/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import {
	type AppContext,
	createApp,
	createContextFactory,
	type Questpie,
	type QuestpieConfig,
} from "questpie";
// ── Module type extraction (inline, no recursive types) ───
import type { UnionToIntersection } from "questpie";

// ── Plugin Singles ─────────────────────────────────────────
import _branding from "../branding";
// ── Collections ────────────────────────────────────────────
import { posts as _coll_posts_collection } from "../collections/posts.collection";
import _dashboard from "../dashboard";
// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings_global } from "../globals/site-settings.global";
// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";
// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";
// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════
import _sidebar from "../sidebar";

type _Module = (typeof _modules)[number];
type _MPRaw<K extends string> = UnionToIntersection<
	_Module extends infer M ? (M extends Record<K, infer V> ? V : never) : never
>;
type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;

type _ModuleCollections = _MP<"collections">;
type _ModuleGlobals = _MP<"globals">;
type _ModuleJobs = _MP<"jobs">;
type _ModuleRoutes = _MP<"routes">;
type _ModuleServices = _MP<"services">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	"posts.collection": typeof _coll_posts_collection;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	"siteSettings.global": typeof _glob_siteSettings_global;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All services in the app (modules + user, user overrides). Values are service instances. */
export type AppServices = _ModuleServices;

/**
 * The fully-typed app instance type.
 * Use `typeof app` or this alias when you need to reference the app type.
 *
 * **Note:** Do NOT import `app` inside framework-defined files (collections,
 * globals, routes, hooks, blocks) — it creates circular dependencies with
 * the generated index. Use the context parameters provided to handlers instead.
 */
export type App = Questpie<
	QuestpieConfig & {
		collections: AppCollections;
		globals: AppGlobals;
		jobs: AppJobs;
		routes: AppRoutes;
		services: AppServices;
	}
>;

// ── AppContext augmentation — auto-types ALL handlers ──────
declare module "questpie" {
	interface AppContext {
		// Infrastructure
		db: App["db"];
		email: App["email"];
		queue: App["queue"];
		storage: App["storage"];
		kv: App["kv"];
		logger: App["logger"];
		search: App["search"];
		realtime: App["realtime"];

		// Entity APIs
		collections: App["api"]["collections"];
		globals: App["api"]["globals"];

		// Request-scoped
		session: Awaited<ReturnType<App["auth"]["api"]["getSession"]>> | null;
		t: (
			key: string,
			params?: Record<string, unknown>,
			locale?: string,
		) => string;
	}
}

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections;
	globals: AppGlobals;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app = (await createApp(
	{
		modules: _modules as any,
		collections: {
			"posts.collection": _coll_posts_collection,
		},
		globals: {
			"siteSettings.global": _glob_siteSettings_global,
		},
		branding: _branding as any,
		dashboard: _dashboard as any,
		sidebar: _sidebar as any,
	},
	_runtime,
)) as unknown as AppConfig & {
	waitForInit(): Promise<void>;
	destroy(): Promise<void>;
};

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export const createContext = createContextFactory(app);
