/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory, extractAppServices, type AppDefinition, type ModuleDefinition, type AppContext, type Registry, type QueueClient, type CollectionAPI } from "questpie";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import { posts as _coll_posts } from "../collections/posts.collection";

// ── Globals ────────────────────────────────────────────────
import { siteSettings as _glob_siteSettings } from "../globals/site-settings.global";

// ── Core Singles ───────────────────────────────────────────
import _authConfig from "../config/auth";

// ── Plugin Singles ─────────────────────────────────────────
import _adminConfig from "../config/admin";
import _openapi from "../config/openapi";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances, UnionToIntersection } from "questpie";
type _Module = (typeof _modules)[number];
type _MPRaw<K extends string> = UnionToIntersection<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;
type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;

type _ModuleCollections = _MP<"collections">;
type _ModuleGlobals = _MP<"globals">;
type _ModuleJobs = _MP<"jobs">;
type _ModuleRoutes = _MP<"routes">;
type _ModuleServices = _MP<"services">;
type _ModuleFieldTypes = _MP<"fieldTypes">;
type _ModuleViews = _MP<"views">;
type _ModuleComponents = _MP<"components">;
type _ModuleBlocks = _MP<"blocks">;
// Registry category extraction from modules
type _Registry_Collections = _MP<"collections">;
type _Registry_Globals = _MP<"globals">;
type _Registry_Jobs = _MP<"jobs">;
type _Registry_Routes = _MP<"routes">;
type _Registry_Services = _MP<"services">;
type _Registry_Emails = _MP<"emails">;
type _Registry_FieldTypes = _MP<"fieldTypes">;
type _Registry_Views = _MP<"views">;
type _Registry_Components = _MP<"components">;
type _Registry_Blocks = _MP<"blocks">;

// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie";

type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	posts: typeof _coll_posts;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	siteSettings: typeof _glob_siteSettings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All service definitions in the app (modules + user, user overrides). */
type _AppServiceDefinitions = _ModuleServices;

/** All services in the app as resolved service instances. */
export type AppServices = {
	[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;
};
type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;
type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;
type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** All fieldtypes in the app (modules + user, user overrides) */
export type AppFieldTypes = _ModuleFieldTypes;

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = _ModuleBlocks;

type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };

// ── AppContext augmentation — auto-types ALL handlers ──────
declare global {
	namespace Questpie {
		interface AppContext extends _AppTopLevelServices, _AppCustomServiceNamespaces {
			// Infrastructure
			db: (typeof app)['db'];
			email: (typeof app)['email'];
			queue: QueueClient<AppJobs>;
			storage: (typeof app)['storage'];
			kv: (typeof app)['kv'];
			logger: (typeof app)['logger'];
			search: (typeof app)['search'];
			realtime: (typeof app)['realtime'];

			// Entity APIs
			collections: _CollectionsAPI;
			globals: (typeof app)['globals'];
			tables: (typeof app)['tables'];

			// Request-scoped
			session: (typeof app)['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;

			// User services
			services: _AppDefaultServices;
		}

		interface ServiceCreateContext extends AppContext {}

		interface Registry {
			collections: _Registry_Collections;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;
			views: _Registry_Views;
			components: _Registry_Components;
			blocks: _Registry_Blocks;
		}
	}
}

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections & Record<string, any>;
	globals: AppGlobals & Record<string, any>;
	routes: AppRoutes;
	auth: typeof _authConfig;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app = await createApp(
	({
		modules: _modules as ModuleDefinition[],
		collections: {
			posts: _coll_posts,
		},
		globals: {
			siteSettings: _glob_siteSettings,
		},
		config: {
			auth: _authConfig as any,
			admin: _adminConfig as any,
			openapi: _openapi as any,
		},
	}) satisfies AppDefinition,
	_runtime,
);

/** Fully typed QUESTPIE app instance. */
export type App = typeof app;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export const createContext = createContextFactory(app);

// Factories: import { collection, global, ... } from '#questpie/factories';
