/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppBookingRouteImport } from './routes/_app/booking'
import { Route as AppSlugRouteImport } from './routes/_app/$slug'
import { Route as AppBlogIndexRouteImport } from './routes/_app/blog.index'
import { Route as AppBarbersIndexRouteImport } from './routes/_app/barbers.index'
import { Route as AppBlogSlugRouteImport } from './routes/_app/blog.$slug'
import { Route as AppBarbersSlugRouteImport } from './routes/_app/barbers.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingRoute = AppBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AppRoute,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AppRoute,
} as any)
const AppBarbersIndexRoute = AppBarbersIndexRouteImport.update({
  id: '/barbers/',
  path: '/barbers/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBarbersSlugRoute = AppBarbersSlugRouteImport.update({
  id: '/barbers/$slug',
  path: '/barbers/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/$slug': typeof AppSlugRoute
  '/booking': typeof AppBookingRoute
  '/contact': typeof AppContactRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/barbers/$slug': typeof AppBarbersSlugRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/barbers': typeof AppBarbersIndexRoute
  '/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof AppSlugRoute
  '/booking': typeof AppBookingRoute
  '/contact': typeof AppContactRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/barbers/$slug': typeof AppBarbersSlugRoute
  '/blog/$slug': typeof AppBlogSlugRoute
  '/barbers': typeof AppBarbersIndexRoute
  '/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/$slug': typeof AppSlugRoute
  '/_app/booking': typeof AppBookingRoute
  '/_app/contact': typeof AppContactRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/barbers/$slug': typeof AppBarbersSlugRoute
  '/_app/blog/$slug': typeof AppBlogSlugRoute
  '/_app/barbers/': typeof AppBarbersIndexRoute
  '/_app/blog/': typeof AppBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/$slug'
    | '/booking'
    | '/contact'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/'
    | '/admin/'
    | '/barbers/$slug'
    | '/blog/$slug'
    | '/barbers'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/booking'
    | '/contact'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/'
    | '/admin'
    | '/barbers/$slug'
    | '/blog/$slug'
    | '/barbers'
    | '/blog'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/$slug'
    | '/_app/booking'
    | '/_app/contact'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/_app/'
    | '/admin/'
    | '/_app/barbers/$slug'
    | '/_app/blog/$slug'
    | '/_app/barbers/'
    | '/_app/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking': {
      id: '/_app/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AppBookingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$slug': {
      id: '/_app/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog/': {
      id: '/_app/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barbers/': {
      id: '/_app/barbers/'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof AppBarbersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blog/$slug': {
      id: '/_app/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barbers/$slug': {
      id: '/_app/barbers/$slug'
      path: '/barbers/$slug'
      fullPath: '/barbers/$slug'
      preLoaderRoute: typeof AppBarbersSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSlugRoute: typeof AppSlugRoute
  AppBookingRoute: typeof AppBookingRoute
  AppContactRoute: typeof AppContactRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBarbersSlugRoute: typeof AppBarbersSlugRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppBarbersIndexRoute: typeof AppBarbersIndexRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSlugRoute: AppSlugRoute,
  AppBookingRoute: AppBookingRoute,
  AppContactRoute: AppContactRoute,
  AppIndexRoute: AppIndexRoute,
  AppBarbersSlugRoute: AppBarbersSlugRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppBarbersIndexRoute: AppBarbersIndexRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiPreviewRoute: ApiPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
