/**
 * Admin Runtime Class
 *
 * Wraps AdminState with runtime methods for accessing configuration.
 * This is what gets passed to AdminProvider and used throughout the admin UI.
 */

import { DEFAULT_LOCALE, DEFAULT_LOCALE_CONFIG } from "questpie/shared";

import type { AdminState } from "./admin-types";
import type { RegisteredAdmin } from "./registry";
import type { ViewKind } from "./view/view";

/**
 * Input type for Admin - accepts Admin instance or plain state.
 *
 * The plain state form is used by generated admin client configs from codegen.
 */
export type AdminInput<TState extends AdminState = AdminState> =
	| Admin<TState>
	| TState;

// ============================================================================
// Admin Class
// ============================================================================

/**
 * Admin runtime instance
 *
 * Provides methods to access admin configuration at runtime.
 *
 * @example
 * ```ts
 * // Generated by `questpie generate`:
 * // import admin from "#questpie/admin/.generated/client";
 * import { Admin } from "@questpie/admin/builder";
 *
 * <AdminLayoutProvider admin={admin} ... />
 * ```
 */
export class Admin<TState extends AdminState = AdminState> {
	constructor(public readonly state: TState) {}

	/**
	 * Normalize input to Admin instance.
	 *
	 * Accepts two input forms:
	 * - `Admin` instance — returned as-is
	 * - Plain `AdminState` object — wraps directly (from codegen)
	 */
	static normalize<TState extends AdminState>(
		input: AdminInput<TState>,
	): Admin<TState> {
		if (input instanceof Admin) {
			return input;
		}
		return new Admin(input as TState);
	}

	// ============================================================================
	// Page Methods
	// ============================================================================

	/**
	 * Get all custom page configurations.
	 */
	getPages(): TState["pages"] {
		return this.state.pages ?? ({} as TState["pages"]);
	}

	/**
	 * Get configuration for a specific page.
	 */
	getPageConfig(name: string): TState["pages"][string] | undefined {
		return (this.state.pages as Record<string, any>)?.[name];
	}

	// ============================================================================
	// Component Methods
	// ============================================================================

	/**
	 * Get all registered component implementations.
	 */
	getComponents(): TState["components"] {
		return this.state.components ?? ({} as TState["components"]);
	}

	/**
	 * Get a specific component implementation by name.
	 */
	getComponent(name: string): TState["components"][string] | undefined {
		return (this.state.components as Record<string, any>)?.[name];
	}

	// ============================================================================
	// View Methods
	// ============================================================================

	/**
	 * Get all registered view definitions (flat map with kind discriminant)
	 */
	getViews(): TState["views"] {
		return this.state.views ?? ({} as TState["views"]);
	}

	/**
	 * Get a specific view definition by name
	 */
	getView(name: string): TState["views"][string] | undefined {
		return (this.state.views as Record<string, any>)?.[name];
	}

	/**
	 * Get all views of a specific kind
	 */
	getViewsByKind(kind: ViewKind): Record<string, any> {
		const views = this.state.views ?? {};
		const result: Record<string, any> = {};
		for (const [name, view] of Object.entries(views as Record<string, any>)) {
			if (view?.kind === kind) {
				result[name] = view;
			}
		}
		return result;
	}

	// ============================================================================
	// Locale Methods
	// ============================================================================

	/**
	 * Get locale configuration
	 */
	getLocale(): TState["locale"] {
		return this.state.locale ?? DEFAULT_LOCALE_CONFIG;
	}

	/**
	 * Get available locales
	 */
	getAvailableLocales(): string[] {
		return this.getLocale().supported ?? [DEFAULT_LOCALE];
	}

	/**
	 * Get default locale
	 */
	getDefaultLocale(): string {
		return this.getLocale().default ?? DEFAULT_LOCALE;
	}

	/**
	 * Get human-readable label for a locale
	 */
	getLocaleLabel(locale: string): string {
		const labels: Record<string, string> = {
			en: "English",
			sk: "Slovencina",
			cs: "Cestina",
			de: "Deutsch",
			fr: "Francais",
			es: "Espanol",
			it: "Italiano",
			pt: "Portugues",
			pl: "Polski",
			nl: "Nederlands",
			ru: "Russkij",
			uk: "Ukrainska",
			ja: "Nihongo",
			ko: "Hangugeo",
			zh: "Zhongwen",
		};
		return labels[locale] ?? locale.toUpperCase();
	}

	// ============================================================================
	// Translations Methods
	// ============================================================================

	/**
	 * Get translations map from state
	 */
	getTranslations(): TState["translations"] {
		return this.state.translations ?? ({} as TState["translations"]);
	}

	// ============================================================================
	// Registry Methods (for field lookups)
	// ============================================================================

	/**
	 * Get all registered field definitions
	 */
	getFields(): TState["fields"] {
		return this.state.fields ?? ({} as TState["fields"]);
	}

	/**
	 * Get a specific field definition
	 */
	getField(name: string): TState["fields"][string] | undefined {
		return (this.state.fields as Record<string, any>)?.[name];
	}

	/**
	 * Get all registered widget definitions
	 */
	getWidgets(): TState["widgets"] {
		return this.state.widgets ?? ({} as TState["widgets"]);
	}
}

// ============================================================================
// Type Helpers
// ============================================================================

/**
 * Infer the app type from an Admin instance
 */
export type InferAdminCMS<TAdmin> =
	TAdmin extends Admin<infer TState>
		? TState extends { "~app": infer TApp }
			? TApp
			: unknown
		: unknown;

/**
 * Get the registered Admin type (from module augmentation)
 */
export type AppAdmin =
	RegisteredAdmin extends Admin<infer TState>
		? Admin<TState>
		: Admin<AdminState>;
