/**
 * Admin Client Template Generator
 *
 * Custom generator for the `admin-client` codegen target.
 * Produces `questpie/admin/.generated/client.ts` — a plain admin config
 * object that replaces `qa().use(adminModule)` setup.
 *
 * The generated file:
 * 1. Imports built-in defaults from `@questpie/admin/client`
 * 2. Imports discovered user files (blocks, views, components, etc.)
 * 3. Merges them into a plain state object (spread over defaults)
 * 4. Exports as default
 *
 * The output is compatible with `AdminInput` — `Admin.normalize()` accepts
 * both `AdminBuilder`, `Admin`, and plain state objects.
 *
 * @see PLAN-PLUGIN-CONSISTENCY.md §6.2 (admin-client target)
 * @see PLAN-PLUGIN-CONSISTENCY.md §7 (Admin Client Generated Artifact)
 */

import type {
	CodegenTargetGenerateContext,
	CodegenTargetOutput,
	DiscoveredFile,
} from "questpie";

/**
 * Category names that the admin-client target discovers.
 * Each category maps to a key on `AdminBuilderState`.
 */
const ADMIN_CATEGORIES = [
	"blocks",
	"views",
	"components",
	"fields",
	"pages",
	"widgets",
] as const;

/**
 * Single file discover keys that map to admin state properties.
 */
const ADMIN_SINGLES: Record<string, string> = {
	locale: "locale",
	translations: "translations",
	defaults: "defaultViews",
};

/**
 * Generate the admin client config file.
 *
 * Called by `runAllTargets()` for the `admin-client` target.
 */
export function generateAdminClientTemplate(
	ctx: CodegenTargetGenerateContext,
): CodegenTargetOutput {
	const lines: string[] = [];

	// Header
	lines.push("/**");
	lines.push(" * Admin Client Config");
	lines.push(" *");
	lines.push(" * Auto-generated by questpie codegen — do not edit.");
	lines.push(" * This file replaces manual `qa().use(adminModule)` setup.");
	lines.push(" *");
	lines.push(" * Pass this directly to <AdminLayoutProvider admin={admin} />");
	lines.push(" */");
	lines.push("");

	// Core import — always present
	lines.push('import { coreAdminModule } from "@questpie/admin/client";');

	// Collect all user file imports
	const userImports: string[] = [];
	const categoryFiles = new Map<string, DiscoveredFile[]>();

	for (const cat of ADMIN_CATEGORIES) {
		const files = ctx.discovered.categories.get(cat);
		if (files && files.size > 0) {
			const sorted = [...files.values()].sort((a, b) =>
				a.key.localeCompare(b.key),
			);
			categoryFiles.set(cat, sorted);
			for (const file of sorted) {
				userImports.push(generateImportLine(file));
			}
		}
	}

	// Import discovered singles
	const singleFiles = new Map<string, DiscoveredFile>();
	for (const [discoverKey, stateKey] of Object.entries(ADMIN_SINGLES)) {
		const file = ctx.discovered.singles.get(discoverKey);
		if (file) {
			singleFiles.set(stateKey, file);
			userImports.push(generateImportLine(file));
		}
	}

	// Add extra imports from transforms
	for (const imp of ctx.extraImports) {
		userImports.push(`import ${imp.name} from "${imp.path}";`);
	}

	if (userImports.length > 0) {
		lines.push("");
		lines.push(...userImports);
	}
	lines.push("");

	// Extract defaults
	lines.push("// Built-in defaults from core admin module");
	lines.push("const _defaults = coreAdminModule.state;");
	lines.push("");

	// Build the merged config object
	const hasAnyUserFiles = categoryFiles.size > 0 || singleFiles.size > 0;

	if (!hasAnyUserFiles && ctx.extraRuntimeCode.length === 0) {
		// No user overrides — just re-export defaults
		lines.push("const admin = _defaults;");
	} else {
		lines.push("const admin = {");
		lines.push("\t..._defaults,");

		// Merge each category that has user files
		for (const cat of ADMIN_CATEGORIES) {
			const files = categoryFiles.get(cat);
			if (!files) continue;

			// For "views", we need special handling — split into listViews/editViews
			// For now, emit as the category key (blocks, components, fields, pages, widgets)
			if (cat === "views") {
				// Views need to be merged into both listViews and editViews based on kind
				// The user should define views with explicit kind — we merge into the flat map
				lines.push(
					`\tlistViews: { ..._defaults.listViews, ...filterViews([${files.map((f) => f.varName).join(", ")}], "list") },`,
				);
				lines.push(
					`\teditViews: { ..._defaults.editViews, ...filterViews([${files.map((f) => f.varName).join(", ")}], "edit") },`,
				);
			} else {
				const entries = files
					.map((f) => `${JSON.stringify(f.key)}: ${f.varName}`)
					.join(", ");
				lines.push(`\t${cat}: { ..._defaults.${cat}, ${entries} },`);
			}
		}

		// Merge discovered singles
		for (const [stateKey, file] of singleFiles) {
			lines.push(`\t${stateKey}: ${file.varName},`);
		}

		// Extra runtime code from transforms
		for (const code of ctx.extraRuntimeCode) {
			lines.push(`\t${code}`);
		}

		lines.push("};");
	}

	// Extra type declarations
	if (ctx.extraTypeDeclarations.length > 0) {
		lines.push("");
		for (const decl of ctx.extraTypeDeclarations) {
			lines.push(decl);
		}
	}

	lines.push("");
	lines.push("export default admin;");
	lines.push("");

	// If views were discovered, we need a helper function
	const hasViews = categoryFiles.has("views");
	let code = lines.join("\n");

	if (hasViews) {
		// Prepend the helper function after imports
		const helperFn = [
			"",
			"/** Filter view definitions by kind */",
			'function filterViews(views: any[], kind: "list" | "edit"): Record<string, any> {',
			"\tconst result: Record<string, any> = {};",
			"\tfor (const view of views) {",
			"\t\tconst v = view && typeof view === 'object' && 'state' in view ? view.state : view;",
			"\t\tif (v && v.kind === kind) { result[v.name] = view; }",
			"\t}",
			"\treturn result;",
			"}",
		].join("\n");

		// Insert after imports, before the defaults extraction
		const defaultsLine = "// Built-in defaults from core admin module";
		code = code.replace(defaultsLine, `${helperFn}\n\n${defaultsLine}`);
	}

	return { code };
}

// ============================================================================
// Helpers
// ============================================================================

/**
 * Generate an import line for a discovered file.
 */
function generateImportLine(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}
