/**
 * Admin Codegen Tests
 *
 * Tests for:
 * 1. `generateAdminClientTemplate()` — admin-client target code generation
 * 2. `createAdminProjectionValidator()` — cross-target projection validation
 */

import { describe, expect, it } from "bun:test";

import type {
	CategoryDeclaration,
	CodegenResult,
	CodegenTargetGenerateContext,
	DiscoveredFile,
	DiscoveryResult,
	ResolvedTarget,
} from "questpie";

import { generateAdminClientTemplate } from "#questpie/admin/server/codegen/admin-client-template";
import { createAdminProjectionValidator } from "#questpie/admin/server/codegen/projection-validator";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function makeFile(
	key: string,
	opts: {
		varName?: string;
		importPath?: string;
		exportType?: "default" | "named" | "unknown";
		namedExportName?: string;
		source?: string;
	} = {},
): DiscoveredFile {
	return {
		absolutePath: `/root/${key}.ts`,
		key,
		varName: opts.varName ?? `_${key.replace(/[./]/g, "_")}`,
		importPath: opts.importPath ?? `../${key}`,
		exportType: opts.exportType ?? "default",
		namedExportName: opts.namedExportName,
		source: opts.source ?? `${key}.ts`,
	};
}

function emptyDiscovery(): DiscoveryResult {
	return {
		categories: new Map(),
		auth: null,
		singles: new Map(),
		spreads: new Map(),
	};
}

function makeTarget(overrides: Partial<ResolvedTarget> = {}): ResolvedTarget {
	return {
		id: "admin-client",
		root: "../admin",
		outDir: ".generated",
		outputFile: "client.ts",
		categories: {},
		discover: {},
		registries: {
			collectionExtensions: {},
			globalExtensions: {},
			singletonFactories: {},
		},
		callbackParams: {},
		transforms: [],
		...overrides,
	};
}

function makeCtx(
	discovered: DiscoveryResult,
	target?: Partial<ResolvedTarget>,
): CodegenTargetGenerateContext {
	return {
		target: makeTarget(target),
		discovered,
		extraImports: [],
		extraTypeDeclarations: [],
		extraRuntimeCode: [],
		extraEntities: new Map(),
	};
}

function makeFakeResult(
	targetId: string,
	categories: Record<string, string[]>,
): CodegenResult {
	const catMap = new Map<string, Map<string, DiscoveredFile>>();
	for (const [catName, keys] of Object.entries(categories)) {
		const fileMap = new Map<string, DiscoveredFile>();
		for (const key of keys) {
			fileMap.set(
				key,
				makeFile(key, {
					varName: `_${catName}_${key}`,
					importPath: `../${catName}/${key}`,
					exportType: "default",
				}),
			);
		}
		catMap.set(catName, fileMap);
	}

	return {
		targetId,
		code: "// fake",
		outputPath: `/fake/.generated/${targetId}.ts`,
		discovered: {
			categories: catMap,
			auth: null,
			singles: new Map(),
			spreads: new Map(),
		},
	};
}

// ─────────────────────────────────────────────────────────────────────────────
// generateAdminClientTemplate
// ─────────────────────────────────────────────────────────────────────────────

describe("generateAdminClientTemplate", () => {
	it("emits empty object when no modules or user files discovered", () => {
		const ctx = makeCtx(emptyDiscovery());
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain("const admin = {};");
		expect(output.code).toContain("export default admin;");
		// Should NOT reference coreAdminModule
		expect(output.code).not.toContain("coreAdminModule");
	});

	it("re-exports module directly when no user files discovered", () => {
		const disc = emptyDiscovery();
		disc.singles.set(
			"modules",
			makeFile("modules", {
				varName: "_mod",
				importPath: "../modules",
				exportType: "default",
			}),
		);

		const ctx = makeCtx(disc);
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain('import _mod from "../modules";');
		expect(output.code).toContain("const admin = _mod;");
		expect(output.code).toContain("export default admin;");
	});

	it("emits auto-generated header comment", () => {
		const ctx = makeCtx(emptyDiscovery());
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain("Auto-generated by questpie codegen");
		expect(output.code).toContain("do not edit");
	});

	it("imports and merges discovered blocks with module", () => {
		const disc = emptyDiscovery();

		// Module
		disc.singles.set(
			"modules",
			makeFile("modules", {
				varName: "_mod",
				importPath: "../modules",
				exportType: "default",
			}),
		);

		// User blocks
		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"hero",
			makeFile("hero", {
				varName: "_block_hero",
				importPath: "../blocks/hero",
				exportType: "default",
			}),
		);
		blocksMap.set(
			"cta",
			makeFile("cta", {
				varName: "_block_cta",
				importPath: "../blocks/cta",
				exportType: "default",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		// Imports
		expect(output.code).toContain('import _mod from "../modules";');
		expect(output.code).toContain('import _block_cta from "../blocks/cta";');
		expect(output.code).toContain('import _block_hero from "../blocks/hero";');
		// Merged object with module spread
		expect(output.code).toContain("blocks: { ..._mod.blocks,");
		expect(output.code).toContain('"cta": _block_cta');
		expect(output.code).toContain('"hero": _block_hero');
	});

	it("keys discovered blocks by source basename", () => {
		const disc = emptyDiscovery();

		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"imageText",
			makeFile("imageText", {
				varName: "_block_imageText",
				importPath: "../blocks/image-text",
				source: "blocks/image-text.tsx",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain(
			'blocks: { "image-text": _block_imageText },',
		);
		expect(output.code).not.toContain('"imageText": _block_imageText');
	});

	it("emits blocks without module when no modules discovered", () => {
		const disc = emptyDiscovery();

		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"hero",
			makeFile("hero", {
				varName: "_block_hero",
				importPath: "../blocks/hero",
				exportType: "default",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		// No module import
		expect(output.code).not.toContain("_mod");
		// User blocks only
		expect(output.code).toContain('blocks: { "hero": _block_hero },');
	});

	it("merges discovered views using keyFromProperty", () => {
		const disc = emptyDiscovery();

		disc.singles.set(
			"modules",
			makeFile("modules", {
				varName: "_mod",
				importPath: "../modules",
				exportType: "default",
			}),
		);

		const viewsMap = new Map<string, DiscoveredFile>();
		viewsMap.set(
			"kanban",
			makeFile("kanban", {
				varName: "_view_kanban",
				importPath: "../views/kanban",
				exportType: "default",
			}),
		);
		disc.categories.set("views", viewsMap);

		const ctx = makeCtx(disc, {
			categories: {
				views: {
					dirs: ["views"],
					prefix: "view",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
					keyFromProperty: "name",
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		// Should emit runtime key using keyFromProperty
		expect(output.code).toContain("views: { ..._mod.views,");
		expect(output.code).toContain("[_view_kanban.name]: _view_kanban");
	});

	it("merges discovered singles into state keys", () => {
		const disc = emptyDiscovery();
		disc.singles.set(
			"locale",
			makeFile("locale", {
				varName: "_locale",
				importPath: "../locale",
				exportType: "default",
			}),
		);
		disc.singles.set(
			"defaults",
			makeFile("defaults", {
				varName: "_defaults_file",
				importPath: "../defaults",
				exportType: "default",
			}),
		);

		const ctx = makeCtx(disc);
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain("locale: _locale,");
		expect(output.code).toContain("defaults: _defaults_file,");
	});

	it("handles named exports correctly", () => {
		const disc = emptyDiscovery();
		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"hero",
			makeFile("hero", {
				varName: "_block_hero",
				importPath: "../blocks/hero",
				exportType: "named",
				namedExportName: "heroBlock",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain(
			'import { heroBlock as _block_hero } from "../blocks/hero";',
		);
	});

	it("includes extra runtime code from transforms", () => {
		const disc = emptyDiscovery();
		// Need at least one user file to trigger the object
		disc.singles.set(
			"locale",
			makeFile("locale", {
				varName: "_locale",
				importPath: "../locale",
				exportType: "default",
			}),
		);

		const ctx = makeCtx(disc);
		ctx.extraRuntimeCode.push('customProp: "hello",');

		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain('customProp: "hello",');
	});

	it("includes extra type declarations from transforms", () => {
		const ctx = makeCtx(emptyDiscovery());
		ctx.extraTypeDeclarations.push("export type CustomType = string;");

		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain("export type CustomType = string;");
	});

	it("merges multiple categories together with module", () => {
		const disc = emptyDiscovery();

		disc.singles.set(
			"modules",
			makeFile("modules", {
				varName: "_mod",
				importPath: "../modules",
				exportType: "default",
			}),
		);

		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"hero",
			makeFile("hero", {
				varName: "_block_hero",
				importPath: "../blocks/hero",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const fieldsMap = new Map<string, DiscoveredFile>();
		fieldsMap.set(
			"color",
			makeFile("color", {
				varName: "_fld_color",
				importPath: "../fields/color",
			}),
		);
		disc.categories.set("fields", fieldsMap);

		const pagesMap = new Map<string, DiscoveredFile>();
		pagesMap.set(
			"analytics",
			makeFile("analytics", {
				varName: "_pg_analytics",
				importPath: "../pages/analytics",
			}),
		);
		disc.categories.set("pages", pagesMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
				fields: {
					dirs: ["fields"],
					prefix: "fld",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
				pages: {
					dirs: ["pages"],
					prefix: "pg",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		expect(output.code).toContain("blocks: { ..._mod.blocks,");
		expect(output.code).toContain("fields: { ..._mod.fields,");
		expect(output.code).toContain("pages: { ..._mod.pages,");
		expect(output.code).toContain('"hero": _block_hero');
		expect(output.code).toContain('"color": _fld_color');
		expect(output.code).toContain('"analytics": _pg_analytics');
	});

	it("spreads module categories even when no user files exist for that category", () => {
		const disc = emptyDiscovery();

		disc.singles.set(
			"modules",
			makeFile("modules", {
				varName: "_mod",
				importPath: "../modules",
				exportType: "default",
			}),
		);

		// Only blocks from user, but fields/views/etc. declared in target
		const blocksMap = new Map<string, DiscoveredFile>();
		blocksMap.set(
			"hero",
			makeFile("hero", {
				varName: "_block_hero",
				importPath: "../blocks/hero",
			}),
		);
		disc.categories.set("blocks", blocksMap);

		const ctx = makeCtx(disc, {
			categories: {
				blocks: {
					dirs: ["blocks"],
					prefix: "block",
					keyFromSource: "basename",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
				fields: {
					dirs: ["fields"],
					prefix: "fld",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
				},
				views: {
					dirs: ["views"],
					prefix: "view",
					registryKey: false,
					includeInAppState: false,
					extractFromModules: false,
					keyFromProperty: "name",
				},
			},
		});
		const output = generateAdminClientTemplate(ctx);

		// Module-only categories should be spread
		expect(output.code).toContain("fields: { ..._mod.fields },");
		expect(output.code).toContain("views: { ..._mod.views },");
		// User category should merge
		expect(output.code).toContain("blocks: { ..._mod.blocks,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// createAdminProjectionValidator
// ─────────────────────────────────────────────────────────────────────────────

describe("createAdminProjectionValidator", () => {
	const validator = createAdminProjectionValidator();

	it("returns no errors when both targets are absent", () => {
		const targets = new Map<string, CodegenResult>();
		expect(validator(targets)).toEqual([]);
	});

	it("returns no errors when only server target exists (no admin-client)", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set("server", makeFakeResult("server", { blocks: ["hero"] }));
		expect(validator(targets)).toEqual([]);
	});

	it("returns no errors when only admin-client target exists (no server)", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", { blocks: ["hero"] }),
		);
		expect(validator(targets)).toEqual([]);
	});

	it("returns no errors when server and client blocks match", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"server",
			makeFakeResult("server", { blocks: ["hero", "cta"] }),
		);
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", { blocks: ["hero", "cta"] }),
		);

		const errors = validator(targets);
		expect(errors).toEqual([]);
	});

	it("reports error for missing block renderer in admin-client", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"server",
			makeFakeResult("server", { blocks: ["hero", "gallery"] }),
		);
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", { blocks: ["hero"] }),
		);

		const errors = validator(targets);
		expect(errors.length).toBe(1);
		expect(errors[0].severity).toBe("error");
		expect(errors[0].category).toBe("blocks");
		expect(errors[0].key).toBe("gallery");
		expect(errors[0].sourceTarget).toBe("server");
		expect(errors[0].consumerTarget).toBe("admin-client");
		expect(errors[0].message).toContain("gallery");
		expect(errors[0].message).toContain("questpie/admin/blocks");
	});

	it("reports error for missing view definition in admin-client", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set("server", makeFakeResult("server", { views: ["kanban"] }));
		targets.set("admin-client", makeFakeResult("admin-client", { views: [] }));

		const errors = validator(targets);
		expect(errors.length).toBe(1);
		expect(errors[0].category).toBe("views");
		expect(errors[0].key).toBe("kanban");
		expect(errors[0].message).toContain("questpie/admin/views");
	});

	it("reports error for missing component definition in admin-client", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set("server", makeFakeResult("server", { components: ["rating"] }));
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", { components: [] }),
		);

		const errors = validator(targets);
		expect(errors.length).toBe(1);
		expect(errors[0].category).toBe("components");
		expect(errors[0].key).toBe("rating");
		expect(errors[0].message).toContain("questpie/admin/components");
	});

	it("reports multiple errors across multiple categories", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"server",
			makeFakeResult("server", {
				blocks: ["hero", "gallery"],
				views: ["kanban"],
				components: ["rating", "badge"],
			}),
		);
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", {
				blocks: ["hero"],
				views: [],
				components: ["badge"],
			}),
		);

		const errors = validator(targets);
		// Missing: gallery (block), kanban (view), rating (component)
		expect(errors.length).toBe(3);

		const blockErr = errors.find(
			(e) => e.category === "blocks" && e.key === "gallery",
		);
		const viewErr = errors.find((e) => e.category === "views");
		const compErr = errors.find(
			(e) => e.category === "components" && e.key === "rating",
		);

		expect(blockErr).toBeDefined();
		expect(viewErr).toBeDefined();
		expect(viewErr!.key).toBe("kanban");
		expect(compErr).toBeDefined();
	});

	it("ignores categories not in PROJECTION_CHECKS", () => {
		const targets = new Map<string, CodegenResult>();
		// "widgets" is not checked by the admin projection validator
		targets.set("server", makeFakeResult("server", { widgets: ["stats"] }));
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", { widgets: [] }),
		);

		const errors = validator(targets);
		expect(errors).toEqual([]);
	});

	it("returns no errors when server has empty categories", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"server",
			makeFakeResult("server", { blocks: [], views: [], components: [] }),
		);
		targets.set("admin-client", makeFakeResult("admin-client", {}));

		const errors = validator(targets);
		expect(errors).toEqual([]);
	});

	it("handles missing category in client gracefully", () => {
		const targets = new Map<string, CodegenResult>();
		// Server has blocks, but admin-client has no blocks category at all
		targets.set("server", makeFakeResult("server", { blocks: ["hero"] }));
		targets.set(
			"admin-client",
			makeFakeResult("admin-client", {}), // no blocks category
		);

		const errors = validator(targets);
		expect(errors.length).toBe(1);
		expect(errors[0].category).toBe("blocks");
		expect(errors[0].key).toBe("hero");
	});

	it("includes suggestedDir in error messages", () => {
		const targets = new Map<string, CodegenResult>();
		targets.set(
			"server",
			makeFakeResult("server", {
				blocks: ["hero"],
				views: ["kanban"],
				components: ["rating"],
			}),
		);
		targets.set("admin-client", makeFakeResult("admin-client", {}));

		const errors = validator(targets);

		const blockErr = errors.find((e) => e.category === "blocks")!;
		const viewErr = errors.find((e) => e.category === "views")!;
		const compErr = errors.find((e) => e.category === "components")!;

		expect(blockErr.message).toContain("questpie/admin/blocks/hero.tsx");
		expect(viewErr.message).toContain("questpie/admin/views/kanban.tsx");
		expect(compErr.message).toContain("questpie/admin/components/rating.tsx");
	});
});
