/**
 * Factory Template Generation
 *
 * Generates `.generated/factories.ts` — typed `collection()` and `global()`
 * factory functions with plugin extensions, singleton factory functions
 * (branding, sidebar, locale, etc.), and module-driven type extraction
 * for autocomplete on proxies (views, components, field types).
 *
 * Extension methods are intercepted by `wrapBuilderWithExtensions()` which
 * delegates to `builder.set()`. Initial state is created by `Builder.create()`.
 *
 * @see RFC-CONTEXT-FIRST §6 (Extension System Without Monkey-Patching)
 * @see QUE-163 — Codegen Simplification
 */

import type {
	BuilderFactory,
	CallbackParamDefinition,
	CategoryDeclaration,
	RegistryExtension,
	ResolvedTarget,
	SingletonFactory,
} from "./types.js";

// ============================================================================
// Factory generation
// ============================================================================

export interface FactoryTemplateOptions {
	/** The resolved target with merged registries and callback params. */
	target: ResolvedTarget;
	/** Whether modules.ts exists (new architecture). */
	hasModules: boolean;
	/**
	 * Import path for the user's fields.ts file, if one exists.
	 * Relative path from the .generated/ output directory.
	 * When present, the default export is spread into _allFieldDefs.
	 */
	userFieldsImportPath?: string;
}

/**
 * Generate `.generated/factories.ts` content.
 * Always generates — even with zero extensions, exports `collection()` and `global()`
 * as thin wrappers around `Builder.create()`.
 */
export function generateFactoryTemplate(
	options: FactoryTemplateOptions,
): string {
	const { target, hasModules, userFieldsImportPath } = options;

	// Extract merged registries and callback params from the resolved target
	const collExtensions = new Map<string, RegistryExtension>();
	const globalExtensions = new Map<string, RegistryExtension>();
	const fieldExtensions = new Map<string, RegistryExtension>();
	const singletonFactories = new Map<string, SingletonFactory>();
	const allImports = new Map<string, Set<string>>(); // from → Set<name>

	for (const [name, ext] of Object.entries(
		target.registries.collectionExtensions,
	)) {
		collExtensions.set(name, ext);
		collectImports(ext, allImports);
	}

	for (const [name, ext] of Object.entries(
		target.registries.globalExtensions,
	)) {
		globalExtensions.set(name, ext);
		collectImports(ext, allImports);
	}

	for (const [name, ext] of Object.entries(target.registries.fieldExtensions)) {
		fieldExtensions.set(name, ext);
		collectImports(ext, allImports);
	}

	for (const [name, factory] of Object.entries(
		target.registries.singletonFactories,
	)) {
		singletonFactories.set(name, factory);
		collectSingletonImports(factory, allImports);
	}

	// Categories with placeholder/recordPlaceholder/typeRegistry (drive type extraction)
	const registryCategories = new Map<string, CategoryDeclaration>();
	for (const [key, decl] of Object.entries(target.categories)) {
		if (decl.placeholder || decl.recordPlaceholder || decl.typeRegistry) {
			registryCategories.set(key, decl);
		}
	}

	// Callback params from the resolved target
	const callbackParams = new Map<string, CallbackParamDefinition>();
	for (const [key, def] of Object.entries(target.callbackParams)) {
		callbackParams.set(key, def);
	}

	// Collect imports for callback param factory functions (only when extensions exist)
	const hasExtensions = collExtensions.size > 0 || globalExtensions.size > 0;
	const hasFieldExtensions = fieldExtensions.size > 0;
	if (hasExtensions || hasFieldExtensions) {
		collectCallbackParamImports(callbackParams, allImports);
	}

	// Collect all configTypePlaceholders → category mappings
	const placeholderCategories = new Map<string, string>();
	for (const ext of [
		...collExtensions.values(),
		...globalExtensions.values(),
		...fieldExtensions.values(),
	]) {
		if (ext.configTypePlaceholders) {
			for (const [placeholder, category] of Object.entries(
				ext.configTypePlaceholders,
			)) {
				placeholderCategories.set(placeholder, category);
			}
		}
	}

	const lines: string[] = [];

	// Header
	lines.push("/* oxlint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push(
		"// Typed factory functions with plugin extensions. Regenerate with: questpie generate",
	);
	lines.push("");

	// Core imports — always import builders; conditionally import wrapBuilderWithExtensions
	// Also import builtinFields (runtime value) for constructing the merged field defs map
	lines.push("// ── Core Imports ───────────────────────────────────────────");
	if (hasExtensions || hasFieldExtensions) {
		const fieldImport = hasFieldExtensions ? ", Field" : "";
		lines.push(
			`import { CollectionBuilder, GlobalBuilder, wrapBuilderWithExtensions, builtinFields, type EmptyCollectionState, type EmptyGlobalState, type BuiltinFields${fieldImport} } from "questpie";`,
		);
	} else {
		lines.push(
			'import { CollectionBuilder, GlobalBuilder, builtinFields, type EmptyCollectionState, type EmptyGlobalState, type BuiltinFields } from "questpie";',
		);
	}
	lines.push("");

	// Runtime field imports from plugins (e.g. adminFields from @questpie/admin/server)
	// These are spread-merged with builtinFields to create _allFieldDefs, which is
	// passed to CollectionBuilder.create() / GlobalBuilder.create() so that
	// .fields(({ f }) => ...) callbacks have access to ALL field types at runtime.
	//
	// Sourced from factoryImports on the fieldTypes category declaration.
	const fieldTypesCategory = target.categories.fieldTypes;
	const runtimeFieldImports: Array<{ name: string; from: string }> =
		fieldTypesCategory?.factoryImports ?? [];
	if (runtimeFieldImports.length > 0 || userFieldsImportPath) {
		lines.push(
			"// ── Runtime Field Imports ──────────────────────────────────",
		);
		for (const { name, from } of runtimeFieldImports) {
			lines.push(`import { ${name} } from "${from}";`);
		}
		if (userFieldsImportPath) {
			lines.push(`import _userFields from "${userFieldsImportPath}";`);
		}
		lines.push("");
	}

	// Emit field extension registry early (before field defs, which reference it)
	if (hasFieldExtensions) {
		emitExtensionRegistry(lines, "_fieldExt", fieldExtensions, callbackParams);
		lines.push("");
	}

	// Build merged field defs constant — builtinFields + plugin fields + user fields
	{
		const spreads = ["...builtinFields"];
		for (const { name } of runtimeFieldImports) {
			spreads.push(`...${name}`);
		}
		if (userFieldsImportPath) {
			spreads.push("..._userFields");
		}
		lines.push(
			"// Merged field factories — builtins + module-contributed (e.g. richText, blocks) + user fields",
		);
		lines.push(`const _rawFieldDefs = { ${spreads.join(", ")} } as const;`);
		lines.push("");

		// When field extensions exist, wrap each field factory so returned Field instances
		// go through the extension proxy (intercepting .admin(), .form(), etc.)
		if (hasFieldExtensions) {
			lines.push(
				"// Wrap field factories so returned Field instances have extension methods",
			);
			lines.push(
				"function _wrapFieldFactory(fn: (...args: any[]) => any): (...args: any[]) => any {",
			);
			lines.push(
				"\treturn (...args: any[]) => wrapBuilderWithExtensions(fn(...args), _fieldExt, Field);",
			);
			lines.push("}");
			lines.push("");
			lines.push("const _allFieldDefs = Object.fromEntries(");
			lines.push(
				"\tObject.entries(_rawFieldDefs).map(([k, v]) => [k, _wrapFieldFactory(v as any)])",
			);
			lines.push(") as unknown as typeof _rawFieldDefs;");
		} else {
			lines.push("const _allFieldDefs = _rawFieldDefs;");
		}
		lines.push("");
	}

	// NOTE: No module import here — factories.ts must NOT reference typeof _modulesArr
	// to avoid circular references. Type information flows through augmentable
	// interfaces (Questpie.ViewsRegistry, Questpie.ComponentsRegistry, Questpie.FieldTypesMap)
	// which are populated by each module's codegen output independently.

	// Plugin imports (only types needed for signatures)
	if (allImports.size > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const [from, names] of allImports) {
			const nameList = [...names]
				.filter((n) => /^[A-Z]/.test(n)) // only types (PascalCase)
				.map((n) => `type ${n}`)
				.join(", ");
			const valueList = [...names]
				.filter((n) => /^[a-z]/.test(n)) // runtime values (camelCase)
				.join(", ");
			const parts = [nameList, valueList].filter(Boolean).join(", ");
			if (parts) {
				lines.push(`import { ${parts} } from "${from}";`);
			}
		}
		lines.push("");
	}

	// ── Type extraction — driven by CategoryDeclaration ──────────
	// ALL type aliases (both names and records) use augmentable interfaces
	// (Questpie.ViewsRegistry, Questpie.ComponentsRegistry) instead of
	// RegistryProp<> or ExtractModuleProp<typeof _modulesArr, ...>.
	// This breaks TWO circular reference chains:
	//
	//   Cycle 1 (recordPlaceholder):
	//     factories.ts augments CollectionBuilder → uses _ViewsRecord
	//     → was: ExtractModuleProp<typeof _modulesArr, "views"> → typeof _modulesArr
	//     → admin module → CollectionBuilder → CYCLE
	//
	//   Cycle 2 (placeholder — THE CRITICAL ONE):
	//     factories.ts augments CollectionBuilder → uses _ViewsNames
	//     → was: keyof RegistryProp<"views"> → Registry["views"]
	//     → Registry augmented from _Module → typeof _modules
	//     → admin module → CollectionBuilder → CYCLE
	//
	//   Now: Both read from Questpie.*Registry (populated independently by each
	//   module's codegen output, no reference to typeof _modules or Registry)
	//   → NO CYCLE
	if (registryCategories.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Type extraction — driven by CategoryDeclaration");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		// Generate type aliases for each category
		// Both placeholder (names) and recordPlaceholder (records) use
		// augmentable interfaces — never RegistryProp (which reads from Registry)
		for (const [key, decl] of registryCategories) {
			const cap = key.charAt(0).toUpperCase() + key.slice(1);
			const interfaceName = `${cap}Registry`;

			if (decl.placeholder) {
				const typeName = `_${cap}Names`;
				// Read from augmentable interface — NOT from Registry via RegistryProp
				lines.push(
					`type ${typeName} = (keyof Questpie.${interfaceName} & string) | (string & {});`,
				);
				if (decl.typeRegistry) {
					lines.push(
						`type ${typeName}_Strict = keyof Questpie.${interfaceName} & string;`,
					);
				}
			}
			if (decl.recordPlaceholder) {
				const recordTypeName = `_${cap}Record`;
				// Use augmentable interface — populated by module codegen, NOT typeof _modulesArr
				lines.push(`type ${recordTypeName} = Questpie.${interfaceName};`);
			}
		}
		lines.push("");
	}

	// Field types — from augmentable interface (populated by module codegen)
	lines.push(
		"// Field types — populated by module codegen via Questpie.FieldTypesMap",
	);
	lines.push("type _AllFieldTypes = Questpie.FieldTypesMap;");
	lines.push("");

	// ── Type augmentations (declare module) ────────────────────
	if (hasExtensions || hasFieldExtensions || registryCategories.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Type augmentations — generated from plugin registries");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		const placeholderMap = buildPlaceholderMap(registryCategories);

		// Builder interface augmentations — keep declare module "questpie" for class merging
		if (
			collExtensions.size > 0 ||
			globalExtensions.size > 0 ||
			fieldExtensions.size > 0
		) {
			lines.push('declare module "questpie" {');

			if (collExtensions.size > 0) {
				lines.push("\tinterface CollectionBuilder<TState> {");
				for (const [name, ext] of collExtensions) {
					const paramName = ext.isCallback ? "configFn" : "config";
					let paramType = ext.configType ?? "any";
					paramType = resolvePlaceholders(
						paramType,
						hasModules,
						placeholderMap,
					);
					lines.push(
						`\t\t${name}(${paramName}: ${paramType}): CollectionBuilder<TState>;`,
					);
				}
				lines.push("\t}");
			}

			if (globalExtensions.size > 0) {
				lines.push("\tinterface GlobalBuilder<TState> {");
				for (const [name, ext] of globalExtensions) {
					const paramName = ext.isCallback ? "configFn" : "config";
					let paramType = ext.configType ?? "any";
					paramType = resolvePlaceholders(
						paramType,
						hasModules,
						placeholderMap,
					);
					lines.push(
						`\t\t${name}(${paramName}: ${paramType}): GlobalBuilder<TState>;`,
					);
				}
				lines.push("\t}");
			}

			if (fieldExtensions.size > 0) {
				lines.push("\tinterface Field<TState> {");
				for (const [name, ext] of fieldExtensions) {
					const paramName = ext.isCallback ? "configFn" : "config";
					let paramType = ext.configType ?? "any";
					paramType = resolvePlaceholders(
						paramType,
						hasModules,
						placeholderMap,
					);
					lines.push(`\t\t${name}(${paramName}: ${paramType}): Field<TState>;`);
				}
				lines.push("\t}");
			}

			lines.push("}");
			lines.push("");
		}

		// FieldTypeRegistry and type registries — use declare global (symlink-safe)
		lines.push("declare global {");
		lines.push("\tnamespace Questpie {");

		// Ensure FieldTypesMap always includes builtin fields
		lines.push("\t\tinterface FieldTypesMap extends BuiltinFields {}");
		lines.push(
			"\t\tinterface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}",
		);

		// Type registries from categories that target "questpie" module
		for (const [key, decl] of registryCategories) {
			if (decl.typeRegistry?.module === "questpie") {
				const strictName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names_Strict`;
				lines.push(
					`\t\tinterface ${decl.typeRegistry.interface} extends Record<${strictName}, {}> {}`,
				);
			}
		}

		lines.push("\t}");
		lines.push("}");
		lines.push("");

		// Type registries from categories that target other modules
		const externalTypeRegistries = new Map<
			string,
			Array<{ key: string; decl: CategoryDeclaration }>
		>();
		for (const [key, decl] of registryCategories) {
			if (decl.typeRegistry && decl.typeRegistry.module !== "questpie") {
				let entries = externalTypeRegistries.get(decl.typeRegistry.module);
				if (!entries) {
					entries = [];
					externalTypeRegistries.set(decl.typeRegistry.module, entries);
				}
				entries.push({ key, decl });
			}
		}

		for (const [moduleName, entries] of externalTypeRegistries) {
			lines.push(`declare module "${moduleName}" {`);
			for (const { key, decl } of entries) {
				const strictName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names_Strict`;
				lines.push(
					`\tinterface ${decl.typeRegistry?.interface} extends Record<${strictName}, {}> {}`,
				);
			}
			lines.push("}");
			lines.push("");
		}
	}

	// ── Extension registries ─────────────────────────────────
	if (hasExtensions || hasFieldExtensions) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Extension registries");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		if (collExtensions.size > 0) {
			emitExtensionRegistry(lines, "_collExt", collExtensions, callbackParams);
			lines.push("");
		}

		if (globalExtensions.size > 0) {
			emitExtensionRegistry(
				lines,
				"_globExt",
				globalExtensions,
				callbackParams,
			);
			lines.push("");
		}

		// Note: _fieldExt is emitted earlier (before field defs) since _allFieldDefs references it
	}

	// ── Factory functions ─────────────────────────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Factory functions");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// collection() — always emitted
	lines.push("/**");
	lines.push(" * Create a typed collection builder with plugin extensions.");
	lines.push(" *");
	lines.push(" * @example");
	lines.push(" * ```ts");
	lines.push(' * import { collection } from "#questpie/factories";');
	lines.push(" *");
	lines.push(' * export default collection("posts")');
	lines.push(" *   .fields(({ f }) => ({ title: f.text(255).required() }))");
	if (collExtensions.size > 0) {
		lines.push(' *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))');
		lines.push(
			" *   .list(({ v, f }) => v.collectionTable({ columns: [f.title] }))",
		);
	}
	lines.push(" * ```");
	lines.push(" */");
	lines.push(
		"export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {",
	);
	if (collExtensions.size > 0) {
		lines.push(
			"\treturn wrapBuilderWithExtensions(CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs), _collExt, CollectionBuilder) as any;",
		);
	} else {
		lines.push(
			"\treturn CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);",
		);
	}
	lines.push("}");
	lines.push("");

	// global() — always emitted
	lines.push("/**");
	lines.push(" * Create a typed global builder with plugin extensions.");
	lines.push(" */");
	lines.push(
		"export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {",
	);
	if (globalExtensions.size > 0) {
		lines.push(
			"\treturn wrapBuilderWithExtensions(GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs), _globExt, GlobalBuilder) as any;",
		);
	} else {
		lines.push(
			"\treturn GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs);",
		);
	}
	lines.push("}");
	lines.push("");

	// ── Builder factory functions (plugin-contributed) ─────────
	const builderFactories = new Map<string, BuilderFactory>();
	for (const [name, factory] of Object.entries(
		target.registries.builderFactories,
	)) {
		builderFactories.set(name, factory);
	}
	if (builderFactories.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Builder factory functions (plugin-contributed)");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		for (const [name, factory] of builderFactories) {
			// Import the builder class
			lines.push(
				`import { ${factory.import.name} } from "${factory.import.from}";`,
			);
			const generic = factory.genericSignature ?? "<TName extends string>";
			const returnType = factory.returnType
				? factory.returnType.replace("$CLASS", factory.builderClass)
				: `ReturnType<typeof ${factory.builderClass}.${factory.createMethod}>`;
			lines.push("/**");
			lines.push(` * Create a typed ${name} builder with wrapped field defs.`);
			lines.push(" */");
			lines.push(
				`export function ${name}${generic}(name: TName): ${returnType} {`,
			);
			lines.push(
				`\treturn ${factory.builderClass}.${factory.createMethod}(name, _allFieldDefs) as any;`,
			);
			lines.push("}");
			lines.push("");
		}
	}

	// ── Singleton factory functions ────────────────────────────
	if (singletonFactories.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Singleton factory functions");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		for (const [name, factory] of singletonFactories) {
			emitSingletonFactory(lines, name, factory);
			lines.push("");
		}
	}

	return lines.join("\n");
}

// ============================================================================
// Singleton factory emission
// ============================================================================

/**
 * Emit a singleton factory function.
 * Non-callback: simple generic identity with type constraint.
 * Callback: overloaded identity accepting both plain config and callback.
 */
function emitSingletonFactory(
	lines: string[],
	name: string,
	factory: SingletonFactory,
): void {
	const { configType, isCallback } = factory;

	if (isCallback) {
		// Overloaded — accepts plain config or callback function
		lines.push(
			`/** Typed factory for ${name} config. Accepts plain config or callback. */`,
		);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T;`,
		);
		lines.push(
			`export function ${name}<T extends (...args: any[]) => ${configType}>(cb: T): T;`,
		);
		lines.push(`export function ${name}(v: any): any { return v; }`);
	} else {
		// Simple identity with type constraint
		lines.push(`/** Typed factory for ${name} config. */`);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T { return config; }`,
		);
	}
}

// ============================================================================
// Placeholder resolution
// ============================================================================

/**
 * Build a placeholder → type alias mapping from categories with placeholder/recordPlaceholder.
 */
function buildPlaceholderMap(
	categories: Map<string, CategoryDeclaration>,
): Record<string, { withModules: string; fallback: string }> {
	const map: Record<string, { withModules: string; fallback: string }> = {};
	for (const [key, decl] of categories) {
		if (decl.placeholder) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			map[decl.placeholder] = { withModules: typeName, fallback: "string" };
		}
		if (decl.recordPlaceholder) {
			const recordTypeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Record`;
			map[decl.recordPlaceholder] = {
				withModules: recordTypeName,
				fallback: "Record<string, any>",
			};
		}
	}
	return map;
}

/**
 * Replace $PLACEHOLDER tokens in a configType string with resolved type aliases.
 */
function resolvePlaceholders(
	configType: string,
	hasModules: boolean,
	placeholderMap: Record<string, { withModules: string; fallback: string }>,
): string {
	let result = configType;
	for (const [placeholder, aliases] of Object.entries(placeholderMap)) {
		if (result.includes(placeholder)) {
			result = result.replaceAll(
				placeholder,
				hasModules ? aliases.withModules : aliases.fallback,
			);
		}
	}
	return result;
}

// ============================================================================
// Extension registry emission
// ============================================================================

/**
 * Emit an extension registry object that maps method names to their
 * stateKey and resolve logic (callback context creation).
 */
function emitExtensionRegistry(
	lines: string[],
	varName: string,
	extensions: Map<string, RegistryExtension>,
	callbackParams: Map<string, CallbackParamDefinition>,
): void {
	lines.push(
		`const ${varName}: Record<string, { stateKey: string; resolve: (v: any) => any }> = {`,
	);
	for (const [name, ext] of extensions) {
		const hasDefaults = ext.defaults && Object.keys(ext.defaults).length > 0;
		const defaultsJson = hasDefaults ? JSON.stringify(ext.defaults) : null;

		if (ext.isCallback) {
			lines.push(`\t${name}: {`);
			lines.push(`\t\tstateKey: "${ext.stateKey}",`);
			lines.push("\t\tresolve(configOrFn: any) {");
			if (hasDefaults) {
				lines.push(
					`\t\t\tconst resolved = typeof configOrFn === 'function' ? configOrFn(${emitCallbackContext(ext, callbackParams)}) : configOrFn;`,
				);
				lines.push(`\t\t\treturn { ...${defaultsJson}, ...resolved };`);
			} else {
				lines.push(
					`\t\t\tif (typeof configOrFn === 'function') return configOrFn(${emitCallbackContext(ext, callbackParams)});`,
				);
				lines.push("\t\t\treturn configOrFn;");
			}
			lines.push("\t\t},");
			lines.push("\t},");
		} else {
			if (hasDefaults) {
				lines.push(
					`\t${name}: { stateKey: "${ext.stateKey}", resolve: (v: any) => ({ ...${defaultsJson}, ...v }) },`,
				);
			} else {
				lines.push(
					`\t${name}: { stateKey: "${ext.stateKey}", resolve: (v: any) => v },`,
				);
			}
		}
	}
	lines.push("};");
}

// ============================================================================
// Helpers
// ============================================================================

function collectImports(
	ext: RegistryExtension,
	allImports: Map<string, Set<string>>,
): void {
	if (!ext.imports) return;
	for (const imp of ext.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

function collectSingletonImports(
	factory: SingletonFactory,
	allImports: Map<string, Set<string>>,
): void {
	for (const imp of factory.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

/**
 * Emit the callback context object for a callback-style extension.
 */
function emitCallbackContext(
	ext: RegistryExtension,
	callbackParams: Map<string, CallbackParamDefinition>,
): string {
	if (!ext.callbackContextParams || ext.callbackContextParams.length === 0) {
		return "{}";
	}

	const params: string[] = [];
	for (const param of ext.callbackContextParams) {
		const def = callbackParams.get(param);
		if (def) {
			params.push(`${param}: ${def.factory}()`);
		} else {
			params.push(`${param}: {}`);
		}
	}

	return `{ ${params.join(", ")} }`;
}

/**
 * Collect imports required by callback param factory functions.
 */
function collectCallbackParamImports(
	callbackParams: Map<string, CallbackParamDefinition>,
	allImports: Map<string, Set<string>>,
): void {
	for (const def of callbackParams.values()) {
		let names = allImports.get(def.from);
		if (!names) {
			names = new Set();
			allImports.set(def.from, names);
		}
		names.add(def.factory);
	}
}
