/**
 * Factory Template Generation
 *
 * Generates `.generated/factories.ts` — typed `collection()` and `global()`
 * factory functions with plugin extensions, singleton factory functions
 * (branding, sidebar, locale, etc.), and module-driven type extraction
 * for autocomplete on proxies (views, components, field types).
 *
 * Extension methods are intercepted by a Proxy wrapper that delegates to
 * `builder.set()`. Core builder methods are passed through and their results
 * are re-wrapped to preserve the Proxy chain across immutable builder calls.
 *
 * @see RFC-CONTEXT-FIRST §6 (Extension System Without Monkey-Patching)
 */

import type {
	CallbackParamDefinition,
	CategoryDeclaration,
	RegistryExtension,
	ResolvedTarget,
	SingletonFactory,
} from "./types.js";

// ============================================================================
// Factory generation
// ============================================================================

export interface FactoryTemplateOptions {
	/** The resolved target with merged registries and callback params. */
	target: ResolvedTarget;
	/** Whether modules.ts exists (new architecture). */
	hasModules: boolean;
}

/**
 * Generate `.generated/factories.ts` content.
 * Returns null if the target declares no registries (no factories needed).
 */
export function generateFactoryTemplate(
	options: FactoryTemplateOptions,
): string | null {
	const { target, hasModules } = options;

	// Extract merged registries and callback params from the resolved target
	const collExtensions = new Map<string, RegistryExtension>();
	const globalExtensions = new Map<string, RegistryExtension>();
	const singletonFactories = new Map<string, SingletonFactory>();
	const allImports = new Map<string, Set<string>>(); // from → Set<name>

	for (const [name, ext] of Object.entries(
		target.registries.collectionExtensions,
	)) {
		collExtensions.set(name, ext);
		collectImports(ext, allImports);
	}

	for (const [name, ext] of Object.entries(
		target.registries.globalExtensions,
	)) {
		globalExtensions.set(name, ext);
		collectImports(ext, allImports);
	}

	for (const [name, factory] of Object.entries(
		target.registries.singletonFactories,
	)) {
		singletonFactories.set(name, factory);
		collectSingletonImports(factory, allImports);
	}

	// Categories with placeholder/recordPlaceholder/typeRegistry (drive type extraction)
	const registryCategories = new Map<string, CategoryDeclaration>();
	for (const [key, decl] of Object.entries(target.categories)) {
		if (decl.placeholder || decl.recordPlaceholder || decl.typeRegistry) {
			registryCategories.set(key, decl);
		}
	}

	// Callback params from the resolved target
	const callbackParams = new Map<string, CallbackParamDefinition>();
	for (const [key, def] of Object.entries(target.callbackParams)) {
		callbackParams.set(key, def);
	}

	// If nothing declared, no factories file needed
	if (
		collExtensions.size === 0 &&
		globalExtensions.size === 0 &&
		singletonFactories.size === 0
	) {
		return null;
	}

	// Collect all configTypePlaceholders → category mappings
	const placeholderCategories = new Map<string, string>();
	for (const ext of [
		...collExtensions.values(),
		...globalExtensions.values(),
	]) {
		if (ext.configTypePlaceholders) {
			for (const [placeholder, category] of Object.entries(
				ext.configTypePlaceholders,
			)) {
				placeholderCategories.set(placeholder, category);
			}
		}
	}

	const lines: string[] = [];

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push(
		"// Typed factory functions with plugin extensions. Regenerate with: questpie generate",
	);
	lines.push("");

	// Core imports
	lines.push("// ── Core Imports ───────────────────────────────────────────");
	lines.push(
		'import { CollectionBuilder, GlobalBuilder, type EmptyCollectionState, type EmptyGlobalState, type Registry } from "questpie";',
	);
	lines.push("");

	// Module import (for runtime field merging only — types come from Registry)
	if (hasModules) {
		lines.push("// ── Module import (for runtime fields) ──");
		lines.push('import _modulesArr from "../modules";');
		lines.push("");
	}

	// Plugin imports (only types needed for signatures)
	if (allImports.size > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const [from, names] of allImports) {
			const nameList = [...names]
				.filter((n) => /^[A-Z]/.test(n)) // only types (PascalCase)
				.map((n) => `type ${n}`)
				.join(", ");
			const valueList = [...names]
				.filter((n) => /^[a-z]/.test(n)) // runtime values (camelCase)
				.join(", ");
			const parts = [nameList, valueList].filter(Boolean).join(", ");
			if (parts) {
				lines.push(`import { ${parts} } from "${from}";`);
			}
		}
		lines.push("");
	}

	// ── Type extraction from Registry (breaks circular reference) ──
	// Instead of deriving types from `typeof _modulesArr` (which causes circular
	// refs with CollectionBuilder augmentation), we read from the Registry
	// interface which is augmented by each module's .generated/module.ts.
	if (hasModules) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push(
			"// Type extraction from Registry — driven by CategoryDeclaration",
		);
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		// Registry-based property extraction (no dependency on typeof _modulesArr)
		lines.push(
			"type _RegistryProp<K extends string> = Registry extends Record<K, infer V> ? V : Record<string, unknown>;",
		);
		lines.push("");

		// Generate type aliases for each category that has placeholder/recordPlaceholder
		for (const [key, decl] of registryCategories) {
			const registryKey = typeof decl.registryKey === "string" ? decl.registryKey : key;
			if (decl.placeholder) {
				const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
				lines.push(
					`type ${typeName} = (keyof _RegistryProp<"${registryKey}"> & string) | (string & {});`,
				);
				if (decl.typeRegistry) {
					lines.push(
						`type ${typeName}_Strict = keyof _RegistryProp<"${registryKey}"> & string;`,
					);
				}
			}
			if (decl.recordPlaceholder) {
				const recordTypeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Record`;
				lines.push(
					`type ${recordTypeName} = _RegistryProp<"${registryKey}">;`,
				);
			}
		}
		lines.push("");

		// Field types — extracted directly from modules (avoids circular dependency with index.ts Registry augmentation)
		lines.push("// Field types — extracted from modules");
		lines.push(
			"type _ExtractProp<M, K extends string> = (M extends { modules: infer Sub extends readonly any[] } ? _ExtractPropArr<Sub, K> : {}) & (K extends keyof M ? M[K] extends Record<string, any> ? M[K] : {} : {});",
		);
		lines.push(
			"type _ExtractPropArr<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _ExtractProp<H, K> & _ExtractPropArr<T, K> : {};",
		);
		lines.push(
			'type _AllFieldTypes = _ExtractProp<{ modules: typeof _modulesArr }, "fields">;',
		);
		lines.push("");
	} else {
		// No modules — use string fallback for all registry categories
		lines.push("// No modules.ts — using string fallback for type extraction");
		for (const [key, decl] of registryCategories) {
			if (decl.placeholder) {
				const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
				lines.push(`type ${typeName} = string;`);
				if (decl.typeRegistry) {
					lines.push(`type ${typeName}_Strict = never;`);
				}
			}
			if (decl.recordPlaceholder) {
				const recordTypeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Record`;
				lines.push(`type ${recordTypeName} = Record<string, any>;`);
			}
		}
		lines.push("type _AllFieldTypes = Record<string, never>;");
		lines.push("");
	}

	// ── Runtime field merging ────────────────────────────────
	if (hasModules) {
		lines.push(
			"// ── Runtime: extract fields from modules ────────────────────",
		);
		lines.push(
			"function _extractModuleFields(modules: readonly any[]): Record<string, any> {",
		);
		lines.push("\tconst merged: Record<string, any> = {};");
		lines.push("\tfor (const m of modules) {");
		lines.push("\t\tif (m.fields) Object.assign(merged, m.fields);");
		lines.push(
			"\t\tif (m.modules) Object.assign(merged, _extractModuleFields(m.modules));",
		);
		lines.push("\t}");
		lines.push("\treturn merged;");
		lines.push("}");
		lines.push("const _allRuntimeFields = _extractModuleFields(_modulesArr);");
		lines.push("");
	}

	// ── Type augmentations (declare module) ────────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Type augmentations — generated from plugin registries");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	const placeholderMap = buildPlaceholderMap(registryCategories);

	// Builder interface augmentations — keep declare module "questpie" for class merging
	// (CollectionBuilder/GlobalBuilder are classes that need interface merging)
	if (collExtensions.size > 0 || globalExtensions.size > 0) {
		lines.push('declare module "questpie" {');

		if (collExtensions.size > 0) {
			lines.push("\tinterface CollectionBuilder<TState> {");
			for (const [name, ext] of collExtensions) {
				const paramName = ext.isCallback ? "configFn" : "config";
				let paramType = ext.configType ?? "any";
				paramType = resolvePlaceholders(paramType, hasModules, placeholderMap);
				lines.push(
					`\t\t${name}(${paramName}: ${paramType}): CollectionBuilder<TState>;`,
				);
			}
			lines.push("\t}");
		}

		if (globalExtensions.size > 0) {
			lines.push("\tinterface GlobalBuilder<TState> {");
			for (const [name, ext] of globalExtensions) {
				const paramName = ext.isCallback ? "configFn" : "config";
				let paramType = ext.configType ?? "any";
				paramType = resolvePlaceholders(paramType, hasModules, placeholderMap);
				lines.push(
					`\t\t${name}(${paramName}: ${paramType}): GlobalBuilder<TState>;`,
				);
			}
			lines.push("\t}");
		}

		lines.push("}");
		lines.push("");
	}

	// FieldTypeRegistry and type registries — use declare global (symlink-safe)
	lines.push("declare global {");
	lines.push("\tnamespace Questpie {");

	lines.push(
		"\t\tinterface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}",
	);

	// Type registries from categories that target "questpie" module
	for (const [key, decl] of registryCategories) {
		if (decl.typeRegistry?.module === "questpie") {
			const strictName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names_Strict`;
			lines.push(
				`\t\tinterface ${decl.typeRegistry.interface} extends Record<${strictName}, {}> {}`,
			);
		}
	}

	lines.push("\t}");
	lines.push("}");
	lines.push("");

	// Type registries from categories that target other modules (e.g., "@questpie/admin/server")
	// Group by module to minimize declare module blocks
	const externalTypeRegistries = new Map<
		string,
		Array<{ key: string; decl: CategoryDeclaration }>
	>();
	for (const [key, decl] of registryCategories) {
		if (decl.typeRegistry && decl.typeRegistry.module !== "questpie") {
			let entries = externalTypeRegistries.get(decl.typeRegistry.module);
			if (!entries) {
				entries = [];
				externalTypeRegistries.set(decl.typeRegistry.module, entries);
			}
			entries.push({ key, decl });
		}
	}

	for (const [moduleName, entries] of externalTypeRegistries) {
		lines.push(`declare module "${moduleName}" {`);
		for (const { key, decl } of entries) {
			const strictName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names_Strict`;
			lines.push(
				`\tinterface ${decl.typeRegistry?.interface} extends Record<${strictName}, {}> {}`,
			);
		}
		lines.push("}");
		lines.push("");
	}

	// ── Extension registries + Proxy wrappers ─────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Extension registries + Proxy wrappers");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	if (collExtensions.size > 0) {
		emitExtensionRegistry(lines, "_collExt", collExtensions, callbackParams);
		lines.push("");
		emitProxyWrapper(lines, "_wrapColl", "_collExt", "CollectionBuilder");
		lines.push("");
	}

	if (globalExtensions.size > 0) {
		emitExtensionRegistry(lines, "_globExt", globalExtensions, callbackParams);
		lines.push("");
		emitProxyWrapper(lines, "_wrapGlob", "_globExt", "GlobalBuilder");
		lines.push("");
	}

	// ── Factory functions ─────────────────────────────────────
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// Factory functions");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// collection()
	if (collExtensions.size > 0) {
		lines.push("/**");
		lines.push(" * Create a typed collection builder with plugin extensions.");
		lines.push(" *");
		lines.push(" * @example");
		lines.push(" * ```ts");
		lines.push(' * import { collection } from "#questpie/factories";');
		lines.push(" *");
		lines.push(' * export default collection("posts")');
		lines.push(
			" *   .fields(({ f }) => ({ title: f.text({ required: true }) }))",
		);
		lines.push(' *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))');
		lines.push(" *   .list(({ v, f }) => v.table({ columns: [f.title] }))");
		lines.push(" * ```");
		lines.push(" */");
		lines.push(
			"export function collection<TName extends string>(name: TName): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {",
		);
		lines.push("\treturn _wrapColl(new CollectionBuilder({");
		lines.push("\t\tname: name as string,");
		lines.push("\t\tfields: {},");
		lines.push("\t\tlocalized: [],");
		lines.push("\t\tvirtuals: undefined,");
		lines.push("\t\trelations: {},");
		lines.push("\t\tindexes: {},");
		lines.push("\t\ttitle: undefined,");
		lines.push("\t\toptions: {},");
		lines.push("\t\thooks: {},");
		lines.push("\t\taccess: {},");
		lines.push("\t\tsearchable: undefined,");
		lines.push("\t\tvalidation: undefined,");
		lines.push("\t\toutput: undefined,");
		lines.push("\t\tupload: undefined,");
		lines.push("\t\tfieldDefinitions: {},");
		if (hasModules) {
			lines.push(
				'\t\t"~questpieApp": { state: { fields: _allRuntimeFields } },',
			);
		} else {
			lines.push('\t\t"~questpieApp": undefined,');
		}
		lines.push("\t})) as any;");
		lines.push("}");
		lines.push("");
	}

	// global()
	if (globalExtensions.size > 0) {
		lines.push("/**");
		lines.push(" * Create a typed global builder with plugin extensions.");
		lines.push(" */");
		lines.push(
			"export function global<TName extends string>(name: TName): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {",
		);
		lines.push("\treturn _wrapGlob(new GlobalBuilder({");
		lines.push("\t\tname: name as string,");
		lines.push("\t\tfields: {},");
		lines.push("\t\tlocalized: [],");
		lines.push("\t\tvirtuals: {},");
		lines.push("\t\trelations: {},");
		lines.push("\t\toptions: {},");
		lines.push("\t\thooks: {},");
		lines.push("\t\taccess: {},");
		lines.push("\t\tfieldDefinitions: {},");
		if (hasModules) {
			lines.push(
				'\t\t"~questpieApp": { state: { fields: _allRuntimeFields } },',
			);
		} else {
			lines.push('\t\t"~questpieApp": undefined,');
		}
		lines.push("\t})) as any;");
		lines.push("}");
		lines.push("");
	}

	// ── Singleton factory functions ────────────────────────────
	if (singletonFactories.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("// Singleton factory functions");
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		for (const [name, factory] of singletonFactories) {
			emitSingletonFactory(lines, name, factory);
			lines.push("");
		}
	}

	return lines.join("\n");
}

// ============================================================================
// Singleton factory emission
// ============================================================================

/**
 * Emit a singleton factory function.
 * Non-callback: simple generic identity with type constraint.
 * Callback: overloaded identity accepting both plain config and callback.
 */
function emitSingletonFactory(
	lines: string[],
	name: string,
	factory: SingletonFactory,
): void {
	const { configType, isCallback } = factory;

	if (isCallback) {
		// Overloaded — accepts plain config or callback function
		lines.push(
			`/** Typed factory for ${name} config. Accepts plain config or callback. */`,
		);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T;`,
		);
		lines.push(
			`export function ${name}<T extends (...args: any[]) => ${configType}>(cb: T): T;`,
		);
		lines.push(`export function ${name}(v: any): any { return v; }`);
	} else {
		// Simple identity with type constraint
		lines.push(`/** Typed factory for ${name} config. */`);
		lines.push(
			`export function ${name}<T extends ${configType}>(config: T): T { return config; }`,
		);
	}
}

// ============================================================================
// Placeholder resolution
// ============================================================================

/**
 * Build a placeholder → type alias mapping from categories with placeholder/recordPlaceholder.
 * Each category with a `placeholder` gets an entry that maps
 * the placeholder token to the generated type alias name.
 */
function buildPlaceholderMap(
	categories: Map<string, CategoryDeclaration>,
): Record<string, { withModules: string; fallback: string }> {
	const map: Record<string, { withModules: string; fallback: string }> = {};
	for (const [key, decl] of categories) {
		if (decl.placeholder) {
			const typeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Names`;
			map[decl.placeholder] = { withModules: typeName, fallback: "string" };
		}
		if (decl.recordPlaceholder) {
			const recordTypeName = `_${key.charAt(0).toUpperCase() + key.slice(1)}Record`;
			map[decl.recordPlaceholder] = {
				withModules: recordTypeName,
				fallback: "Record<string, any>",
			};
		}
	}
	return map;
}

/**
 * Replace $PLACEHOLDER tokens in a configType string with resolved type aliases.
 */
function resolvePlaceholders(
	configType: string,
	hasModules: boolean,
	placeholderMap: Record<string, { withModules: string; fallback: string }>,
): string {
	let result = configType;
	for (const [placeholder, aliases] of Object.entries(placeholderMap)) {
		if (result.includes(placeholder)) {
			result = result.replaceAll(
				placeholder,
				hasModules ? aliases.withModules : aliases.fallback,
			);
		}
	}
	return result;
}

// ============================================================================
// Extension registry + Proxy wrapper emission
// ============================================================================

/**
 * Emit an extension registry object that maps method names to their
 * stateKey and resolve logic (callback context creation).
 */
function emitExtensionRegistry(
	lines: string[],
	varName: string,
	extensions: Map<string, RegistryExtension>,
	callbackParams: Map<string, CallbackParamDefinition>,
): void {
	lines.push(
		`const ${varName}: Record<string, { stateKey: string; resolve: (v: any) => any }> = {`,
	);
	for (const [name, ext] of extensions) {
		const hasDefaults = ext.defaults && Object.keys(ext.defaults).length > 0;
		const defaultsJson = hasDefaults ? JSON.stringify(ext.defaults) : null;

		if (ext.isCallback) {
			lines.push(`\t${name}: {`);
			lines.push(`\t\tstateKey: "${ext.stateKey}",`);
			lines.push("\t\tresolve(configOrFn: any) {");
			if (hasDefaults) {
				lines.push(
					`\t\t\tconst resolved = typeof configOrFn === 'function' ? configOrFn(${emitCallbackContext(ext, callbackParams)}) : configOrFn;`,
				);
				lines.push(
					`\t\t\treturn { ...${defaultsJson}, ...resolved };`,
				);
			} else {
				lines.push(
					`\t\t\tif (typeof configOrFn === 'function') return configOrFn(${emitCallbackContext(ext, callbackParams)});`,
				);
				lines.push("\t\t\treturn configOrFn;");
			}
			lines.push("\t\t},");
			lines.push("\t},");
		} else {
			if (hasDefaults) {
				lines.push(
					`\t${name}: { stateKey: "${ext.stateKey}", resolve: (v: any) => ({ ...${defaultsJson}, ...v }) },`,
				);
			} else {
				lines.push(
					`\t${name}: { stateKey: "${ext.stateKey}", resolve: (v: any) => v },`,
				);
			}
		}
	}
	lines.push("};");
}

/**
 * Emit a Proxy wrapper function that intercepts extension method calls
 * and delegates to `builder.set()`. Also re-wraps builder-returning
 * methods so the Proxy chain is preserved across immutable builder calls.
 */
function emitProxyWrapper(
	lines: string[],
	fnName: string,
	registryVar: string,
	builderClass: string,
): void {
	lines.push(`function ${fnName}(builder: any): any {`);
	lines.push("\treturn new Proxy(builder, {");
	lines.push("\t\tget(target, prop, receiver) {");
	lines.push(`\t\t\tif (typeof prop === 'string' && prop in ${registryVar}) {`);
	lines.push(`\t\t\t\tconst ext = ${registryVar}[prop];`);
	lines.push(
		`\t\t\t\treturn (configOrFn: any) => ${fnName}(target.set(ext.stateKey, ext.resolve(configOrFn)));`,
	);
	lines.push("\t\t\t}");
	lines.push("\t\t\tconst val = Reflect.get(target, prop, receiver);");
	lines.push("\t\t\tif (typeof val === 'function') {");
	lines.push("\t\t\t\treturn function(this: any, ...args: any[]) {");
	lines.push("\t\t\t\t\tconst result = val.apply(target, args);");
	lines.push(
		`\t\t\t\t\treturn result instanceof ${builderClass} ? ${fnName}(result) : result;`,
	);
	lines.push("\t\t\t\t};");
	lines.push("\t\t\t}");
	lines.push("\t\t\treturn val;");
	lines.push("\t\t},");
	lines.push("\t});");
	lines.push("}");
}

// ============================================================================
// Helpers
// ============================================================================

function collectImports(
	ext: RegistryExtension,
	allImports: Map<string, Set<string>>,
): void {
	if (!ext.imports) return;
	for (const imp of ext.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

function collectSingletonImports(
	factory: SingletonFactory,
	allImports: Map<string, Set<string>>,
): void {
	for (const imp of factory.imports) {
		let names = allImports.get(imp.from);
		if (!names) {
			names = new Set();
			allImports.set(imp.from, names);
		}
		names.add(imp.name);
	}
}

/**
 * Emit the callback context object for a callback-style extension.
 * Looks up each param name in the plugin-contributed callbackParams registry
 * and emits the registered proxyCode inline.
 */
function emitCallbackContext(
	ext: RegistryExtension,
	callbackParams: Map<string, CallbackParamDefinition>,
): string {
	if (!ext.callbackContextParams || ext.callbackContextParams.length === 0) {
		return "{}";
	}

	const params: string[] = [];
	for (const param of ext.callbackContextParams) {
		const def = callbackParams.get(param);
		if (def) {
			params.push(`${param}: ${def.proxyCode}`);
		} else {
			// Fallback for unknown params — empty object
			params.push(`${param}: {}`);
		}
	}

	return `{ ${params.join(", ")} }`;
}
