/**
 * Module Template Generation
 *
 * Generates the `.generated/module.ts` file content for npm package modules.
 * The generated file:
 * 1. Imports all discovered entities (collections, routes, jobs, etc.)
 * 2. Imports sub-modules from `modules.ts` (if present)
 * 3. Emits type interfaces using typeof references (zero inference cost)
 * 4. Exports a plain static module definition object
 *
 * Unlike the root app template (template.ts), this does NOT:
 * - Import a runtime config
 * - Call createApp()
 * - Generate an App type
 *
 * All category-specific behavior is driven by `CategoryDeclaration` metadata
 * from plugins — no hardcoded category names.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */

import type {
	CategoryDeclaration,
	DiscoveredFile,
	DiscoverPattern,
	DiscoveryResult,
} from "./types.js";

// ============================================================================
// Module template options
// ============================================================================

export interface ModuleTemplateOptions {
	/** Module name (e.g. "questpie-admin", "questpie-audit"). */
	moduleName: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/**
	 * Merged category declarations from all plugins.
	 * Key = category name, value = declaration metadata.
	 * Used to determine emit strategy, type emission, etc.
	 */
	categoryMeta: Map<string, CategoryDeclaration>;
	/** Additional imports from plugins (e.g. admin view/component factories). */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/**
	 * Additional runtime code to add to the module object.
	 * Each entry is a line like `listViews: { table: listView("table") },`.
	 */
	extraModuleProperties?: string[];
	/** @deprecated No longer used — Registry augmentation moved to root template. */
	discoverPatterns?: Record<string, DiscoverPattern>;
}

/**
 * Result of module template generation.
 * May include an additional registries file for factory registry augmentations.
 */
export interface ModuleTemplateResult {
	/** Main module.ts code. */
	code: string;
	/**
	 * Optional registries.ts code for factory registry augmentations.
	 * Generated in a separate file to avoid circular references:
	 * module.ts contains CollectionBuilder instances whose augmented interface
	 * references Questpie.ViewsRegistry etc. — augmenting those in the same
	 * file creates a within-file circular dependency.
	 */
	registriesCode: string | null;
}

// ============================================================================
// Module template generation
// ============================================================================

/**
 * Generate the .generated/module.ts file content for a package module.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.2 (Module — .generated/module.ts)
 */
export function generateModuleTemplate(
	options: ModuleTemplateOptions,
): ModuleTemplateResult {
	const lines: string[] = [];
	const {
		moduleName,
		discovered,
		categoryMeta,
		extraImports,
		extraTypeDeclarations,
		extraModuleProperties,
	} = options;

	const modulesFile = discovered.singles.get("modules") ?? null;

	// Derive a PascalCase type prefix from the module name
	// "questpie-admin" → "Admin", "questpie-audit" → "Audit"
	const typePrefix = deriveTypePrefix(moduleName);

	// Header
	lines.push("/* oxlint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate --module");
	lines.push("");

	// Import sub-modules
	if (modulesFile) {
		lines.push(
			"// ── Sub-Modules ────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// Import all categories (collections, globals, jobs, routes, etc.)
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const label = catName.charAt(0).toUpperCase() + catName.slice(1);
		lines.push(`// ── ${label} ────────────────────────────────────────────`);
		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import singles (auth, locale, hooks, access, context, fields, sidebar, etc.)
	const singles = getNonModuleSingles(discovered.singles);
	if (singles.length > 0) {
		lines.push(
			"// ── Singles ────────────────────────────────────────────────",
		);
		for (const file of singles) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — module type extraction
	// ════════════════════════════════════════════════════════════

	// Determine which categories need named type interfaces.
	// Use typeEmit from CategoryDeclaration — skip "none" and "messages".
	const categoriesNeedingTypes = new Set<string>();
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		const decl = categoryMeta.get(catName);
		const typeEmit = decl?.typeEmit ?? "standard";
		// Skip categories that don't produce meaningful named types for modules
		if (typeEmit === "none" || typeEmit === "messages") continue;
		categoriesNeedingTypes.add(catName);
	}

	if (categoriesNeedingTypes.size > 0) {
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push(
			"// TYPES — composed from typeof references (zero inference cost)",
		);
		lines.push(
			"// ════════════════════════════════════════════════════════════",
		);
		lines.push("");

		if (categoriesNeedingTypes.has("routes")) {
			lines.push(
				'import type { RouteParamsFromKey, RouteWithParams } from "questpie";',
			);
			lines.push("");
		}

		// Always emit simple interfaces (no sub-module extends).
		//
		// Why not `extends _SubCollections`:
		//   Modules declare their OWN collections. When a module overrides a
		//   sub-module's collection (e.g. admin overrides starter's `account` with
		//   .merge().set("admin",...)), the override type is NOT a subtype of the
		//   original — TypeScript's `extends` constraint breaks.
		//
		//   Sub-module collection composition is handled upstream in the root app's
		//   index.ts via `ExtractFromModuleArray` and intersection types. Each module
		//   only needs to declare what IT directly provides.
		//
		// Why emit at all (not just infer from `_module`):
		//   Deep .merge().set() builder chains cause TS7056 ("inferred type exceeds
		//   maximum length"). Named interfaces give TypeScript a stable anchor.
		for (const catName of categoriesNeedingTypes) {
			const fileMap = discovered.categories.get(catName)!;
			const decl = categoryMeta.get(catName);
			const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;

			if (catName === "routes") {
				emitSimpleRouteTypeInterface(lines, typeName, fileMap);
			} else {
				emitSimpleTypeInterface(lines, typeName, fileMap, decl);
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// MODULE DEFINITION — static plain object
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// MODULE DEFINITION — static plain object");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	// Pre-scan extraModuleProperties to identify registry-matching properties.
	// These need separate const declarations BEFORE _module to avoid circular
	// typeof _module references in Registry augmentation:
	//   typeof _module → collections → CollectionBuilder augmentation → Registry
	//   → typeof _module["listViews"] → cycle!
	// By extracting to a separate const, Registry can use typeof _reg_listViews.
	const extractedConsts = new Map<
		string,
		{ constName: string; expression: string }
	>();
	const extraPropNames = new Set<string>();
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		// Build the set of category names that have registryKey — these need extraction
		const registryPropNames = new Set<string>();
		for (const [catName, decl] of categoryMeta) {
			if (decl.registryKey) registryPropNames.add(catName);
		}
		for (const prop of extraModuleProperties) {
			const match = prop.match(/^(\w+)\s*:\s*(.+?),?\s*$/);
			if (match) {
				const [, propName, expression] = match;
				extraPropNames.add(propName);
				if (registryPropNames.has(propName)) {
					const constName = `_reg_${propName}`;
					extractedConsts.set(propName, { constName, expression });
				}
			}
		}
	}

	// Emit extracted consts before _module to break typeof circular references
	if (extractedConsts.size > 0) {
		for (const [, { constName, expression }] of extractedConsts) {
			lines.push(`const ${constName} = ${expression};`);
		}
		lines.push("");
	}

	lines.push("const _module = {");
	lines.push(`\tname: "${moduleName}" as const,`);

	// Sub-modules
	if (modulesFile) {
		lines.push(`\tmodules: ${modulesFile.varName},`);
	}

	// Emit all categories — driven by CategoryDeclaration.emit
	// Track which categories were emitted with files
	const emittedCategories = new Set<string>();

	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;
		emittedCategories.add(catName);
		const decl = categoryMeta.get(catName);
		const emitStrategy = decl?.emit ?? "record";
		const typeEmit = decl?.typeEmit ?? "standard";
		const typeName = `${typePrefix}${catName.charAt(0).toUpperCase() + catName.slice(1)}`;
		const hasNamedType = categoriesNeedingTypes.has(catName);

		if (emitStrategy === "array") {
			// Array emission (migrations, seeds)
			const vars = sortedValues(fileMap)
				.map((f) => f.varName)
				.join(", ");
			lines.push(`\t${safeKey(catName)}: [${vars}],`);
		} else {
			// Record emission (collections, globals, jobs, messages, etc.)
			lines.push(`\t${safeKey(catName)}: {`);
			for (const file of sortedValues(fileMap)) {
				if (file.isBundle) {
					// Bundle files are spread into the parent object
					lines.push(`\t\t...${file.varName},`);
				} else if (decl?.keyFromProperty) {
					lines.push(
						`\t\t[${file.varName}.${decl.keyFromProperty}]: ${file.varName},`,
					);
				} else {
					lines.push(`\t\t${safeKey(file.key)}: ${file.varName},`);
				}
			}
			if (hasNamedType && typeEmit !== "messages") {
				lines.push(`\t} as ${typeName},`);
			} else {
				lines.push("\t},");
			}
		}
	}

	// Emit empty stubs for declared categories with no discovered files.
	// This ensures the module type always includes all target categories,
	// so consumers can spread `module.blocks` without type assertions.
	for (const [catName, decl] of categoryMeta) {
		if (emittedCategories.has(catName)) continue;
		if (extraPropNames.has(catName)) continue; // provided by extraModuleProperties
		const emitStrategy = decl.emit ?? "record";
		if (emitStrategy === "array") {
			lines.push(`\t${safeKey(catName)}: [] as const,`);
		} else {
			lines.push(`\t${safeKey(catName)}: {},`);
		}
	}

	// Separate config-bucket singles from plain singles
	const configSingles = singles.filter((f) => f.configKey);
	const plainSingles = singles.filter((f) => !f.configKey);

	// Config bucket — each config file = one key
	if (configSingles.length > 0) {
		lines.push("\tconfig: {");
		for (const file of configSingles) {
			lines.push(`\t\t${safeKey(file.configKey!)}: ${file.varName},`);
		}
		lines.push("\t},");
	}

	// Plain singles (fields, etc.)
	for (const file of plainSingles) {
		lines.push(`\t${safeKey(file.key)}: ${file.varName},`);
	}

	// Extra module properties from plugins
	if (extraModuleProperties && extraModuleProperties.length > 0) {
		for (const prop of extraModuleProperties) {
			const match = prop.match(/^(\w+)\s*:\s*(.+?),?\s*$/);
			if (match) {
				const [, propName] = match;
				const extracted = extractedConsts.get(propName);
				if (extracted) {
					// Reference the extracted const instead of inline expression
					lines.push(`\t${propName}: ${extracted.constName},`);
				} else {
					lines.push(`\t${prop}`);
				}
			} else {
				lines.push(`\t${prop}`);
			}
		}
	}

	lines.push("};");
	lines.push("");

	// Export type and default
	lines.push(`export type ${typePrefix}Module = typeof _module;`);
	lines.push("export default _module;");
	lines.push("");

	// ── Factory registry augmentations → separate file ───────────────
	// Augmentations for Questpie.ViewsRegistry, Questpie.ComponentsRegistry, and
	// Questpie.FieldTypesMap are emitted in a SEPARATE registries.ts file to avoid
	// circular references. The cycle is:
	//
	//   module.ts defines _module → contains CollectionBuilder instances
	//   → CollectionBuilder augmented interface references Questpie.ViewsRegistry
	//   → ViewsRegistry augmented IN THIS FILE → needs typeof _module to be resolved
	//   → BUT _module IS being resolved → CYCLE
	//
	// By moving augmentations to registries.ts (which imports type-only references
	// from module.ts), the cycle is broken. module.ts uses a side-effect import
	// of registries.ts to ensure the augmentations are always loaded.
	let registriesCode: string | null = null;
	{
		const augmentations: string[] = [];

		// Categories with recordPlaceholder (views, components)
		for (const [catName, decl] of categoryMeta) {
			if (!decl.recordPlaceholder) continue;
			const fileMap = discovered.categories.get(catName);
			if (!fileMap || fileMap.size === 0) continue;

			const cap = catName.charAt(0).toUpperCase() + catName.slice(1);
			const interfaceName = `${cap}Registry`;
			// Use the local type name from registries.ts (NOT from module.ts to avoid circular imports)
			const regLocalTypeName = `_Reg${cap}`;

			// Check if we emitted a named type interface for this category
			if (categoriesNeedingTypes.has(catName)) {
				augmentations.push(
					`\t\tinterface ${interfaceName} extends ${regLocalTypeName} {}`,
				);
			}
		}

		// ~fieldTypes singleton (fields.ts) → FieldTypesMap
		const fieldsSingle = singles.find((f) => f.key === "fields");
		if (fieldsSingle) {
			augmentations.push(`\t\tinterface FieldTypesMap extends _FieldTypes {}`);
		}

		if (augmentations.length > 0) {
			// Generate registries.ts content
			const regLines: string[] = [];
			regLines.push("/* oxlint-disable */");
			regLines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
			regLines.push(
				"// Factory registry augmentations for module. Separate file to avoid circular refs.",
			);
			regLines.push(
				"// IMPORTANT: This file must NOT import from module.ts to avoid circular imports.",
			);
			regLines.push("");

			// Instead of importing named types from module.ts (which creates circular
			// imports: module.ts → registries.ts → module.ts), we rebuild the needed
			// type interfaces here from the original source files.
			for (const [catName, decl] of categoryMeta) {
				if (!decl.recordPlaceholder) continue;
				const fileMap = discovered.categories.get(catName);
				if (!fileMap || fileMap.size === 0) continue;
				if (!categoriesNeedingTypes.has(catName)) continue;

				const cap = catName.charAt(0).toUpperCase() + catName.slice(1);
				const typeName = `_Reg${cap}`;

				// Import individual source files
				for (const file of sortedValues(fileMap)) {
					regLines.push(
						`import type ${file.varName} from "${file.importPath}";`,
					);
				}
				regLines.push("");

				// Emit a local type interface
				const leafFiles = sortedValues(fileMap).filter((f) => !f.isBundle);
				const bundleFiles = sortedValues(fileMap).filter((f) => f.isBundle);

				if (bundleFiles.length === 0) {
					regLines.push(`interface ${typeName} {`);
					for (const file of leafFiles) {
						regLines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
					}
					regLines.push("}");
				} else {
					const parts: string[] = [];
					if (leafFiles.length > 0) {
						parts.push(
							`{ ${leafFiles.map((f) => `${safeKey(f.key)}: typeof ${f.varName}`).join("; ")} }`,
						);
					}
					for (const bundle of bundleFiles) {
						parts.push(`typeof ${bundle.varName}`);
					}
					regLines.push(`type ${typeName} = ${parts.join(" & ")};`);
				}
				regLines.push("");
			}

			// Import fields singleton for typeof
			if (fieldsSingle) {
				regLines.push(`import type _fields from "${fieldsSingle.importPath}";`);
				regLines.push("type _FieldTypes = typeof _fields;");
			}
			regLines.push("");

			regLines.push("declare global {");
			regLines.push("\tnamespace Questpie {");
			for (const aug of augmentations) {
				regLines.push(aug);
			}
			regLines.push("\t}");
			regLines.push("}");
			regLines.push("");

			registriesCode = regLines.join("\n");

			// Add side-effect import in module.ts to ensure augmentations are loaded
			// Insert after the header comments (before any other imports)
			lines.splice(3, 0, 'import "./registries.js";', "");
		}
	}

	return {
		code: lines.join("\n"),
		registriesCode,
	};
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Derive a PascalCase type prefix from a module name.
 * "questpie-admin" → "Admin"
 * "questpie-audit" → "Audit"
 * "billing" → "Billing"
 */
function deriveTypePrefix(moduleName: string): string {
	// Remove "questpie-" prefix if present
	const name = moduleName.replace(/^questpie-/, "");
	// Split on hyphens and PascalCase
	return name
		.split("-")
		.map((s) => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/**
 * Get all singles except "modules" (which is handled separately).
 */
function getNonModuleSingles(
	singles: Map<string, DiscoveredFile>,
): DiscoveredFile[] {
	const result: DiscoveredFile[] = [];
	for (const [key, file] of singles) {
		if (key === "modules") continue;
		result.push(file);
	}
	return result.sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Emit a plain type interface for a module category (no sub-module extends).
 * Always emit named types to prevent TS7056 ("inferred type exceeds maximum
 * length") when collection builder types are deeply nested via .merge().set().
 */
function emitSimpleTypeInterface(
	lines: string[],
	typeName: string,
	fileMap: Map<string, DiscoveredFile>,
	decl: CategoryDeclaration | undefined,
): void {
	const leafFiles = sortedValues(fileMap).filter((f) => !f.isBundle);
	const bundleFiles = sortedValues(fileMap).filter((f) => f.isBundle);

	if (decl?.keyFromProperty) {
		lines.push(`export type ${typeName} =`);
		const parts = [
			...leafFiles.map(
				(file) =>
					`{ [K in typeof ${file.varName}.${decl.keyFromProperty}]: typeof ${file.varName} }`,
			),
			...bundleFiles.map((bundle) => `typeof ${bundle.varName}`),
		];
		for (const [index, part] of parts.entries()) {
			const suffix = index === parts.length - 1 ? ";" : " &";
			lines.push(`\t${part}${suffix}`);
		}
		lines.push("");
		return;
	}

	if (bundleFiles.length === 0) {
		// No bundles — simple interface
		lines.push(`export interface ${typeName} {`);
		for (const file of leafFiles) {
			lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
		}
		lines.push("}");
	} else {
		// Bundles present — use type alias with intersection to capture spread keys
		const parts: string[] = [];
		if (leafFiles.length > 0) {
			parts.push(
				`{ ${leafFiles.map((f) => `${safeKey(f.key)}: typeof ${f.varName}`).join("; ")} }`,
			);
		}
		for (const bundle of bundleFiles) {
			parts.push(`typeof ${bundle.varName}`);
		}
		lines.push(`export type ${typeName} = ${parts.join(" & ")};`);
	}
	lines.push("");
}

function emitSimpleRouteTypeInterface(
	lines: string[],
	typeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	const leafFiles = sortedValues(fileMap).filter((f) => !f.isBundle);
	const bundleFiles = sortedValues(fileMap).filter((f) => f.isBundle);

	if (bundleFiles.length === 0) {
		lines.push(`export interface ${typeName} {`);
		for (const file of leafFiles) {
			lines.push(
				`\t${safeKey(file.key)}: RouteWithParams<typeof ${file.varName}, RouteParamsFromKey<${JSON.stringify(file.key)}>>;`,
			);
		}
		lines.push("}");
	} else {
		const parts: string[] = [];
		if (leafFiles.length > 0) {
			parts.push(
				`{ ${leafFiles
					.map(
						(f) =>
							`${safeKey(f.key)}: RouteWithParams<typeof ${f.varName}, RouteParamsFromKey<${JSON.stringify(f.key)}>>`,
					)
					.join("; ")} }`,
			);
		}
		for (const bundle of bundleFiles) {
			parts.push(`typeof ${bundle.varName}`);
		}
		lines.push(`export type ${typeName} = ${parts.join(" & ")};`);
	}
	lines.push("");
}

// ============================================================================
// Nested structure builder (for emit: "nested" categories)
// ============================================================================

function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	return `import ${file.varName} from "${file.importPath}";`;
}

function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}
