/**
 * Template Generation
 *
 * Generates the `.generated/index.ts` file content from discovered files.
 * The generated file:
 * 1. Imports the runtime config, modules, and all discovered entities
 * 2. Emits type interfaces using typeof references (zero inference cost)
 * 3. Calls createApp(definition, runtime) to create the app instance
 * 4. Exports the app and composed App type
 *
 * All category-specific behavior (imports, types, runtime emission) is driven
 * by CategoryDeclaration metadata from plugins. Categories without explicit
 * metadata get sensible defaults matching the standard record pattern.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */

import type {
	CategoryDeclaration,
	DiscoveredFile,
	DiscoverPattern,
	DiscoveryResult,
	SingletonFactory,
} from "./types.js";

// ============================================================================
// Template generation
// ============================================================================

export interface TemplateOptions {
	/** Path to questpie.config.ts relative to .generated directory. */
	configImportPath: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Merged category declarations from the resolved target. */
	categories?: Record<string, CategoryDeclaration>;
	/** Merged singleton factories from the resolved target (for re-export names). */
	singletonFactories?: Record<string, SingletonFactory>;
	/** Additional imports from plugins. */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/** Additional runtime code from plugins. */
	extraRuntimeCode?: string[];
	/** Additional entity keys to pass to createApp (from plugins). */
	extraEntities?: Map<string, string>;
	/** Discover patterns from the resolved target (for ~-prefixed registryKey handling). */
	discoverPatterns?: Record<string, DiscoverPattern>;
}

/**
 * Generate the .generated/index.ts file content.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */
export function generateTemplate(options: TemplateOptions): string {
	const lines: string[] = [];
	const {
		configImportPath,
		discovered,
		categories,
		singletonFactories,
		extraImports,
		extraTypeDeclarations,
		extraRuntimeCode,
		extraEntities,
		discoverPatterns,
	} = options;

	// Build category declarations map from the resolved target
	const allDecls = collectCategoryDeclarations(categories);
	const declaredCatNames = new Set(allDecls.keys());

	// modules.ts is required — new architecture only
	const modulesFile = discovered.singles.get("modules") ?? null;
	if (!modulesFile) {
		throw new Error(
			"[questpie] modules.ts is required. Create a modules.ts file in your questpie server directory.\n" +
				"See: https://questpie.com/docs/modules",
		);
	}

	// Header
	lines.push("/* oxlint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate");
	lines.push("");

	// Import createApp + types
	lines.push(
		'import { createApp, createContextFactory, extractAppServices, type AppDefinition, type Questpie, type AppContext, type Registry, type QuestpieConfig, type QueueClient, type CollectionAPI } from "questpie";',
	);
	lines.push("");

	// Import runtime config
	lines.push("// ── Runtime ────────────────────────────────────────────────");
	lines.push(`import _runtime from "${configImportPath}";`);
	lines.push("");

	// Import modules from singles (new architecture)
	if (modulesFile) {
		lines.push(
			"// ── Modules ────────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// ── Import declared categories (from plugin.categories) ────────
	// These are emitted first, in plugin declaration order.
	for (const [catName, fileMap] of discovered.categories) {
		if (!declaredCatNames.has(catName)) continue;
		if (fileMap.size === 0) continue;

		const decl = allDecls.get(catName)!;
		const label = capitalize(catName);
		lines.push(sectionComment(label));

		// Extra type imports (e.g. ServiceInstanceOf, MailerService)
		if (decl.extraTypeImports) {
			for (const imp of decl.extraTypeImports) {
				lines.push(imp);
			}
		}

		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import core singles (auth, locale, hooks, access, context) — excluding modules (already imported)
	const coreSingles = getCategorizedSingles(discovered.singles, allDecls);
	if (coreSingles.core.length > 0) {
		lines.push(
			"// ── Core Singles ───────────────────────────────────────────",
		);
		for (const file of coreSingles.core) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import plugin singles (sidebar, dashboard, branding, adminLocale, etc.)
	if (coreSingles.plugin.length > 0) {
		lines.push(
			"// ── Plugin Singles ─────────────────────────────────────────",
		);
		for (const file of coreSingles.plugin) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import spread singles (sidebar, dashboard — mergeStrategy: "spread")
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const label = capitalize(stateKey);
			lines.push(
				`// ── ${label} (spread) ─────────────────────────────────────────`,
			);
			for (const file of files) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// ── Import undeclared categories (from plugin.discover directory patterns) ──
	// These are categories without CategoryDeclaration metadata (e.g. blocks).
	for (const [catName, fileMap] of discovered.categories) {
		if (declaredCatNames.has(catName)) continue;
		if (fileMap.size === 0) continue;

		const label = capitalize(catName);
		lines.push(sectionComment(label));
		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — composed from typeof references (zero inference cost)
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push(
		"// TYPES — composed from typeof references (zero inference cost)",
	);
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	lines.push(
		'import type { ServiceCustomNamespaceInstances, ServiceInstanceOf, ServiceInstancesInNamespace, ServiceTopLevelInstances, UnionToIntersection } from "questpie";',
	);
	lines.push(`type _Module = (typeof ${modulesFile.varName})[number];`);
	lines.push(
		"type _MPRaw<K extends string> = UnionToIntersection<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;",
	);
	lines.push(
		"type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;",
	);
	lines.push("");

	// ── _Module* type extraction for categories ──────────────────
	for (const [catName, fileMap] of discovered.categories) {
		const decl = allDecls.get(catName);
		const shouldExtract = decl ? decl.extractFromModules !== false : true;
		if (!shouldExtract) continue;

		const moduleTypeName = deriveModuleTypeName(catName);
		lines.push(`type ${moduleTypeName} = _MP<"${catName}">;`);
	}
	// Also extract spread keys (sidebar, dashboard, etc.) from modules
	for (const [stateKey] of discovered.spreads) {
		const moduleTypeName = deriveModuleTypeName(stateKey);
		lines.push(`type ${moduleTypeName} = _MP<"${stateKey}">;`);
	}

	// ── Registry categories — extracted from modules via _MP<> ──────────
	// ALL categories with registryKey are extracted and merged here centrally.
	// Modules MUST NOT augment Registry — multiple modules declaring the same
	// key causes TS2717. The root template is the single source of truth.
	{
		const registryCatNames: Array<{ catName: string; regKey: string }> = [];
		for (const [catName, decl] of allDecls) {
			if (!decl.registryKey) continue;
			const regKey =
				typeof decl.registryKey === "string" ? decl.registryKey : catName;
			registryCatNames.push({ catName, regKey });
		}

		if (registryCatNames.length > 0) {
			lines.push("// Registry category extraction from modules");
			for (const { catName } of registryCatNames) {
				const typeName = `_Registry_${capitalize(catName)}`;
				lines.push(`type ${typeName} = _MP<"${catName}">;`);
			}
			lines.push("");
		}
	}

	// ── ~-prefixed registryKey extraction from modules ───────────────
	// Recursively extracts properties from modules + sub-modules.
	// Unlike _MP<> (top-level only), this recurses into sub-modules because
	// each module contributes its own field types (not merged into parent).
	{
		const tildeKeys = collectTildeRegistryKeys(
			discoverPatterns,
			discovered.singles,
		);
		if (tildeKeys.length > 0) {
			lines.push(
				"// Recursive module property extraction (for fields contributed at each level)",
			);
			lines.push('import type { ExtractModuleProp } from "questpie";');
			lines.push("");

			for (const { singleName, registryKey } of tildeKeys) {
				const userFile = discovered.singles.get(singleName);
				const typeName = `_AllModule${capitalize(singleName)}`;
				if (userFile) {
					lines.push(
						`type ${typeName} = ExtractModuleProp<{ modules: typeof ${modulesFile.varName} }, "${singleName}"> & typeof ${userFile.varName};`,
					);
				} else {
					lines.push(
						`type ${typeName} = ExtractModuleProp<{ modules: typeof ${modulesFile.varName} }, "${singleName}">;`,
					);
				}
			}
		}
	}
	lines.push("");

	// ── Augment factory registries with user-defined files ────────────
	// User-defined views, components, and fields augment the same
	// Questpie.*Registry interfaces that modules populate. This provides
	// autocomplete on v.*, c.*, f.* for BOTH module and user entities.
	// These augmentations use direct typeof references — NOT _MP<> — to
	// avoid circular dependencies.
	{
		const factoryRegistryAugmentations: string[] = [];
		const factoryTypeAliases: string[] = [];

		// Categories with recordPlaceholder (views, components) — user files
		for (const [catName, decl] of allDecls) {
			if (!decl.recordPlaceholder) continue;
			const fileMap = discovered.categories.get(catName);
			if (!fileMap || fileMap.size === 0) continue;

			const cap = capitalize(catName);
			const interfaceName = `${cap}Registry`;

			// Build inline type with user file entries
			const entries = sortedValues(fileMap)
				.map((f) => `${safeKey(f.key)}: typeof ${f.varName}`)
				.join("; ");
			factoryRegistryAugmentations.push(
				`\t\tinterface ${interfaceName} { ${entries}; }`,
			);
		}

		// User fields.ts → FieldTypesMap
		// NOTE: We use a type alias instead of inline `extends typeof _fields`
		// because some bundlers (rolldown/tsdown) cannot parse that syntax.
		{
			const tildeKeys = collectTildeRegistryKeys(
				discoverPatterns,
				discovered.singles,
			);
			for (const { singleName } of tildeKeys) {
				if (singleName !== "fields") continue;
				const userFile = discovered.singles.get(singleName);
				if (userFile) {
					const aliasName = `_UserFieldTypes`;
					factoryTypeAliases.push(
						`type ${aliasName} = typeof ${userFile.varName};`,
					);
					factoryRegistryAugmentations.push(
						`\t\tinterface FieldTypesMap extends ${aliasName} {}`,
					);
				}
			}
		}

		if (factoryRegistryAugmentations.length > 0) {
			lines.push("// Augment factory registries with user-defined files");

			// Emit type aliases before declare global (bundler compatibility)
			for (const alias of factoryTypeAliases) {
				lines.push(alias);
			}

			lines.push("declare global {");
			lines.push("\tnamespace Questpie {");
			for (const aug of factoryRegistryAugmentations) {
				lines.push(aug);
			}
			lines.push("\t}");
			lines.push("}");
			lines.push("");
		}
	}

	// ── App* type interfaces for each category ───────────────────
	for (const [catName, fileMap] of discovered.categories) {
		const decl = allDecls.get(catName);
		const typeEmit = decl?.typeEmit ?? "standard";
		const appTypeName = deriveAppTypeName(catName, decl);
		const moduleTypeName = deriveModuleTypeName(catName);

		switch (typeEmit) {
			case "standard": {
				emitTypeInterface(lines, appTypeName, moduleTypeName, fileMap);
				break;
			}
			case "services": {
				const hasUser = fileMap.size > 0;
				lines.push(
					"/** All service definitions in the app (modules + user, user overrides). */",
				);
				if (hasUser) {
					lines.push(`type _AppServiceDefinitions = ${moduleTypeName} & {`);
					for (const file of sortedValues(fileMap)) {
						lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
					}
					lines.push("};");
				} else {
					lines.push(`type _AppServiceDefinitions = ${moduleTypeName};`);
				}
				lines.push("");
				lines.push(
					"/** All services in the app as resolved service instances. */",
				);
				lines.push(`export type ${appTypeName} = {`);
				lines.push(
					"\t[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;",
				);
				lines.push("};");
				lines.push(
					'type _AppDefaultServices = ServiceInstancesInNamespace<_AppServiceDefinitions, "services">;',
				);
				lines.push(
					"type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;",
				);
				lines.push(
					"type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;",
				);
				lines.push("");
				break;
			}
			case "emails": {
				const hasFiles = fileMap.size > 0;
				lines.push(
					"/** All email templates in the app — use with email.sendTemplate() */",
				);
				if (hasFiles) {
					lines.push(`export type ${appTypeName} = {`);
					for (const file of sortedValues(fileMap)) {
						lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
					}
					lines.push("};");
				} else {
					lines.push(`export type ${appTypeName} = Record<string, never>;`);
				}
				lines.push("");
				break;
			}
			case "messages": {
				if (fileMap.size > 0) {
					lines.push(
						"/** Message keys — union of all keys from all locales */",
					);
					const msgParts = sortedValues(fileMap).map(
						(f) => `keyof typeof ${f.varName}`,
					);
					lines.push(`export type AppMessageKeys = ${msgParts.join(" | ")};`);
					lines.push("");
				}
				break;
			}
			case "none": {
				// No type emitted (migrations, seeds)
				break;
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ── Context resolver return type auto-propagation ────────────
	// If a context resolver is discovered (via appConfig.context or standalone context.ts),
	// emit a type that extracts its return type and augments QuestpieContextExtension.
	// This makes custom context properties available on all handler `ctx` parameters.
	{
		const appConfigFile = discovered.singles.get("appConfig");
		const contextFile = discovered.singles.get("contextResolver");
		let contextTypeExpr: string | null = null;

		if (appConfigFile?.configKey) {
			// Config bucket: context is a property of the appConfig export
			contextTypeExpr = `typeof ${appConfigFile.varName}.context`;
		} else if (appConfigFile?.destructure && "context" in appConfigFile.destructure) {
			// Legacy destructure: context is a property of the appConfig export
			contextTypeExpr = `typeof ${appConfigFile.varName}.context`;
		} else if (contextFile) {
			// Standalone context.ts
			contextTypeExpr = `typeof ${contextFile.varName}`;
		}

		if (contextTypeExpr) {
			lines.push("// Context resolver return type → auto-typed handler ctx");
			lines.push(
				`type _ContextReturn = ${contextTypeExpr} extends (...args: any[]) => any`,
			);
			lines.push(
				`\t? Awaited<ReturnType<${contextTypeExpr}>>`,
			);
			lines.push("\t: {};");
			lines.push("declare global {");
			lines.push("\tnamespace Questpie {");
			lines.push(
				"\t\tinterface QuestpieContextExtension extends _ContextReturn {}",
			);
			lines.push("\t}");
			lines.push("}");
			lines.push("");
		}
	}

	// ── App — the full Questpie<> app type ──────────────────────
	{
		const stateMembers: string[] = [];

		for (const [catName] of discovered.categories) {
			const decl = allDecls.get(catName);
			const include = decl ? decl.includeInAppState !== false : true;
			if (!include) continue;
			const appTypeName = deriveAppTypeName(catName, decl);
			stateMembers.push(`\t${catName}: ${appTypeName};`);
		}

		// Messages — special ~messageKeys member
		const messagesMap = discovered.categories.get("messages");
		if (messagesMap && messagesMap.size > 0) {
			stateMembers.push('\t"~messageKeys": AppMessageKeys;');
		}

		lines.push("/**");
		lines.push(" * The fully-typed app instance type.");
		lines.push(
			" * Use `typeof app` or this alias when you need to reference the app type.",
		);
		lines.push(" *");
		lines.push(
			" * **Note:** Do NOT import `app` inside framework-defined files (collections,",
		);
		lines.push(
			" * globals, routes, hooks, blocks) — it creates circular dependencies with",
		);
		lines.push(
			" * the generated index. Use the context parameters provided to handlers instead.",
		);
		lines.push(" */");
		lines.push("export type App = Questpie<QuestpieConfig & {");
		for (const member of stateMembers) {
			lines.push(member);
		}
		lines.push("}>;");
		lines.push("");
	}

	// ── AppContext augmentation — auto-types ALL handlers ──────
	{
		const emailsCat = discovered.categories.get("emails");
		const hasEmails = emailsCat && emailsCat.size > 0;
		const emailsTypeName = deriveAppTypeName("emails", allDecls.get("emails"));

		const messagesCat = discovered.categories.get("messages");
		const hasMessages = messagesCat && messagesCat.size > 0;

		const servicesCat = discovered.categories.get("services");
		const hasServices = !!servicesCat;

		// Skip App['api']['collections'] class getter indirection — map directly over AppCollections
		lines.push(
			"type _CollectionsAPI = { [K in keyof AppCollections]: CollectionAPI<AppCollections[K], AppCollections> };",
		);
		lines.push("");

		lines.push(
			"// ── AppContext augmentation — auto-types ALL handlers ──────",
		);
		lines.push("declare global {");
		lines.push("\tnamespace Questpie {");
		if (hasServices) {
			lines.push(
				"\t\tinterface AppContext extends _AppTopLevelServices, _AppCustomServiceNamespaces {",
			);
		} else {
			lines.push("\t\tinterface AppContext {");
		}
		lines.push("\t\t\t// Infrastructure");
		lines.push("\t\t\tdb: App['db'];");
		if (hasEmails) {
			lines.push(`\t\t\temail: MailerService<${emailsTypeName}>;`);
		} else {
			lines.push("\t\t\temail: App['email'];");
		}
		lines.push("\t\t\tqueue: QueueClient<AppJobs>;");
		lines.push("\t\t\tstorage: App['storage'];");
		lines.push("\t\t\tkv: App['kv'];");
		lines.push("\t\t\tlogger: App['logger'];");
		lines.push("\t\t\tsearch: App['search'];");
		lines.push("\t\t\trealtime: App['realtime'];");
		lines.push("");
		lines.push("\t\t\t// Entity APIs");
		lines.push("\t\t\tcollections: _CollectionsAPI;");
		lines.push("\t\t\tglobals: App['api']['globals'];");
		lines.push("\t\t\ttables: App['tables'];");
		lines.push("");
		lines.push("\t\t\t// Request-scoped");
		lines.push(
			"\t\t\tsession: App['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;",
		);
		if (hasMessages) {
			lines.push(
				"\t\t\tt: (key: AppMessageKeys | (string & {}), params?: Record<string, unknown>, locale?: string) => string;",
			);
		} else {
			lines.push(
				"\t\t\tt: (key: string, params?: Record<string, unknown>, locale?: string) => string;",
			);
		}

		// Services — default namespace under `services`
		if (hasServices) {
			lines.push("");
			lines.push("\t\t\t// User services");
			lines.push("\t\t\tservices: _AppDefaultServices;");
		}

		lines.push("\t\t}");
		lines.push("");
		lines.push("\t\tinterface ServiceCreateContext extends AppContext {}");

		// Registry — ALL registryKey categories + ~-prefixed singles augmented centrally.
		// This is the SINGLE place that augments Registry. Modules never augment it.
		{
			const registryEntries: string[] = [];

			// Category registryKeys (views, components, blocks, listViews, etc.)
			for (const [catName, decl] of allDecls) {
				if (!decl.registryKey) continue;
				const regKey =
					typeof decl.registryKey === "string" ? decl.registryKey : catName;
				const typeName = `_Registry_${capitalize(catName)}`;
				registryEntries.push(`\t\t\t${safeKey(regKey)}: ${typeName};`);
			}

			// ~-prefixed registryKeys from singles (e.g. ~fieldTypes)
			const tildeKeys = collectTildeRegistryKeys(
				discoverPatterns,
				discovered.singles,
			);
			for (const { singleName, registryKey } of tildeKeys) {
				const typeName = `_AllModule${capitalize(singleName)}`;
				registryEntries.push(`\t\t\t${safeKey(registryKey)}: ${typeName};`);
			}

			if (registryEntries.length > 0) {
				lines.push("");
				lines.push("\t\tinterface Registry {");
				for (const entry of registryEntries) {
					lines.push(entry);
				}
				lines.push("\t\t}");
			}
		}

		lines.push("\t}");
		lines.push("}");
		lines.push("");
	}

	// AppConfig — flat type for client APIs (createClient<AppConfig>(), createAdminAuthClient<AppConfig>())
	lines.push("/**");
	lines.push(" * Flat config type for client APIs.");
	lines.push(
		" * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.",
	);
	lines.push(
		" * For handler context, use `AppContext` (auto-typed via module augmentation).",
	);
	lines.push(" */");
	lines.push("export type AppConfig = {");
	lines.push("\tcollections: AppCollections & Record<string, any>;");
	lines.push("\tglobals: AppGlobals & Record<string, any>;");
	lines.push("\troutes: AppRoutes;");
	const authConfigFile = discovered.singles.get("authConfig");
	const authFile = authConfigFile ?? discovered.singles.get("auth");
	if (authFile) {
		lines.push(`\tauth: typeof ${authFile.varName};`);
	}
	lines.push("};");
	lines.push("");

	// ════════════════════════════════════════════════════════════
	// RUNTIME — create the app instance
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// RUNTIME — create the app instance");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	emitNewArchitectureRuntime(lines, discovered, allDecls, extraEntities);

	// createContext() — typed context factory for scripts/standalone usage
	lines.push("// ── createContext — typed context for scripts ──────────────");
	lines.push("/**");
	lines.push(
		" * Create a typed AppContext for use in scripts, tests, or standalone code.",
	);
	lines.push(
		" * Resolves all services and provides flat access to infrastructure.",
	);
	lines.push(" *");
	lines.push(" * @example");
	lines.push(" * ```ts");
	lines.push(' * import { createContext } from "#questpie";');
	lines.push(" *");
	lines.push(" * const ctx = await createContext();");
	lines.push(" * const posts = await ctx.collections.posts.find({});");
	lines.push(" * ```");
	lines.push(" */");
	lines.push("export const createContext = createContextFactory(app);");
	lines.push("");

	// Factories are available via #questpie/factories (separate entry to avoid circular deps)
	lines.push(
		"// Factories: import { collection, global, ... } from '#questpie/factories';",
	);
	lines.push("");

	// Extra runtime code from plugins
	if (extraRuntimeCode && extraRuntimeCode.length > 0) {
		for (const code of extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ============================================================================
// Runtime emission — new architecture
// ============================================================================

/**
 * Emit the createApp(definition, _runtime) call for new architecture.
 * Iterates over all discovered categories using CategoryDeclaration metadata
 * to determine how each category should be emitted (record, nested, array).
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1
 */
function emitNewArchitectureRuntime(
	lines: string[],
	discovered: DiscoveryResult,
	allDecls: Map<string, CategoryDeclaration>,
	extraEntities?: Map<string, string>,
): void {
	const modulesFile = discovered.singles.get("modules");
	if (!modulesFile) {
		throw new Error("emitNewArchitectureRuntime called without modules.ts");
	}
	const coreSingles = getCategorizedSingles(discovered.singles, allDecls);

	lines.push("export const app = await createApp(");
	lines.push("\t({");

	// Modules
	lines.push(`\t\tmodules: ${modulesFile.varName} as any,`);

	// ── Emit all categories ──────────────────────────────────────
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;

		const decl = allDecls.get(catName);
		const emitMode = decl?.emit ?? "record";
		const createAppKey = decl?.createAppKey ?? catName;

		switch (emitMode) {
			case "record": {
				lines.push(`\t\t${safeKey(createAppKey)}: {`);
				for (const file of sortedValues(fileMap)) {
					if (decl?.keyFromProperty) {
						lines.push(
							`\t\t\t[${file.varName}.${decl.keyFromProperty}]: ${file.varName},`,
						);
					} else {
						lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
					}
				}
				lines.push("\t\t},");
				break;
			}
			case "array": {
				const vars = sortedValues(fileMap)
					.map((f) => f.varName)
					.join(", ");
				lines.push(`\t\t${safeKey(createAppKey)}: [${vars}],`);
				break;
			}
		}
	}

	// Separate config-bucket singles from plain singles
	const allSingles = [...coreSingles.core, ...coreSingles.plugin];
	const configEntries: Array<{ configKey: string; file: DiscoveredFile }> = [];
	const plainSingles: DiscoveredFile[] = [];

	for (const file of allSingles) {
		if (file.configKey) {
			configEntries.push({ configKey: file.configKey, file });
		} else if (file.key !== "modules") {
			plainSingles.push(file);
		}
	}

	// Emit config bucket — each config file = one key
	if (configEntries.length > 0) {
		lines.push("\t\tconfig: {");
		for (const { configKey, file } of configEntries) {
			lines.push(`\t\t\t${safeKey(configKey)}: ${file.varName} as any,`);
		}
		lines.push("\t\t},");
	}

	// Plain singles (fields, etc.) — NOT config files
	for (const file of plainSingles) {
		lines.push(`\t\t${safeKey(file.key)}: ${file.varName} as any,`);
	}

	// Spread singles (sidebar, dashboard — mergeStrategy: "spread")
	// NOTE: With the config bucket, spreads from features should flow into
	// the config bucket too. For now, keep spread emission for backward compat.
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const spread = files
				.map((f) => `...(${f.varName} as any ?? [])`)
				.join(", ");
			lines.push(`\t\t${safeKey(stateKey)}: [${spread}],`);
		}
	}

	// Extra entities from plugins
	if (extraEntities) {
		for (const [key, value] of extraEntities) {
			lines.push(`\t\t${safeKey(key)}: ${value},`);
		}
	}

	lines.push("\t}) satisfies AppDefinition,");
	lines.push("\t_runtime,");
	lines.push(") as unknown as App;");
	lines.push("");
}

// ============================================================================
// Category metadata helpers
// ============================================================================

/**
 * Build a Map of category declarations from the resolved target's merged categories.
 */
function collectCategoryDeclarations(
	categories?: Record<string, CategoryDeclaration>,
): Map<string, CategoryDeclaration> {
	const result = new Map<string, CategoryDeclaration>();
	if (!categories) return result;
	for (const [name, decl] of Object.entries(categories)) {
		result.set(name, decl);
	}
	return result;
}

function capitalize(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Derive the App type name for a category.
 * Uses createAppKey if set, otherwise uses the category name.
 * e.g., "collections" → "AppCollections", "emails" (createAppKey: "emailTemplates") → "AppEmailTemplates"
 */
function deriveAppTypeName(
	catName: string,
	decl?: CategoryDeclaration,
): string {
	const key = decl?.createAppKey ?? catName;
	return `App${capitalize(key)}`;
}

/**
 * Derive the _Module type name for a category.
 * e.g., "collections" → "_ModuleCollections"
 */
function deriveModuleTypeName(catName: string): string {
	return `_Module${capitalize(catName)}`;
}

/**
 * Generate a section comment with consistent formatting.
 */
function sectionComment(label: string): string {
	const base = `// ── ${label} `;
	const dashes = "─".repeat(Math.max(0, 62 - base.length));
	return base + dashes;
}

// ============================================================================
// Singles categorization
// ============================================================================

/**
 * Well-known core single file keys.
 * Determined from corePlugin().discover patterns.
 * Used to separate "Core Singles" from "Plugin Singles" in generated comments.
 */
function getCoreSingleKeys(
	allDecls: Map<string, CategoryDeclaration>,
): Set<string> {
	// Core singles are those discovered by any plugin that also declares categories.
	// In practice, this is the core plugin which declares modules, locale, hooks, etc.
	// We use a simple heuristic: keys that match well-known core patterns.
	return new Set([
		"modules",
		"authConfig",
		"appConfig",
	]);
}

interface CategorizedSingles {
	/** Core singles (locale, hooks, access, context) — NOT modules. */
	core: DiscoveredFile[];
	/** Plugin-discovered singles (sidebar, dashboard, branding, adminLocale, etc.). */
	plugin: DiscoveredFile[];
}

/**
 * Categorize singles into core (always available) and plugin-discovered.
 * Excludes "modules" since that's handled separately.
 */
function getCategorizedSingles(
	singles: Map<string, DiscoveredFile>,
	allDecls: Map<string, CategoryDeclaration>,
): CategorizedSingles {
	const coreSingleKeys = getCoreSingleKeys(allDecls);
	const core: DiscoveredFile[] = [];
	const plugin: DiscoveredFile[] = [];

	for (const [key, file] of singles) {
		if (key === "modules") continue; // handled separately
		if (coreSingleKeys.has(key)) {
			core.push(file);
		} else {
			plugin.push(file);
		}
	}

	// Sort for deterministic output
	core.sort((a, b) => a.key.localeCompare(b.key));
	plugin.sort((a, b) => a.key.localeCompare(b.key));

	return { core, plugin };
}

// ============================================================================
// Type interface emission helper
// ============================================================================

/**
 * Emit a type interface or type alias for a category (collections, globals, etc.).
 * When user has entities, emits `export type X = _ModuleX & { ... }`.
 * Otherwise emits `export type X = _ModuleX;`.
 */
function emitTypeInterface(
	lines: string[],
	typeName: string,
	moduleTypeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	const label = typeName.replace(/^App/, "").toLowerCase();
	const hasUser = fileMap.size > 0;
	lines.push(`/** All ${label} in the app (modules + user, user overrides) */`);
	if (hasUser) {
		lines.push(`export type ${typeName} = ${moduleTypeName} & {`);
		for (const file of sortedValues(fileMap)) {
			lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
		}
		lines.push("};");
	} else {
		lines.push(`export type ${typeName} = ${moduleTypeName};`);
	}
	lines.push("");
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Sort discovered files by key for deterministic output.
 */
function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Generate the import statement for a discovered file.
 * Uses default import for "default" exports, named import for "named" exports.
 */
function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	// default or unknown — use default import
	return `import ${file.varName} from "${file.importPath}";`;
}

/**
 * Quote a key if it's not a valid identifier.
 */
function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}

/**
 * Collect singleton discover patterns with ~-prefixed registryKeys.
 * These need centralized augmentation in the root template (not per-module)
 * to avoid TypeScript merge conflicts when multiple modules contribute.
 */
function collectTildeRegistryKeys(
	discoverPatterns: Record<string, DiscoverPattern> | undefined,
	singles: Map<string, DiscoveredFile>,
): Array<{ singleName: string; registryKey: string }> {
	if (!discoverPatterns) return [];
	const result: Array<{ singleName: string; registryKey: string }> = [];
	for (const [name, pattern] of Object.entries(discoverPatterns)) {
		if (typeof pattern !== "object" || !pattern.registryKey) continue;
		if (!pattern.registryKey.startsWith("~")) continue;
		// Only include if at least modules exist (which provide the fields).
		// The user may also have a fields.ts — handled by the type emission.
		result.push({ singleName: name, registryKey: pattern.registryKey });
	}
	return result.sort((a, b) => a.singleName.localeCompare(b.singleName));
}
