/**
 * Template Generation
 *
 * Generates the `.generated/index.ts` file content from discovered files.
 * The generated file:
 * 1. Imports the runtime config, modules, and all discovered entities
 * 2. Emits type interfaces using typeof references (zero inference cost)
 * 3. Calls createApp(definition, runtime) to create the app instance
 * 4. Exports the app and composed App type
 *
 * All category-specific behavior (imports, types, runtime emission) is driven
 * by CategoryDeclaration metadata from plugins. Categories without explicit
 * metadata get sensible defaults matching the standard record pattern.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */

import type {
	CategoryDeclaration,
	DiscoverPattern,
	DiscoveredFile,
	DiscoveryResult,
	SingletonFactory,
} from "./types.js";

// ============================================================================
// Template generation
// ============================================================================

export interface TemplateOptions {
	/** Path to questpie.config.ts relative to .generated directory. */
	configImportPath: string;
	/** Discovery result with all found files. */
	discovered: DiscoveryResult;
	/** Merged category declarations from the resolved target. */
	categories?: Record<string, CategoryDeclaration>;
	/** Merged singleton factories from the resolved target (for re-export names). */
	singletonFactories?: Record<string, SingletonFactory>;
	/** Additional imports from plugins. */
	extraImports?: Array<{ name: string; path: string }>;
	/** Additional type declarations from plugins. */
	extraTypeDeclarations?: string[];
	/** Additional runtime code from plugins. */
	extraRuntimeCode?: string[];
	/** Additional entity keys to pass to createApp (from plugins). */
	extraEntities?: Map<string, string>;
	/** Discover patterns from the resolved target (for ~-prefixed registryKey handling). */
	discoverPatterns?: Record<string, DiscoverPattern>;
}

/**
 * Generate the .generated/index.ts file content.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */
export function generateTemplate(options: TemplateOptions): string {
	const lines: string[] = [];
	const {
		configImportPath,
		discovered,
		categories,
		singletonFactories,
		extraImports,
		extraTypeDeclarations,
		extraRuntimeCode,
		extraEntities,
		discoverPatterns,
	} = options;

	// Build category declarations map from the resolved target
	const allDecls = collectCategoryDeclarations(categories);
	const declaredCatNames = new Set(allDecls.keys());

	// modules.ts is required — new architecture only
	const modulesFile = discovered.singles.get("modules") ?? null;
	if (!modulesFile) {
		throw new Error(
			"[questpie] modules.ts is required. Create a modules.ts file in your questpie server directory.\n" +
				"See: https://questpie.com/docs/modules",
		);
	}

	// Header
	lines.push("/* eslint-disable */");
	lines.push("// AUTO-GENERATED by questpie codegen — DO NOT EDIT");
	lines.push("// Regenerate with: questpie generate");
	lines.push("");

	// Import createApp + types
	lines.push(
		'import { createApp, extractAppServices, type Questpie, type AppContext, type Registry, type QuestpieConfig, type QueueClient } from "questpie";',
	);
	lines.push("");

	// Import runtime config
	lines.push("// ── Runtime ────────────────────────────────────────────────");
	lines.push(`import _runtime from "${configImportPath}";`);
	lines.push("");

	// Import modules from singles (new architecture)
	if (modulesFile) {
		lines.push(
			"// ── Modules ────────────────────────────────────────────────",
		);
		lines.push(importStatement(modulesFile));
		lines.push("");
	}

	// ── Import declared categories (from plugin.categories) ────────
	// These are emitted first, in plugin declaration order.
	for (const [catName, fileMap] of discovered.categories) {
		if (!declaredCatNames.has(catName)) continue;
		if (fileMap.size === 0) continue;

		const decl = allDecls.get(catName)!;
		const label = capitalize(catName);
		lines.push(sectionComment(label));

		// Extra type imports (e.g. ServiceInstanceOf, MailerService)
		if (decl.extraTypeImports) {
			for (const imp of decl.extraTypeImports) {
				lines.push(imp);
			}
		}

		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import core singles (auth, locale, hooks, access, context) — excluding modules (already imported)
	const coreSingles = getCategorizedSingles(discovered.singles, allDecls);
	if (coreSingles.core.length > 0) {
		lines.push(
			"// ── Core Singles ───────────────────────────────────────────",
		);
		for (const file of coreSingles.core) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import plugin singles (sidebar, dashboard, branding, adminLocale, etc.)
	if (coreSingles.plugin.length > 0) {
		lines.push(
			"// ── Plugin Singles ─────────────────────────────────────────",
		);
		for (const file of coreSingles.plugin) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Import spread singles (sidebar, dashboard — mergeStrategy: "spread")
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const label = capitalize(stateKey);
			lines.push(
				`// ── ${label} (spread) ─────────────────────────────────────────`,
			);
			for (const file of files) {
				lines.push(importStatement(file));
			}
			lines.push("");
		}
	}

	// ── Import undeclared categories (from plugin.discover directory patterns) ──
	// These are categories without CategoryDeclaration metadata (e.g. blocks).
	for (const [catName, fileMap] of discovered.categories) {
		if (declaredCatNames.has(catName)) continue;
		if (fileMap.size === 0) continue;

		const label = capitalize(catName);
		lines.push(sectionComment(label));
		for (const file of sortedValues(fileMap)) {
			lines.push(importStatement(file));
		}
		lines.push("");
	}

	// Extra plugin imports
	if (extraImports && extraImports.length > 0) {
		lines.push(
			"// ── Plugin Imports ─────────────────────────────────────────",
		);
		for (const imp of extraImports) {
			lines.push(`import ${imp.name} from "${imp.path}";`);
		}
		lines.push("");
	}

	// ════════════════════════════════════════════════════════════
	// TYPES — composed from typeof references (zero inference cost)
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push(
		"// TYPES — composed from typeof references (zero inference cost)",
	);
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	lines.push(
		"type _U2I<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;",
	);
	lines.push(`type _Module = (typeof ${modulesFile.varName})[number];`);
	lines.push(
		"type _MPRaw<K extends string> = _U2I<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;",
	);
	lines.push(
		"type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;",
	);
	lines.push("");

	// ── _Module* type extraction for categories ──────────────────
	for (const [catName, fileMap] of discovered.categories) {
		const decl = allDecls.get(catName);
		const shouldExtract = decl ? decl.extractFromModules !== false : true;
		if (!shouldExtract) continue;

		const moduleTypeName = deriveModuleTypeName(catName);
		lines.push(`type ${moduleTypeName} = _MP<"${catName}">;`);
	}
	// Also extract spread keys (sidebar, dashboard, etc.) from modules
	for (const [stateKey] of discovered.spreads) {
		const moduleTypeName = deriveModuleTypeName(stateKey);
		lines.push(`type ${moduleTypeName} = _MP<"${stateKey}">;`);
	}

	// NOTE: Module registries (views, listViews, formViews, components) are NOT
	// extracted here via _MP<>. They are augmented into Registry by each module's
	// own .generated/module.ts. This avoids circular references:
	//   typeof _modules → CollectionBuilder augmentation → Registry → typeof _modules.
	//
	// However, ~-prefixed registryKeys (like ~fieldTypes) ARE extracted here via
	// recursive module traversal. They must NOT be augmented per-module because
	// multiple modules augmenting the same Registry property with different types
	// causes TypeScript to degrade the merged type to `any`.

	// ── ~-prefixed registryKey extraction from modules ───────────────
	// Recursively extracts properties from modules + sub-modules.
	// Unlike _MP<> (top-level only), this recurses into sub-modules because
	// each module contributes its own field types (not merged into parent).
	{
		const tildeKeys = collectTildeRegistryKeys(discoverPatterns, discovered.singles);
		if (tildeKeys.length > 0) {
			lines.push(
				"// Recursive module property extraction (for fields contributed at each level)",
			);
			lines.push(
				`type _ExtractProp<M, K extends string> = (M extends { modules: infer Sub extends readonly any[] } ? _ExtractPropArr<Sub, K> : {}) & (K extends keyof M ? M[K] extends Record<string, any> ? M[K] : {} : {});`,
			);
			lines.push(
				`type _ExtractPropArr<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _ExtractProp<H, K> & _ExtractPropArr<T, K> : {};`,
			);
			lines.push("");

			for (const { singleName, registryKey } of tildeKeys) {
				const userFile = discovered.singles.get(singleName);
				const typeName = `_AllModule${capitalize(singleName)}`;
				if (userFile) {
					lines.push(
						`type ${typeName} = _ExtractProp<{ modules: typeof ${modulesFile.varName} }, "${singleName}"> & typeof ${userFile.varName};`,
					);
				} else {
					lines.push(
						`type ${typeName} = _ExtractProp<{ modules: typeof ${modulesFile.varName} }, "${singleName}">;`,
					);
				}
			}
		}
	}
	lines.push("");

	// ── App* type interfaces for each category ───────────────────
	for (const [catName, fileMap] of discovered.categories) {
		const decl = allDecls.get(catName);
		const typeEmit = decl?.typeEmit ?? "standard";
		const appTypeName = deriveAppTypeName(catName, decl);
		const moduleTypeName = deriveModuleTypeName(catName);

		switch (typeEmit) {
			case "standard": {
				emitTypeInterface(lines, appTypeName, moduleTypeName, fileMap);
				break;
			}
			case "functions": {
				const hasUser = fileMap.size > 0;
				lines.push(
					"/** All functions in the app (modules + user, user overrides) */",
				);
				if (hasUser) {
					lines.push(`export type ${appTypeName} = ${moduleTypeName} & {`);
					const nested = buildNestedFunctions(fileMap);
					emitNestedTypeObject(lines, nested, 1);
					lines.push("};");
				} else {
					lines.push(`export type ${appTypeName} = ${moduleTypeName};`);
				}
				lines.push("");
				break;
			}
			case "services": {
				const hasUser = fileMap.size > 0;
				lines.push(
					"/** All services in the app (modules + user, user overrides). Values are service instances. */",
				);
				if (hasUser) {
					lines.push(`export type ${appTypeName} = ${moduleTypeName} & {`);
					for (const file of sortedValues(fileMap)) {
						lines.push(
							`\t${safeKey(file.key)}: ServiceInstanceOf<typeof ${file.varName}>;`,
						);
					}
					lines.push("};");
				} else {
					lines.push(`export type ${appTypeName} = ${moduleTypeName};`);
				}
				lines.push("");
				break;
			}
			case "emails": {
				const hasFiles = fileMap.size > 0;
				lines.push(
					"/** All email templates in the app — use with email.sendTemplate() */",
				);
				if (hasFiles) {
					lines.push(`export type ${appTypeName} = {`);
					for (const file of sortedValues(fileMap)) {
						lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
					}
					lines.push("};");
				} else {
					lines.push(`export type ${appTypeName} = Record<string, never>;`);
				}
				lines.push("");
				break;
			}
			case "messages": {
				if (fileMap.size > 0) {
					lines.push(
						"/** Message keys — union of all keys from all locales */",
					);
					const msgParts = sortedValues(fileMap).map(
						(f) => `keyof typeof ${f.varName}`,
					);
					lines.push(`export type AppMessageKeys = ${msgParts.join(" | ")};`);
					lines.push("");
				}
				break;
			}
			case "none": {
				// No type emitted (migrations, seeds)
				break;
			}
		}
	}

	// Extra type declarations from plugins
	if (extraTypeDeclarations && extraTypeDeclarations.length > 0) {
		for (const decl of extraTypeDeclarations) {
			lines.push(decl);
		}
		lines.push("");
	}

	// ── _AppInternal — internal Questpie<> type ──────────────────
	{
		const stateMembers: string[] = [];

		for (const [catName] of discovered.categories) {
			const decl = allDecls.get(catName);
			const include = decl ? decl.includeInAppState !== false : true;
			if (!include) continue;
			const appTypeName = deriveAppTypeName(catName, decl);
			stateMembers.push(`\t${catName}: ${appTypeName};`);
		}

		// Messages — special ~messageKeys member
		const messagesMap = discovered.categories.get("messages");
		if (messagesMap && messagesMap.size > 0) {
			stateMembers.push('\t"~messageKeys": AppMessageKeys;');
		}

		lines.push(
			"/** @internal — used only for type derivation, not exported */",
		);
		lines.push("type _AppInternal = Questpie<QuestpieConfig & {");
		for (const member of stateMembers) {
			lines.push(member);
		}
		lines.push("}>;");
		lines.push("");
	}

	// ── AppContext augmentation — auto-types ALL handlers ──────
	{
		const emailsCat = discovered.categories.get("emails");
		const hasEmails = emailsCat && emailsCat.size > 0;
		const emailsTypeName = deriveAppTypeName("emails", allDecls.get("emails"));

		const messagesCat = discovered.categories.get("messages");
		const hasMessages = messagesCat && messagesCat.size > 0;

		const servicesCat = discovered.categories.get("services");
		const hasServices = servicesCat && servicesCat.size > 0;

		lines.push(
			"// ── AppContext augmentation — auto-types ALL handlers ──────",
		);
		lines.push("declare global {");
		lines.push("\tnamespace Questpie {");
		lines.push("\t\tinterface AppContext {");
		lines.push("\t\t\t// Infrastructure");
		lines.push("\t\t\tdb: _AppInternal['db'];");
		if (hasEmails) {
			lines.push(`\t\t\temail: MailerService<${emailsTypeName}>;`);
		} else {
			lines.push("\t\t\temail: _AppInternal['email'];");
		}
		lines.push("\t\t\tqueue: QueueClient<AppJobs>;");
		lines.push("\t\t\tstorage: _AppInternal['storage'];");
		lines.push("\t\t\tkv: _AppInternal['kv'];");
		lines.push("\t\t\tlogger: _AppInternal['logger'];");
		lines.push("\t\t\tsearch: _AppInternal['search'];");
		lines.push("\t\t\trealtime: _AppInternal['realtime'];");
		lines.push("");
		lines.push("\t\t\t// Entity APIs");
		lines.push("\t\t\tcollections: _AppInternal['api']['collections'];");
		lines.push("\t\t\tglobals: _AppInternal['api']['globals'];");
		lines.push("\t\t\ttables: _AppInternal['tables'];");
		lines.push("");
		lines.push("\t\t\t// Request-scoped");
		lines.push(
			"\t\t\tsession: _AppInternal['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;",
		);
		if (hasMessages) {
			lines.push(
				"\t\t\tt: (key: AppMessageKeys | (string & {}), params?: Record<string, unknown>, locale?: string) => string;",
			);
		} else {
			lines.push(
				"\t\t\tt: (key: string, params?: Record<string, unknown>, locale?: string) => string;",
			);
		}

		// Services — namespaced under `services` (matches extractAppServices runtime)
		if (hasServices) {
			lines.push("");
			lines.push("\t\t\t// User services");
			lines.push("\t\t\tservices: AppServices;");
		}

		lines.push("\t\t}");

		// Registry — ~-prefixed registryKeys augmented centrally
		{
			const tildeKeys = collectTildeRegistryKeys(discoverPatterns, discovered.singles);
			if (tildeKeys.length > 0) {
				lines.push("");
				lines.push("\t\tinterface Registry {");
				for (const { singleName, registryKey } of tildeKeys) {
					const typeName = `_AllModule${capitalize(singleName)}`;
					lines.push(`\t\t\t${safeKey(registryKey)}: ${typeName};`);
				}
				lines.push("\t\t}");
			}
		}

		lines.push("\t}");
		lines.push("}");
		lines.push("");
	}

	// AppConfig — flat type for client APIs (createClient<AppConfig>(), createAdminAuthClient<AppConfig>())
	lines.push("/**");
	lines.push(" * Flat config type for client APIs.");
	lines.push(
		" * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.",
	);
	lines.push(
		" * For handler context, use `AppContext` (auto-typed via module augmentation).",
	);
	lines.push(" */");
	lines.push("export type AppConfig = {");
	lines.push("\tcollections: AppCollections & Record<string, any>;");
	lines.push("\tglobals: AppGlobals & Record<string, any>;");
	lines.push("\tfunctions: AppFunctions;");
	lines.push("\troutes: AppRoutes;");
	const authFile = discovered.singles.get("auth");
	if (authFile) {
		lines.push(`\tauth: typeof ${authFile.varName};`);
	}
	lines.push("};");
	lines.push("");

	// ════════════════════════════════════════════════════════════
	// RUNTIME — create the app instance
	// ════════════════════════════════════════════════════════════

	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("// RUNTIME — create the app instance");
	lines.push("// ════════════════════════════════════════════════════════════");
	lines.push("");

	emitNewArchitectureRuntime(lines, discovered, allDecls, extraEntities);

	// createContext() — typed context factory for scripts/standalone usage
	lines.push("// ── createContext — typed context for scripts ──────────────");
	lines.push("/**");
	lines.push(
		" * Create a typed AppContext for use in scripts, tests, or standalone code.",
	);
	lines.push(
		" * Resolves all services and provides flat access to infrastructure.",
	);
	lines.push(" *");
	lines.push(" * @example");
	lines.push(" * ```ts");
	lines.push(' * import { createContext } from "#questpie";');
	lines.push(" *");
	lines.push(" * const ctx = await createContext();");
	lines.push(" * const posts = await ctx.collections.posts.find({});");
	lines.push(" * ```");
	lines.push(" */");
	lines.push("export async function createContext(options?: {");
	lines.push("\taccessMode?: 'system' | 'user';");
	lines.push("}): Promise<AppContext> {");
	lines.push("\tconst reqCtx = await (app as any).createContext({");
	lines.push("\t\taccessMode: options?.accessMode ?? 'system',");
	lines.push("\t});");
	lines.push("\tconst services = extractAppServices(app, {");
	lines.push("\t\tdb: (app as any).db,");
	lines.push("\t\tsession: reqCtx.session,");
	lines.push("\t});");
	lines.push(
		"\treturn { ...services, locale: reqCtx.locale } as unknown as AppContext;",
	);
	lines.push("}");
	lines.push("");

	// Factories are available via #questpie/factories (separate entry to avoid circular deps)
	lines.push("// Factories: import { collection, global, ... } from '#questpie/factories';");
	lines.push("");

	// Extra runtime code from plugins
	if (extraRuntimeCode && extraRuntimeCode.length > 0) {
		for (const code of extraRuntimeCode) {
			lines.push(code);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ============================================================================
// Runtime emission — new architecture
// ============================================================================

/**
 * Emit the createApp(definition, _runtime) call for new architecture.
 * Iterates over all discovered categories using CategoryDeclaration metadata
 * to determine how each category should be emitted (record, nested, array).
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1
 */
function emitNewArchitectureRuntime(
	lines: string[],
	discovered: DiscoveryResult,
	allDecls: Map<string, CategoryDeclaration>,
	extraEntities?: Map<string, string>,
): void {
	const modulesFile = discovered.singles.get("modules");
	if (!modulesFile) {
		throw new Error("emitNewArchitectureRuntime called without modules.ts");
	}
	const coreSingles = getCategorizedSingles(discovered.singles, allDecls);

	lines.push("export const app = createApp(");
	lines.push("\t{");

	// Modules
	lines.push(`\t\tmodules: ${modulesFile.varName} as any,`);

	// ── Emit all categories ──────────────────────────────────────
	for (const [catName, fileMap] of discovered.categories) {
		if (fileMap.size === 0) continue;

		const decl = allDecls.get(catName);
		const emitMode = decl?.emit ?? "record";
		const createAppKey = decl?.createAppKey ?? catName;

		switch (emitMode) {
			case "record": {
				lines.push(`\t\t${safeKey(createAppKey)}: {`);
				for (const file of sortedValues(fileMap)) {
					if (decl?.keyFromProperty) {
						lines.push(`\t\t\t[${file.varName}.${decl.keyFromProperty}]: ${file.varName},`);
					} else {
						lines.push(`\t\t\t${safeKey(file.key)}: ${file.varName},`);
					}
				}
				lines.push("\t\t},");
				break;
			}
			case "nested": {
				lines.push(`\t\t${safeKey(createAppKey)}: {`);
				const nested = buildNestedFunctions(fileMap);
				emitNestedObject(lines, nested, 3);
				lines.push("\t\t},");
				break;
			}
			case "array": {
				const vars = sortedValues(fileMap)
					.map((f) => f.varName)
					.join(", ");
				lines.push(`\t\t${safeKey(createAppKey)}: [${vars}],`);
				break;
			}
		}
	}

	// Core singles (auth, locale, hooks, access, context)
	// Cast with `as any` because user files may use `as const` (readonly),
	// and the whole expression is cast to App anyway.
	for (const file of coreSingles.core) {
		lines.push(`\t\t${safeKey(file.key)}: ${file.varName} as any,`);
	}

	// Plugin singles (sidebar, dashboard, branding, adminLocale, etc.)
	for (const file of coreSingles.plugin) {
		lines.push(`\t\t${safeKey(file.key)}: ${file.varName} as any,`);
	}

	// Spread singles (sidebar, dashboard — mergeStrategy: "spread")
	// Each stateKey maps to an array of files spread into one array.
	for (const [stateKey, files] of discovered.spreads) {
		if (files.length > 0) {
			const spread = files
				.map((f) => `...(${f.varName} as any ?? [])`)
				.join(", ");
			lines.push(`\t\t${safeKey(stateKey)}: [${spread}],`);
		}
	}

	// Extra entities from plugins
	if (extraEntities) {
		for (const [key, value] of extraEntities) {
			lines.push(`\t\t${safeKey(key)}: ${value},`);
		}
	}

	lines.push("\t},");
	lines.push("\t_runtime,");
	lines.push(") as unknown as _AppInternal;");
	lines.push("");
}

// ============================================================================
// Category metadata helpers
// ============================================================================

/**
 * Build a Map of category declarations from the resolved target's merged categories.
 */
function collectCategoryDeclarations(
	categories?: Record<string, CategoryDeclaration>,
): Map<string, CategoryDeclaration> {
	const result = new Map<string, CategoryDeclaration>();
	if (!categories) return result;
	for (const [name, decl] of Object.entries(categories)) {
		result.set(name, decl);
	}
	return result;
}

function capitalize(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Derive the App type name for a category.
 * Uses createAppKey if set, otherwise uses the category name.
 * e.g., "collections" → "AppCollections", "emails" (createAppKey: "emailTemplates") → "AppEmailTemplates"
 */
function deriveAppTypeName(
	catName: string,
	decl?: CategoryDeclaration,
): string {
	const key = decl?.createAppKey ?? catName;
	return `App${capitalize(key)}`;
}

/**
 * Derive the _Module type name for a category.
 * e.g., "collections" → "_ModuleCollections"
 */
function deriveModuleTypeName(catName: string): string {
	return `_Module${capitalize(catName)}`;
}

/**
 * Generate a section comment with consistent formatting.
 */
function sectionComment(label: string): string {
	const base = `// ── ${label} `;
	const dashes = "─".repeat(Math.max(0, 62 - base.length));
	return base + dashes;
}

// ============================================================================
// Singles categorization
// ============================================================================

/**
 * Well-known core single file keys.
 * Determined from corePlugin().discover patterns.
 * Used to separate "Core Singles" from "Plugin Singles" in generated comments.
 */
function getCoreSingleKeys(
	allDecls: Map<string, CategoryDeclaration>,
): Set<string> {
	// Core singles are those discovered by any plugin that also declares categories.
	// In practice, this is the core plugin which declares modules, locale, hooks, etc.
	// We use a simple heuristic: keys that match well-known core patterns.
	return new Set([
		"modules",
		"auth",
		"locale",
		"hooks",
		"defaultAccess",
		"contextResolver",
	]);
}

interface CategorizedSingles {
	/** Core singles (locale, hooks, access, context) — NOT modules. */
	core: DiscoveredFile[];
	/** Plugin-discovered singles (sidebar, dashboard, branding, adminLocale, etc.). */
	plugin: DiscoveredFile[];
}

/**
 * Categorize singles into core (always available) and plugin-discovered.
 * Excludes "modules" since that's handled separately.
 */
function getCategorizedSingles(
	singles: Map<string, DiscoveredFile>,
	allDecls: Map<string, CategoryDeclaration>,
): CategorizedSingles {
	const coreSingleKeys = getCoreSingleKeys(allDecls);
	const core: DiscoveredFile[] = [];
	const plugin: DiscoveredFile[] = [];

	for (const [key, file] of singles) {
		if (key === "modules") continue; // handled separately
		if (coreSingleKeys.has(key)) {
			core.push(file);
		} else {
			plugin.push(file);
		}
	}

	// Sort for deterministic output
	core.sort((a, b) => a.key.localeCompare(b.key));
	plugin.sort((a, b) => a.key.localeCompare(b.key));

	return { core, plugin };
}

// ============================================================================
// Type interface emission helper
// ============================================================================

/**
 * Emit a type interface or type alias for a category (collections, globals, etc.).
 * When user has entities, emits `export type X = _ModuleX & { ... }`.
 * Otherwise emits `export type X = _ModuleX;`.
 */
function emitTypeInterface(
	lines: string[],
	typeName: string,
	moduleTypeName: string,
	fileMap: Map<string, DiscoveredFile>,
): void {
	const label = typeName.replace(/^App/, "").toLowerCase();
	const hasUser = fileMap.size > 0;
	lines.push(`/** All ${label} in the app (modules + user, user overrides) */`);
	if (hasUser) {
		lines.push(`export type ${typeName} = ${moduleTypeName} & {`);
		for (const file of sortedValues(fileMap)) {
			lines.push(`\t${safeKey(file.key)}: typeof ${file.varName};`);
		}
		lines.push("};");
	} else {
		lines.push(`export type ${typeName} = ${moduleTypeName};`);
	}
	lines.push("");
}

// ============================================================================
// Nested functions builder
// ============================================================================

type NestedNode =
	| { type: "leaf"; varName: string }
	| { type: "branch"; children: Map<string, NestedNode> };

/**
 * Build a nested tree from dot-separated function keys.
 * "search" → { search: leaf }
 * "admin.stats" → { admin: { stats: leaf } }
 */
function buildNestedFunctions(
	functions: Map<string, DiscoveredFile>,
): Map<string, NestedNode> {
	const root = new Map<string, NestedNode>();

	for (const file of functions.values()) {
		const segments = file.key.split(".");
		let current = root;

		for (let i = 0; i < segments.length; i++) {
			const seg = segments[i];
			const isLast = i === segments.length - 1;

			if (isLast) {
				current.set(seg, { type: "leaf", varName: file.varName });
			} else {
				let node = current.get(seg);
				if (!node || node.type === "leaf") {
					node = { type: "branch", children: new Map() };
					current.set(seg, node);
				}
				current = (node as Extract<NestedNode, { type: "branch" }>).children;
			}
		}
	}

	return root;
}

/**
 * Emit a nested object structure as runtime code lines.
 */
function emitNestedObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: ${node.varName},`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedObject(lines, node.children, indent + 1);
			lines.push(`${tabs}},`);
		}
	}
}

/**
 * Emit a nested type structure for interface declarations.
 */
function emitNestedTypeObject(
	lines: string[],
	tree: Map<string, NestedNode>,
	indent: number,
): void {
	const tabs = "\t".repeat(indent);
	for (const [key, node] of tree) {
		if (node.type === "leaf") {
			lines.push(`${tabs}${safeKey(key)}: typeof ${node.varName};`);
		} else {
			lines.push(`${tabs}${safeKey(key)}: {`);
			emitNestedTypeObject(lines, node.children, indent + 1);
			lines.push(`${tabs}};`);
		}
	}
}

// ============================================================================
// Utilities
// ============================================================================

/**
 * Sort discovered files by key for deterministic output.
 */
function sortedValues(map: Map<string, DiscoveredFile>): DiscoveredFile[] {
	return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
}

/**
 * Generate the import statement for a discovered file.
 * Uses default import for "default" exports, named import for "named" exports.
 */
function importStatement(file: DiscoveredFile): string {
	if (file.exportType === "named" && file.namedExportName) {
		return `import { ${file.namedExportName} as ${file.varName} } from "${file.importPath}";`;
	}
	// default or unknown — use default import
	return `import ${file.varName} from "${file.importPath}";`;
}

/**
 * Quote a key if it's not a valid identifier.
 */
function safeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return `"${key}"`;
}

/**
 * Collect all factory export names from the resolved target.
 * Always includes "collection" and "global", plus any singleton factories.
 */
function getFactoryNames(
	singletonFactories?: Record<string, SingletonFactory>,
): string[] {
	const names = new Set(["collection", "global"]);
	if (singletonFactories) {
		for (const name of Object.keys(singletonFactories)) {
			names.add(name);
		}
	}
	return [...names].sort();
}

/**
 * Collect singleton discover patterns with ~-prefixed registryKeys.
 * These need centralized augmentation in the root template (not per-module)
 * to avoid TypeScript merge conflicts when multiple modules contribute.
 */
function collectTildeRegistryKeys(
	discoverPatterns: Record<string, DiscoverPattern> | undefined,
	singles: Map<string, DiscoveredFile>,
): Array<{ singleName: string; registryKey: string }> {
	if (!discoverPatterns) return [];
	const result: Array<{ singleName: string; registryKey: string }> = [];
	for (const [name, pattern] of Object.entries(discoverPatterns)) {
		if (typeof pattern !== "object" || !pattern.registryKey) continue;
		if (!pattern.registryKey.startsWith("~")) continue;
		// Only include if at least modules exist (which provide the fields).
		// The user may also have a fields.ts — handled by the type emission.
		result.push({ singleName: name, registryKey: pattern.registryKey });
	}
	return result.sort((a, b) => a.singleName.localeCompare(b.singleName));
}
