/**
 * Server-Side Type Definitions for Admin Package
 *
 * Type definitions for admin-specific features added to CollectionBuilder
 * and GlobalBuilder via codegen-generated factories (`.admin()`, `.list()`, `.form()`).
 *
 * @example
 * ```ts
 * // collections/posts.ts (file convention)
 * import { collection } from "#questpie/factories";
 *
 * export const posts = collection("posts")
 *   .fields(({ f }) => ({
 *     title: f.text({ required: true }),
 *   }))
 *   .admin(({ c }) => ({
 *     label: { en: "Posts" },
 *     icon: c.icon("ph:article"),
 *   }))
 *   .list(({ v, f }) => v.table({
 *     columns: [f.title],
 *   }))
 *   .form(({ v, f }) => v.form({
 *     fields: [f.title],
 *   }));
 * ```
 */

import type { AppContext } from "questpie";
import type { I18nText } from "questpie/shared";
import type { AnyBlockBuilder } from "./block/index.js";

// ============================================================================
// Admin Locale Configuration
// ============================================================================

/**
 * Admin locale configuration for UI language support.
 * Separate from content locales - UI can have different languages than content.
 *
 * @example
 * ```ts
 * .adminLocale({
 *   locales: ["en", "sk"],  // UI available in 2 languages
 *   defaultLocale: "en",
 * })
 * ```
 */
export interface AdminLocaleConfig {
	/** Available UI locales for admin interface */
	locales: string[];
	/** Default UI locale */
	defaultLocale: string;
}

// ============================================================================
// Admin Configuration Types
// ============================================================================

/**
 * Reference to a server-registered component.
 * Used for icons, badges, and other UI elements defined on server.
 *
 * @example
 * ```ts
 * { type: "icon", props: { name: "ph:users" } }
 * ```
 */
export interface ComponentReference<
	TType extends string = string,
	TProps extends Record<string, unknown> = Record<string, unknown>,
> {
	type: TType;
	props: TProps;
}

/**
 * Icon component reference with typed props.
 */
type IconReference = ComponentReference<"icon", { name: string }>;

/**
 * Badge component reference with typed props.
 */
type BadgeReference = ComponentReference<
	"badge",
	{ text: string; color?: string }
>;

// ============================================================================
// Component Type Registry — Plugin-Extensible
// ============================================================================

/**
 * Open augmentation point for component type names.
 * Codegen augments this interface from module-contributed component maps,
 * so user code gets autocomplete for valid component type names.
 *
 * When no modules are loaded (empty registry), `ComponentType` falls back to `string`.
 *
 * @example
 * ```ts
 * // Generated by codegen:
 * declare module "@questpie/admin/server" {
 *   interface ComponentTypeRegistry extends Record<_ComponentsNames_Strict, {}> {}
 * }
 *
 * // Third-party plugin can extend:
 * declare module "@questpie/admin/server" {
 *   interface ComponentTypeRegistry {
 *     avatar: {};
 *     statusBadge: {};
 *   }
 * }
 * ```
 */
// biome-ignore lint/suspicious/noEmptyInterface: Designed to be augmented via declaration merging
export interface ComponentTypeRegistry {}

/**
 * Union of all registered component type names.
 * Falls back to `string` when no types are registered (empty ComponentTypeRegistry).
 */
export type ComponentType = [keyof ComponentTypeRegistry] extends [never]
	? string
	: keyof ComponentTypeRegistry;

// ============================================================================
// View Kind Registry — Plugin-Extensible
// ============================================================================

/**
 * Open augmentation point for view kinds.
 * Plugins extend this interface to register new view kinds.
 *
 * The admin plugin registers "list" and "form" by default.
 * Third-party plugins can add new kinds (e.g., "dashboard", "kanban-board").
 *
 * @example
 * ```ts
 * // Admin plugin declares:
 * declare module "@questpie/admin/server" {
 *   interface ViewKindRegistry {
 *     list: {};
 *     edit: {};
 *   }
 * }
 *
 * // Third-party plugin extends:
 * declare module "@questpie/admin/server" {
 *   interface ViewKindRegistry {
 *     dashboard: {};
 *   }
 * }
 * ```
 */
export interface ViewKindRegistry {
	list: {};
	form: {};
}

/**
 * Union of all registered view kind names.
 * Derived from ViewKindRegistry — automatically extends when plugins
 * augment the registry.
 */
export type ViewKind = keyof ViewKindRegistry;

// ============================================================================
// View Definition — Unified
// ============================================================================

/**
 * Unified view definition with `kind` discriminant.
 *
 * The `kind` field determines which builder extension this view is used in:
 * - `"list"` → available in `.list()` callback
 * - `"form"` → available in `.form()` callback
 *
 * Each view carries its own config — codegen extracts the type and
 * introspection serializes the schema for the client.
 */
export interface ViewDefinition<
	TName extends string = string,
	TKind extends ViewKind = ViewKind,
	TConfig = unknown,
> {
	type: "view";
	name: TName;
	kind: TKind;
	/**
	 * Phantom type marker carrying the view's config type.
	 *
	 * Not used at runtime — only exists for TypeScript to extract
	 * per-view config in `ListViewFactory` / `EditViewFactory`.
	 * When a user calls `v.table({ columns: [...] })`, TypeScript
	 * infers the config shape from this phantom field.
	 *
	 * @example
	 * ```ts
	 * // views/kanban.ts
	 * export default view<KanbanConfig>("kanban", { kind: "list" });
	 * // → ViewDefinition<"kanban", "list", KanbanConfig>
	 * // → v.kanban({ groupBy: "status" }) type-checks against KanbanConfig
	 * ```
	 */
	readonly "~config"?: TConfig;
	[key: string]: unknown;
}

/**
 * View definition for list views (table, cards, etc.)
 * @deprecated Use ViewDefinition with kind: "list" instead.
 */
export interface ListViewDefinition<TName extends string = string> {
	type: "listView";
	name: TName;
}

/**
 * View definition for edit views (form, wizard, etc.)
 * @deprecated Use ViewDefinition with kind: "form" instead.
 */
export interface EditViewDefinition<TName extends string = string> {
	type: "editView";
	name: TName;
}

/**
 * Component definition for reusable UI components.
 *
 * The `TProps` phantom type carries the input props type that
 * `c.myComponent(props)` accepts in `.admin()` callbacks.
 * When omitted, falls back to `Record<string, unknown> | string`.
 *
 * @example
 * ```ts
 * // components/icon.ts
 * export default component<string | { name: string }>("icon");
 * // → c.icon("ph:users") type-checks against string | { name: string }
 *
 * // components/rating.ts
 * interface RatingProps { value: number; max?: number }
 * export default component<RatingProps>("rating");
 * // → c.rating({ value: 4, max: 5 }) type-checks against RatingProps
 * ```
 */
export interface ComponentDefinition<
	TName extends string = string,
	TProps = unknown,
> {
	type: "component";
	name: TName;
	/** Phantom type marker carrying the component's input props type. */
	readonly "~props"?: TProps;
}

/**
 * Extract the input props type from a ComponentDefinition.
 * Falls back to `TFallback` when the component has `unknown` props.
 */
type ExtractComponentProps<
	TComponent,
	TFallback = Record<string, unknown> | string,
> = TComponent extends ComponentDefinition<any, infer P>
	? unknown extends P
		? TFallback
		: P
	: TFallback;

/**
 * Normalize component input props to output props for ComponentReference.
 * Handles string shorthand: `string | X` → just `X` (the string is
 * normalized to the object form at runtime by the proxy).
 */
type NormalizeComponentOutput<TProps> = TProps extends string
	? Record<string, unknown>
	: Exclude<TProps, string>;

/**
 * Component factory API generated from registered components.
 *
 * Each key is a callable that accepts the **per-component props type** extracted
 * from the ComponentDefinition's `~props` phantom field.
 *
 * Accepts either a components record (per-component typed props) or a string
 * union (fallback: all components use `Record<string, unknown> | string`).
 *
 * Note: `c.icon("ph:users")` string shorthand is supported when the component
 * definition includes `string` in its props union.
 */
export type ComponentFactory<
	TComponents extends Record<string, any> | string = string,
> =
	TComponents extends Record<string, any>
		? {
				[K in keyof TComponents & string]: (
					props: ExtractComponentProps<TComponents[K]>,
				) => ComponentReference<
					K,
					NormalizeComponentOutput<
						ExtractComponentProps<TComponents[K]>
					> extends Record<string, unknown>
						? NormalizeComponentOutput<ExtractComponentProps<TComponents[K]>>
						: Record<string, unknown>
				>;
			}
		: {
				[K in TComponents & string]: (
					props: Record<string, unknown> | string,
				) => ComponentReference<K, Record<string, unknown>>;
			};

// ============================================================================
// Collection Admin Configuration
// ============================================================================

/**
 * Admin metadata for a collection.
 * Defines how the collection appears in the admin sidebar and UI.
 */
export interface AdminCollectionConfig {
	/** Display label for the collection */
	label?: I18nText;
	/** Description shown in tooltips/help text */
	description?: I18nText;
	/** Icon reference (resolved by client's icon component) */
	icon?: ComponentReference;
	/** Hide from admin sidebar */
	hidden?: boolean;
	/** Group in sidebar */
	group?: string;
	/** Order within group */
	order?: number;
	/**
	 * Whether this collection should be included in audit logging.
	 * Requires the audit module to be registered via `runtimeConfig({ modules: [auditModule] })`.
	 *
	 * - `true` or `undefined` (default): audited when audit module is active
	 * - `false`: never audited, even when audit module is active
	 */
	audit?: boolean;
}

/**
 * Block category configuration.
 * Defines how blocks are grouped in the block picker.
 */
export interface BlockCategoryConfig {
	/** Display label for the category */
	label: I18nText;
	/** Icon for the category */
	icon?: ComponentReference;
	/** Order in block picker (lower = first) */
	order?: number;
}

/**
 * Admin metadata for a block.
 * Defines how the block appears in the block picker and editor.
 *
 * @example
 * ```ts
 * block("hero")
 *   .admin(({ c }) => ({
 *     label: { en: "Hero Section", sk: "Hero sekcia" },
 *     icon: c.icon("ph:image"),
 *     category: {
 *       label: { en: "Sections", sk: "Sekcie" },
 *       icon: c.icon("ph:layout"),
 *     },
 *   }))
 * ```
 */
export interface AdminBlockConfig {
	/** Display label for the block */
	label?: I18nText;
	/** Description shown in tooltips/help text */
	description?: I18nText;
	/** Icon reference (resolved by client's icon component) */
	icon?: ComponentReference;
	/** Category for grouping in block picker */
	category?: BlockCategoryConfig;
	/** Order within category in block picker (lower = first) */
	order?: number;
	/** Hide from block picker (useful for deprecated blocks) */
	hidden?: boolean;
}

/**
 * List view configuration for a collection.
 * Defines columns, sorting, filtering, and actions.
 */
export interface ListViewConfig {
	/** View type to use (e.g., "table", "cards") */
	view?: string;
	/** Columns to display */
	columns?: string[];
	/** Default sort configuration */
	defaultSort?: { field: string; direction: "asc" | "desc" };
	/** Searchable fields */
	searchable?: string[];
	/** Filterable fields */
	filterable?: string[];
	/** Actions configuration */
	actions?: {
		header?: { primary?: ActionReference[]; secondary?: ActionReference[] };
		row?: ActionReference[];
		bulk?: ActionReference[];
	};
}

// ============================================================================
// Form View Layout Types
// ============================================================================

/**
 * Context passed to form reactive handlers.
 */
export interface FormReactiveContext<TData = Record<string, unknown>> {
	data: TData;
	sibling: Record<string, unknown>;
	ctx: {
		db: any;
		user?: any;
		locale?: string;
	};
	prev?: {
		data: TData;
		sibling: Record<string, unknown>;
	};
}

/**
 * Reactive config for field-level form behavior.
 */
export type FormReactiveConfig<TData = any, TReturn = any> =
	| ((ctx: FormReactiveContext<TData>) => TReturn | Promise<TReturn>)
	| {
			handler: (ctx: FormReactiveContext<TData>) => TReturn | Promise<TReturn>;
			deps?: string[] | ((ctx: FormReactiveContext<TData>) => any[]);
			debounce?: number;
	  }
	| {
			deps: string[];
			debounce?: number;
	  };

/**
 * Section layout for form views.
 * Groups fields with optional visual wrapper and layout mode.
 *
 * @example
 * ```ts
 * {
 *   type: "section",
 *   label: { en: "Contact Information" },
 *   layout: "grid",
 *   columns: 2,
 *   fields: [f.name, f.email, f.phone],
 * }
 * ```
 */
export interface FormSectionLayout {
	type: "section";
	/** Section label */
	label?: I18nText;
	/** Section description */
	description?: I18nText;
	/** Visual wrapper mode */
	wrapper?: "flat" | "collapsible";
	/** Default collapsed state (for collapsible wrapper) */
	defaultCollapsed?: boolean;
	/** Field arrangement mode */
	layout?: "stack" | "inline" | "grid";
	/** Number of columns (for grid layout) */
	columns?: number;
	/** Custom gap (in quarter rems) */
	gap?: number;
	/** Fields in this section */
	fields: FieldLayoutItem[];
	/** Conditional visibility */
	hidden?: boolean;
	/** Custom CSS class */
	className?: string;
}

/**
 * Tab configuration for tabbed form views.
 */
export interface FormTabConfig {
	/** Unique tab identifier */
	id: string;
	/** Tab label */
	label: I18nText;
	/** Tab icon */
	icon?: ComponentReference;
	/** Fields in this tab */
	fields: FieldLayoutItem[];
	/** Conditional visibility */
	hidden?: boolean;
}

/**
 * Tabs layout for form views.
 *
 * @example
 * ```ts
 * {
 *   type: "tabs",
 *   tabs: [
 *     { id: "basic", label: { en: "Basic" }, fields: [f.name, f.email] },
 *     { id: "advanced", label: { en: "Advanced" }, fields: [f.settings] },
 *   ],
 * }
 * ```
 */
export interface FormTabsLayout {
	type: "tabs";
	tabs: FormTabConfig[];
}

/**
 * Field entry with optional reactive form behavior.
 */
export interface FormFieldLayoutItem<TData = any> {
	field: string;
	className?: string;
	hidden?: boolean | FormReactiveConfig<TData, boolean>;
	readOnly?: boolean | FormReactiveConfig<TData, boolean>;
	disabled?: boolean | FormReactiveConfig<TData, boolean>;
	compute?: FormReactiveConfig<TData, any>;
}

/**
 * Field layout item - union of field reference or layout container.
 *
 * Can be:
 * - Field name string: `f.name`
 * - Field with className: `{ field: "name", className: "col-span-2" }`
 * - Section layout: `{ type: "section", ... }`
 * - Tabs layout: `{ type: "tabs", ... }`
 */
export type FieldLayoutItem =
	| string
	| FormFieldLayoutItem
	| FormSectionLayout
	| FormTabsLayout;

/**
 * Form sidebar configuration.
 * Places fields in a fixed sidebar alongside the main content.
 *
 * @example
 * ```ts
 * sidebar: {
 *   position: "right",
 *   fields: [f.isActive, f.avatar],
 * }
 * ```
 */
export interface FormSidebarConfig {
	/** Sidebar position (default: "right") */
	position?: "left" | "right";
	/** Fields in the sidebar */
	fields: FieldLayoutItem[];
}

/**
 * Form view configuration for a collection.
 * Defines field layout with sections, tabs, and optional sidebar.
 *
 * @example
 * ```ts
 * v.form({
 *   sidebar: { position: "right", fields: [f.status] },
 *   fields: [
 *     { type: "section", label: { en: "Details" }, layout: "grid", columns: 2, fields: [f.name, f.email] },
 *     { type: "section", label: { en: "Content" }, fields: [f.body] },
 *   ],
 * })
 * ```
 */
export interface FormViewConfig {
	/** View type to use (e.g., "form", "wizard") */
	view?: string;
	/** Main content fields */
	fields: FieldLayoutItem[];
	/** Sidebar configuration */
	sidebar?: FormSidebarConfig;
}

/**
 * Preview configuration for a collection.
 * Enables live preview of content.
 */
export interface PreviewConfig {
	/** Enable preview panel */
	enabled?: boolean;
	/** Preview URL builder (runs on server) */
	url?: (ctx: { record: Record<string, unknown>; locale?: string }) => string;
	/** Preview panel position */
	position?: "left" | "right" | "bottom";
	/** Default panel width (percentage) */
	defaultWidth?: number;
}

/**
 * Reference to an action
 */
export type ActionReference = string | { type: string; config?: unknown };

// ============================================================================
// Global Admin Configuration
// ============================================================================

/**
 * Admin metadata for a global.
 */
export interface AdminGlobalConfig {
	/** Display label */
	label?: I18nText;
	/** Description */
	description?: I18nText;
	/** Icon reference */
	icon?: ComponentReference;
	/** Hide from admin */
	hidden?: boolean;
	/** Group in sidebar */
	group?: string;
	/** Order within group */
	order?: number;
	/**
	 * Whether this global should be included in audit logging.
	 * @see AdminCollectionConfig.audit
	 */
	audit?: boolean;
}

// ============================================================================
// Server-Side Dashboard Configuration
// ============================================================================

/**
 * Context available to widget loader and access functions on the server.
 * Provides typed access to collections, globals, and infrastructure.
 */
export interface WidgetFetchContext extends AppContext {
	/** Database handle — populated at runtime by extractAppServices */
	db: unknown;
	/** Collection APIs — populated at runtime by extractAppServices */
	collections: Record<string, any>;
	/** Global APIs — populated at runtime by extractAppServices */
	globals: Record<string, any>;
}

/**
 * Per-widget access rule. Can be a boolean or async function.
 * - `true` or `undefined`: always visible
 * - `false`: always hidden
 * - function: evaluated at request time
 */
export type WidgetAccessRule =
	| boolean
	| ((ctx: WidgetFetchContext) => boolean | Promise<boolean>);

/**
 * Server-side dashboard widget configuration.
 * These are serializable and can be sent via introspection API.
 */
export type ServerDashboardWidget =
	| ServerStatsWidget
	| ServerChartWidget
	| ServerRecentItemsWidget
	| ServerQuickActionsWidget
	| ServerCustomWidget
	| ServerValueWidget
	| ServerTableWidget
	| ServerTimelineWidget
	| ServerProgressWidget;

/**
 * Stats widget - shows count from a collection
 */
export interface ServerStatsWidget {
	type: "stats";
	/** Unique widget ID */
	id?: string;
	/** Widget label */
	label?: I18nText;
	/** Icon reference */
	icon?: ComponentReference;
	/** Collection to count */
	collection: string;
	/** Filter to apply */
	filter?: Record<string, unknown>;
	/** Grid span (1-4) */
	span?: number;
	/** Optional server-side data loader (overrides collection count) */
	loader?: (ctx: WidgetFetchContext) => Promise<{ count: number }>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Chart widget - shows data over time
 */
export interface ServerChartWidget {
	type: "chart";
	/** Unique widget ID */
	id?: string;
	/** Widget label */
	label?: I18nText;
	/** Chart type */
	chartType: "line" | "bar" | "area" | "pie";
	/** Collection to query */
	collection: string;
	/** Date field for time series */
	dateField?: string;
	/** Field to aggregate by (for pie charts, etc.) */
	field?: string;
	/** Time range */
	timeRange?: "7d" | "30d" | "90d" | "1y";
	/** Filter to apply */
	filter?: Record<string, unknown>;
	/** Grid span (1-4) */
	span?: number;
	/** Optional server-side data loader (overrides collection query) */
	loader?: (
		ctx: WidgetFetchContext,
	) => Promise<Array<{ name: string; value: number }>>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Recent items widget - shows latest items from a collection
 */
export interface ServerRecentItemsWidget {
	type: "recentItems";
	/** Unique widget ID */
	id?: string;
	/** Widget label */
	label?: I18nText;
	/** Collection to query */
	collection: string;
	/** Date field for ordering */
	dateField: string;
	/** Number of items to show */
	limit?: number;
	/** Filter to apply */
	filter?: Record<string, unknown>;
	/** Grid span (1-4) */
	span?: number;
	/** Optional server-side data loader */
	loader?: (ctx: WidgetFetchContext) => Promise<unknown>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Quick actions widget - shows action buttons
 */
export interface ServerQuickActionsWidget {
	type: "quickActions";
	/** Unique widget ID */
	id?: string;
	/** Widget label */
	label?: I18nText;
	/** Actions to display */
	actions: ServerQuickAction[];
	/** Grid span (1-4) */
	span?: number;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Quick action definition
 */
export interface ServerQuickAction {
	/** Action label */
	label: I18nText;
	/** Action icon */
	icon?: ComponentReference;
	/** Action to perform */
	action:
		| { type: "create"; collection: string }
		| { type: "link"; href: string; external?: boolean }
		| { type: "page"; pageId: string };
}

/**
 * Custom widget - rendered by client component
 */
export interface ServerCustomWidget {
	type: "custom";
	/** Unique widget ID (required for custom) */
	id: string;
	/** Widget label */
	label?: I18nText;
	/** Custom widget type name (resolved by client registry) */
	widgetType: string;
	/** Widget props (passed to client component) */
	props?: Record<string, unknown>;
	/** Grid span (1-4) */
	span?: number;
	/** Optional server-side data loader */
	loader?: (ctx: WidgetFetchContext) => Promise<unknown>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Value widget - displays a single metric with optional trend
 */
export interface ServerValueWidget {
	type: "value";
	/** Unique widget ID */
	id: string;
	/** Widget label */
	label?: I18nText;
	/** Icon reference */
	icon?: ComponentReference;
	/** Grid span (1-4) */
	span?: number;
	/** Auto-refresh interval in milliseconds */
	refreshInterval?: number;
	/** Server-side data loader (required) */
	loader: (ctx: WidgetFetchContext) => Promise<{
		value: number | string;
		formatted?: string;
		label?: I18nText | string;
		subtitle?: I18nText | string;
		footer?: I18nText | string;
		icon?: ComponentReference;
		trend?: { value: string; icon?: ComponentReference };
		classNames?: Record<string, string>;
	}>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Table widget - displays a mini table from a collection
 */
export interface ServerTableWidget {
	type: "table";
	/** Unique widget ID */
	id: string;
	/** Widget label */
	label?: I18nText;
	/** Collection to fetch from */
	collection: string;
	/** Columns to display */
	columns: Array<string | { key: string; label?: I18nText }>;
	/** Number of rows */
	limit?: number;
	/** Sort field */
	sortBy?: string;
	/** Sort direction */
	sortOrder?: "asc" | "desc";
	/** Filter */
	filter?: Record<string, unknown>;
	/** Grid span (1-4) */
	span?: number;
	/** Optional server-side data loader */
	loader?: (ctx: WidgetFetchContext) => Promise<unknown>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Timeline widget - displays activity/event timeline
 */
export interface ServerTimelineWidget {
	type: "timeline";
	/** Unique widget ID */
	id: string;
	/** Widget label */
	label?: I18nText;
	/** Max items to show */
	maxItems?: number;
	/** Show timestamps */
	showTimestamps?: boolean;
	/** Timestamp format */
	timestampFormat?: "relative" | "absolute" | "datetime";
	/** Empty state message */
	emptyMessage?: I18nText;
	/** Grid span (1-4) */
	span?: number;
	/** Server-side data loader (required) */
	loader: (ctx: WidgetFetchContext) => Promise<
		Array<{
			id: string;
			title: string;
			description?: string;
			timestamp: Date | string;
			icon?: ComponentReference;
			variant?: "default" | "success" | "warning" | "error" | "info";
			href?: string;
		}>
	>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Progress widget - displays progress towards a goal
 */
export interface ServerProgressWidget {
	type: "progress";
	/** Unique widget ID */
	id: string;
	/** Widget label */
	label?: I18nText;
	/** Progress bar color */
	color?: string;
	/** Show percentage */
	showPercentage?: boolean;
	/** Grid span (1-4) */
	span?: number;
	/** Server-side data loader (required) */
	loader: (ctx: WidgetFetchContext) => Promise<{
		current: number;
		target: number;
		label?: string;
		subtitle?: string;
	}>;
	/** Per-widget access rule */
	access?: WidgetAccessRule;
}

/**
 * Dashboard section - groups widgets
 */
export interface ServerDashboardSection {
	type: "section";
	/** Section label */
	label?: I18nText;
	/** Section description */
	description?: I18nText;
	/** Section icon */
	icon?: ComponentReference;
	/** Layout mode */
	layout?: "grid" | "stack";
	/** Grid columns */
	columns?: number;
	/** Wrapper style */
	wrapper?: "flat" | "card" | "collapsible";
	/** Default collapsed (for collapsible) */
	defaultCollapsed?: boolean;
	/** Section items */
	items: ServerDashboardItem[];
}

/**
 * Dashboard tabs - tabbed sections
 */
export interface ServerDashboardTabs {
	type: "tabs";
	/** Tabs configuration */
	tabs: ServerDashboardTab[];
	/** Default active tab ID */
	defaultTab?: string;
}

/**
 * Single tab configuration
 */
export interface ServerDashboardTab {
	/** Tab ID */
	id: string;
	/** Tab label */
	label: I18nText;
	/** Tab icon */
	icon?: ComponentReference;
	/** Tab items */
	items: ServerDashboardItem[];
}

/**
 * Dashboard layout item
 */
export type ServerDashboardItem =
	| ServerDashboardWidget
	| ServerDashboardSection
	| ServerDashboardTabs;

/**
 * Dashboard header action shown beside title/description.
 */
export interface ServerDashboardAction {
	/** Unique action ID */
	id: string;
	/** Action label */
	label: I18nText;
	/** Action icon */
	icon?: ComponentReference;
	/** Action URL */
	href: string;
	/** Visual variant */
	variant?: "default" | "primary" | "secondary" | "outline" | "ghost";
}

/**
 * Server-side dashboard configuration
 */
export interface ServerDashboardConfig {
	/** Dashboard title */
	title?: I18nText;
	/** Dashboard description */
	description?: I18nText;
	/** Header actions */
	actions?: ServerDashboardAction[];
	/** Grid columns (default: 4) */
	columns?: number;
	/** Gap between widgets */
	gap?: number;
	/** Dashboard items */
	items?: ServerDashboardItem[];
	/** Enable realtime invalidation for dashboard widgets by default */
	realtime?: boolean;
	/** Auto-refresh interval in milliseconds */
	refreshInterval?: number;
}

// ============================================================================
// Server-Side Branding Configuration
// ============================================================================

/**
 * Branding configuration for the admin panel.
 */
export interface ServerBrandingConfig {
	/** Admin panel name */
	name?: I18nText;
	/** Logo configuration */
	logo?: unknown;
}

// ============================================================================
// Server-Side Sidebar Configuration
// ============================================================================

/**
 * Server-side sidebar item types
 */
export type ServerSidebarItem =
	| ServerSidebarCollectionItem
	| ServerSidebarGlobalItem
	| ServerSidebarPageItem
	| ServerSidebarLinkItem
	| ServerSidebarDividerItem;

/**
 * Collection item in sidebar
 */
export interface ServerSidebarCollectionItem {
	type: "collection";
	/** Collection name (validated against registered collections) */
	collection: string;
	/** Override display label */
	label?: I18nText;
	/** Override icon */
	icon?: ComponentReference;
}

/**
 * Global item in sidebar
 */
export interface ServerSidebarGlobalItem {
	type: "global";
	/** Global name (validated against registered globals) */
	global: string;
	/** Override display label */
	label?: I18nText;
	/** Override icon */
	icon?: ComponentReference;
}

/**
 * Custom page item in sidebar
 */
export interface ServerSidebarPageItem {
	type: "page";
	/** Page ID (resolved by client) */
	pageId: string;
	/** Display label */
	label?: I18nText;
	/** Icon */
	icon?: ComponentReference;
}

/**
 * External link item in sidebar
 */
export interface ServerSidebarLinkItem {
	type: "link";
	/** Display label */
	label: I18nText;
	/** Link URL */
	href: string;
	/** Icon */
	icon?: ComponentReference;
	/** Open in new tab */
	external?: boolean;
}

/**
 * Divider item in sidebar
 */
export interface ServerSidebarDividerItem {
	type: "divider";
}

/**
 * Sidebar section
 */
export interface ServerSidebarSection {
	/** Section ID (for targeting/extending) */
	id: string;
	/** Section title */
	title?: I18nText;
	/** Section icon */
	icon?: ComponentReference;
	/** Whether this section can be collapsed/expanded by the user */
	collapsible?: boolean;
	/** Section items */
	items?: ServerSidebarItem[];
	/** Nested subsections */
	sections?: ServerSidebarSection[];
}

/**
 * Server-side sidebar configuration (final merged output)
 */
export interface ServerSidebarConfig {
	/** Sidebar sections */
	sections: ServerSidebarSection[];
}

// ============================================================================
// Composable Sidebar/Dashboard Contributions (§5.8)
// ============================================================================

/**
 * Sidebar contribution — what a module or user config contributes.
 * Multiple contributions are merged by createApp() (§5.8.3).
 * Resolved from callback: `sidebar: ({ s, c }) => ({ sections: [...], items: [...] })`
 */
export interface SidebarContribution {
	/** Section definitions — merged by id across modules. Later wins for title/icon. */
	sections?: SidebarSectionDef[];
	/** Items — appended to sections by sectionId. Module resolution order. */
	items?: SidebarItemDef[];
}

/**
 * Sidebar section definition for contributions.
 */
export interface SidebarSectionDef {
	/** Unique section ID — used for targeting from other modules. */
	id: string;
	/** Section title. */
	title?: I18nText;
	/** Section icon. */
	icon?: ComponentReference;
	/** Whether section is collapsible. */
	collapsible?: boolean;
}

/**
 * Sidebar item definition for contributions.
 * Each item references a sectionId to indicate which section it belongs to.
 */
export interface SidebarItemDef extends Omit<ServerSidebarItem, "type"> {
	/** Which section this item belongs to. */
	sectionId: string;
	/** 'start' to prepend, default is 'end' (append). */
	position?: "start" | "end";
	/** Item type. */
	type: "collection" | "global" | "page" | "link" | "divider";
	/** Collection slug (when type = "collection"). */
	collection?: string;
	/** Global slug (when type = "global"). */
	global?: string;
	/** Page ID (when type = "page"). */
	pageId?: string;
	/** Display label (for links, overrides). */
	label?: I18nText;
	/** URL (for links). */
	href?: string;
	/** Icon reference. */
	icon?: ComponentReference;
	/** Open in new tab (for links). */
	external?: boolean;
}

/**
 * Dashboard contribution — what a module or user config contributes.
 * Multiple contributions are merged by createApp() (§5.8.3).
 * Resolved from callback: `dashboard: ({ d, c, a }) => ({ ... })`
 */
export interface DashboardContribution {
	/** Dashboard title — last module/user wins. */
	title?: I18nText;
	/** Dashboard description — last module/user wins. */
	description?: I18nText;
	/** Grid columns — last module/user wins. */
	columns?: number;
	/** Enable realtime — last module/user wins. */
	realtime?: boolean;

	/** Quick actions — concatenated from all modules. */
	actions?: ServerDashboardAction[];
	/** Section definitions — merged by id across modules. */
	sections?: DashboardSectionDef[];
	/** Widget items — appended to sections by sectionId. */
	items?: DashboardItemDef[];
}

/**
 * Dashboard section definition for contributions.
 */
export interface DashboardSectionDef {
	/** Unique section ID. */
	id: string;
	/** Section title. */
	label?: I18nText;
	/** Layout mode. */
	layout?: "grid";
	/** Grid columns for this section. */
	columns?: number;
}

/**
 * Dashboard item (widget) definition for contributions.
 * Each item references a sectionId to indicate which section it belongs to.
 */
export interface DashboardItemDef {
	/** Which section this item belongs to. */
	sectionId: string;
	/** 'start' to prepend, default is 'end' (append). */
	position?: "start" | "end";
	/** Unique widget ID. */
	id: string;
	/** Widget type. */
	type:
		| "stats"
		| "value"
		| "progress"
		| "chart"
		| "recentItems"
		| "timeline"
		| "table"
		| "custom";
	/** Display label. */
	label?: I18nText;
	/** Grid span (1-4). */
	span?: number;
	/** Refresh interval in ms. */
	refreshInterval?: number;
	/** Widget-specific config (collection, filter, loader, chartType, etc.) */
	[key: string]: unknown;
}

// ============================================================================
// Sidebar/Dashboard Proxy Types (for callbacks)
// ============================================================================

/**
 * Sidebar proxy — provided in sidebar callbacks as `s`.
 * Creates serializable contribution objects.
 */
export interface SidebarProxy {
	/** Define a sidebar section. */
	section(def: SidebarSectionDef): SidebarSectionDef;
	/** Define a sidebar item. */
	item(def: SidebarItemDef): SidebarItemDef;
}

/**
 * Dashboard proxy — provided in dashboard callbacks as `d`.
 * Creates serializable widget/section objects.
 */
export interface DashboardProxy {
	/** Define a dashboard section. */
	section(def: DashboardSectionDef): DashboardSectionDef;
	/** Stats widget — count docs from a collection. */
	stats(def: DashboardItemDef): DashboardItemDef;
	/** Value widget — custom value from async loader. */
	value(def: DashboardItemDef): DashboardItemDef;
	/** Progress widget — progress bar from async loader. */
	progress(def: DashboardItemDef): DashboardItemDef;
	/** Chart widget — aggregate a field into chart. */
	chart(def: DashboardItemDef): DashboardItemDef;
	/** Recent items widget — latest docs from a collection. */
	recentItems(def: DashboardItemDef): DashboardItemDef;
	/** Timeline widget — event stream from async loader. */
	timeline(def: DashboardItemDef): DashboardItemDef;
	/** Table widget — tabular data from async loader. */
	table(def: DashboardItemDef): DashboardItemDef;
	/** Custom widget — resolved by client. */
	custom(def: DashboardItemDef): DashboardItemDef;
}

/**
 * Dashboard action proxy — provided in dashboard callbacks as `a`.
 * Creates dashboard header action objects.
 */
export interface DashboardActionProxy {
	/** Create link for a collection. */
	create(
		config: Omit<ServerDashboardAction, "href"> & { collection: string },
	): ServerDashboardAction;
	/** Edit link for a global. */
	global(
		config: Omit<ServerDashboardAction, "href"> & { global: string },
	): ServerDashboardAction;
	/** Plain link. */
	link(config: ServerDashboardAction): ServerDashboardAction;
}

/**
 * Context for sidebar callbacks on module() and config().
 */
export interface SidebarCallbackContext {
	/** Sidebar builder proxy. */
	s: SidebarProxy;
	/** Component proxy (scoped to registered components). */
	c: ComponentFactory;
}

/**
 * Context for dashboard callbacks on module() and config().
 */
export interface DashboardCallbackContext {
	/** Dashboard builder proxy. */
	d: DashboardProxy;
	/** Component proxy (scoped to registered components). */
	c: ComponentFactory;
	/** Dashboard action proxy. */
	a: DashboardActionProxy;
}

/**
 * Sidebar callback type for module() and config().
 */
export type SidebarCallback = (
	ctx: SidebarCallbackContext,
) => SidebarContribution;

/**
 * Dashboard callback type for module() and config().
 */
export type DashboardCallback = (
	ctx: DashboardCallbackContext,
) => DashboardContribution;

// ============================================================================
// Server-Side Action System
// ============================================================================

/**
 * Action result types returned from action handlers.
 */
export type ServerActionResult =
	| ServerActionSuccess
	| ServerActionError
	| ServerActionRedirect
	| ServerActionDownload;

/**
 * Successful action result
 */
export interface ServerActionSuccess {
	type: "success";
	/** Toast notification to show */
	toast?: {
		message: string;
		title?: string;
	};
	/** Side effects to trigger */
	effects?: ServerActionEffects;
}

/**
 * Error action result
 */
export interface ServerActionError {
	type: "error";
	/** Toast notification to show */
	toast?: {
		message: string;
		title?: string;
	};
	/** Field-level errors */
	errors?: Record<string, string>;
}

/**
 * Redirect action result
 */
export interface ServerActionRedirect {
	type: "redirect";
	/** URL to redirect to */
	url: string;
	/** Open in new tab */
	external?: boolean;
}

/**
 * Download action result
 */
export interface ServerActionDownload {
	type: "download";
	/** File data */
	file: {
		name: string;
		content: string | Uint8Array;
		mimeType: string;
	};
}

/**
 * Action side effects
 */
export interface ServerActionEffects {
	/** Close the action modal */
	closeModal?: boolean;
	/** Invalidate queries (true = all, string[] = specific collections) */
	invalidate?: boolean | string[];
	/** Redirect after success */
	redirect?: string;
}

/**
 * Action handler context
 */
export interface ServerActionContext<TData = Record<string, unknown>> {
	/** Form data submitted */
	data: TData;
	/** Item ID (for single-item actions) */
	itemId?: string;
	/** Item IDs (for bulk actions) */
	itemIds?: string[];
	/** Auth instance (Better Auth API) */
	auth: any;
	/** Collection CRUD APIs */
	collections: any;
	/** Global CRUD APIs */
	globals: any;
	/** Database client */
	db: unknown;
	/** Current user session */
	session?: unknown;
	/** Current locale */
	locale?: string;
}

/**
 * Action handler function type
 */
export type ServerActionHandler<TData = Record<string, unknown>> = (
	ctx: ServerActionContext<TData>,
) => Promise<ServerActionResult> | ServerActionResult;

/**
 * Server-side action form field definition.
 * Can be either a field definition from the registry or a simple config object.
 */
export type ServerActionFormField =
	| ServerActionFormFieldConfig
	| ServerActionFormFieldDefinition;

/**
 * Simple field config for action forms (when not using field registry)
 */
export interface ServerActionFormFieldConfig {
	/** Field type */
	type: string;
	/** Field label */
	label?: I18nText;
	/** Field description */
	description?: I18nText;
	/** Whether field is required */
	required?: boolean;
	/** Default value */
	default?: unknown;
	/** Field-specific options */
	options?: unknown;
}

/**
 * Field definition from field registry (has getMetadata method)
 */
export interface ServerActionFormFieldDefinition {
	/** Field definition state */
	state: {
		type?: string;
		config?: {
			label?: I18nText;
			description?: I18nText;
			required?: boolean;
			[key: string]: unknown;
		};
		/** @deprecated Use state.config.label instead */
		label?: I18nText;
		/** @deprecated Use state.config.description instead */
		description?: I18nText;
		/** @deprecated Use state.config.required instead */
		required?: boolean;
	};
	/** Get metadata for introspection */
	getMetadata(): {
		type: string;
		label?: I18nText;
		description?: I18nText;
		required?: boolean;
	};
	/** Generate Zod schema for validation */
	toZodSchema(): unknown;
}

/**
 * Server-side action form configuration
 */
export interface ServerActionForm {
	/** Form dialog title */
	title: I18nText;
	/** Form dialog description */
	description?: I18nText;
	/** Form fields */
	fields: Record<string, ServerActionFormField>;
	/** Submit button label */
	submitLabel?: I18nText;
	/** Cancel button label */
	cancelLabel?: I18nText;
	/** Dialog width */
	width?: "sm" | "md" | "lg" | "xl";
}

/**
 * Server-side action definition
 */
export interface ServerActionDefinition<TData = Record<string, unknown>> {
	/** Unique action ID */
	id: string;
	/** Display label */
	label: I18nText;
	/** Action description */
	description?: I18nText;
	/** Icon reference */
	icon?: ComponentReference;
	/** Button variant */
	variant?: "default" | "destructive" | "outline" | "secondary" | "ghost";
	/** Where the action appears */
	scope?: "single" | "bulk" | "header" | "row";
	/** Form configuration (for actions with input) */
	form?: ServerActionForm;
	/** Confirmation dialog */
	confirmation?: {
		title: I18nText;
		description?: I18nText;
		confirmLabel?: I18nText;
		cancelLabel?: I18nText;
		destructive?: boolean;
	};
	/** Action handler (runs on server) */
	handler: ServerActionHandler<TData>;
}

/**
 * Built-in action types
 */
export type BuiltinActionType =
	| "create"
	| "save"
	| "delete"
	| "deleteMany"
	| "restore"
	| "restoreMany"
	| "duplicate";

/**
 * Server-side actions configuration for a collection
 */
export interface ServerActionsConfig {
	/** Built-in actions to enable */
	builtin?: BuiltinActionType[];
	/** Custom actions */
	custom?: ServerActionDefinition[];
}

/**
 * Context for actions config function.
 *
 * Uses the same field registry as collections, so you can use `f.text()`, `f.select()` etc.
 * for action form fields.
 *
 * @example
 * ```ts
 * .actions(({ a, c, f }) => ({
 *   custom: [
 *     a.action({
 *       id: "send-email",
 *       label: { en: "Send Email" },
 *       form: {
 *         title: { en: "Send Email" },
 *         fields: {
 *           subject: f.text({ label: { en: "Subject" }, required: true }),
 *           message: f.textarea({ label: { en: "Message" } }),
 *           priority: f.select({
 *             label: { en: "Priority" },
 *             options: [
 *               { value: "low", label: { en: "Low" } },
 *               { value: "high", label: { en: "High" } },
 *             ],
 *           }),
 *         },
 *       },
 *       handler: async ({ data }) => {
 *         // data.subject, data.message, data.priority are typed
 *         return { type: "success" };
 *       },
 *     }),
 *   ],
 * }))
 * ```
 */
export interface ActionsConfigContext<
	_TFields extends Record<string, unknown> = Record<string, unknown>,
	TComponents extends Record<string, any> | string = string,
> {
	/** Action builders */
	a: {
		/** Enable create action */
		create: () => BuiltinActionType;
		/** Enable save action */
		save: () => BuiltinActionType;
		/** Enable delete action */
		delete: () => BuiltinActionType;
		/** Enable delete many action */
		deleteMany: () => BuiltinActionType;
		/** Enable restore action */
		restore: () => BuiltinActionType;
		/** Enable restore many action */
		restoreMany: () => BuiltinActionType;
		/** Enable duplicate action */
		duplicate: () => BuiltinActionType;
		/** Define a custom action */
		action: <TData = Record<string, unknown>>(
			def: Omit<ServerActionDefinition<TData>, "scope"> & {
				scope?: "single" | "row";
			},
		) => ServerActionDefinition<TData>;
		/** Define a bulk action */
		bulkAction: <TData = Record<string, unknown>>(
			def: Omit<ServerActionDefinition<TData>, "scope">,
		) => ServerActionDefinition<TData>;
		/** Define a header action */
		headerAction: <TData = Record<string, unknown>>(
			def: Omit<ServerActionDefinition<TData>, "scope">,
		) => ServerActionDefinition<TData>;
	};
	/** Component helpers (from registered component registry) */
	c: ComponentFactory<TComponents>;
	/**
	 * Field proxy from field registry.
	 * Use the same field types as in collections: f.text(), f.select(), etc.
	 */
	f: Record<
		string,
		(config?: Record<string, unknown>) => ServerActionFormField
	>;
}

// ============================================================================
// Dashboard and Sidebar Context Types
// ============================================================================

/**
 * Action factory for dashboard header actions.
 */
export interface DashboardActionFactory {
	/** Return action as-is */
	action: (config: ServerDashboardAction) => ServerDashboardAction;
	/** Link action */
	link: (config: ServerDashboardAction) => ServerDashboardAction;
	/** Create action linking to collection create view */
	create: (
		config: Omit<ServerDashboardAction, "href"> & { collection: string },
	) => ServerDashboardAction;
	/** Global action linking to global edit view */
	global: (
		config: Omit<ServerDashboardAction, "href"> & { global: string },
	) => ServerDashboardAction;
}

/**
 * Context for dashboard config function
 */
export interface DashboardConfigContext<
	TComponents extends Record<string, any> | string = string,
> {
	/** Dashboard action helpers */
	a: DashboardActionFactory;
	/** Dashboard builder helpers */
	d: {
		/** Create dashboard config */
		dashboard: (config: ServerDashboardConfig) => ServerDashboardConfig;
		/** Create a section */
		section: (
			config: Omit<ServerDashboardSection, "type">,
		) => ServerDashboardSection;
		/** Create tabs */
		tabs: (config: Omit<ServerDashboardTabs, "type">) => ServerDashboardTabs;
		/** Create a stats widget */
		stats: (config: Omit<ServerStatsWidget, "type">) => ServerStatsWidget;
		/** Create a chart widget */
		chart: (config: Omit<ServerChartWidget, "type">) => ServerChartWidget;
		/** Create a recent items widget */
		recentItems: (
			config: Omit<ServerRecentItemsWidget, "type">,
		) => ServerRecentItemsWidget;
		/** Create a quick actions widget */
		quickActions: (
			config: Omit<ServerQuickActionsWidget, "type">,
		) => ServerQuickActionsWidget;
		/** Create a custom widget */
		custom: (config: Omit<ServerCustomWidget, "type">) => ServerCustomWidget;
		/** Create a value widget */
		value: (config: Omit<ServerValueWidget, "type">) => ServerValueWidget;
		/** Create a table widget */
		table: (config: Omit<ServerTableWidget, "type">) => ServerTableWidget;
		/** Create a timeline widget */
		timeline: (
			config: Omit<ServerTimelineWidget, "type">,
		) => ServerTimelineWidget;
		/** Create a progress widget */
		progress: (
			config: Omit<ServerProgressWidget, "type">,
		) => ServerProgressWidget;
	};
	/** Component helpers (from registered component registry) */
	c: ComponentFactory<TComponents>;
}

/**
 * Context for sidebar config function
 */
export interface SidebarConfigContext<
	TComponents extends Record<string, any> | string = string,
> {
	/** Sidebar builder helpers */
	s: {
		/** Create sidebar config */
		sidebar: (config: ServerSidebarConfig) => ServerSidebarConfig;
		/** Create a section */
		section: (
			config: Omit<ServerSidebarSection, "items"> & {
				items?: ServerSidebarItem[];
			},
		) => ServerSidebarSection;
	};
	/** Component helpers (from registered component registry) */
	c: ComponentFactory<TComponents>;
}

// ============================================================================
// Admin Builder Context Types
// ============================================================================

/**
 * Context for admin config functions with component proxy.
 *
 * `TComponents` can be either a components record (per-component typed props)
 * or a string union (backward-compatible, all components use `Record<string, unknown> | string`).
 */
export interface AdminConfigContext<
	TComponents extends Record<string, any> | string = string,
> {
	c: ComponentFactory<TComponents>;
}

/**
 * Extract the config type from a ViewDefinition.
 * Falls back to `TFallback` when the view has `unknown` config
 * (i.e. was defined without a config type parameter).
 */
type ExtractViewConfig<
	TView,
	TFallback = Record<string, unknown>,
> = TView extends ViewDefinition<any, any, infer C>
	? unknown extends C
		? TFallback
		: C
	: TFallback;

/**
 * View factory API generated from registered list views.
 *
 * Each key is a callable that accepts the **per-view config type** extracted
 * from the ViewDefinition's `~config` phantom field. When a view was defined
 * with `view<ListViewConfig>("table", { kind: "list" })`, calling `v.table()`
 * type-checks against `Omit<ListViewConfig, "view">`. A custom
 * `view<KanbanConfig>("kanban", ...)` would type-check against `KanbanConfig`.
 *
 * Accepts either a views record (per-view typed config) or a string union
 * (fallback: all views use `ListViewConfig`).
 */
export type ListViewFactory<
	TListViews extends Record<string, any> | string = string,
> =
	TListViews extends Record<string, any>
		? {
				[K in keyof TListViews & string]: (
					config: Omit<
						ExtractViewConfig<TListViews[K], ListViewConfig>,
						"view"
					>,
				) => ExtractViewConfig<TListViews[K], ListViewConfig> & { view: K };
			}
		: {
				[K in TListViews & string]: (
					config: Omit<ListViewConfig, "view">,
				) => ListViewConfig & { view: K };
			};

/**
 * View factory API generated from registered edit views.
 *
 * Same pattern as ListViewFactory but for edit views,
 * with `FormViewConfig` as the fallback config type.
 */
export type EditViewFactory<
	TEditViews extends Record<string, any> | string = string,
> =
	TEditViews extends Record<string, any>
		? {
				[K in keyof TEditViews & string]: (
					config: Omit<
						ExtractViewConfig<TEditViews[K], FormViewConfig>,
						"view"
					>,
				) => ExtractViewConfig<TEditViews[K], FormViewConfig> & { view: K };
			}
		: {
				[K in TEditViews & string]: (
					config: Omit<FormViewConfig, "view">,
				) => FormViewConfig & { view: K };
			};

/**
 * Context for list view config functions.
 *
 * `TListViews` can be either a views record (per-view typed config)
 * or a string union (backward-compatible, all views use `ListViewConfig`).
 */
export interface ListViewConfigContext<
	TFields extends Record<string, any> = Record<string, any>,
	TListViews extends Record<string, any> | string = string,
> {
	/** View factory — per-view typed config extracted from ViewDefinition */
	v: ListViewFactory<TListViews>;
	/** Field reference proxy - returns field names as strings */
	f: { [K in keyof TFields]: K };
	/** Action reference proxy */
	a: {
		create: string;
		save: string;
		delete: string;
		deleteMany: string;
		restore: string;
		restoreMany: string;
		duplicate: string;
		export: string;
		custom: (
			name: string,
			config?: unknown,
		) => { type: string; config?: unknown };
	};
}

/**
 * Context for form view config functions.
 *
 * `TEditViews` can be either a views record (per-view typed config)
 * or a string union (backward-compatible, all views use `FormViewConfig`).
 */
export interface FormViewConfigContext<
	TFields extends Record<string, any> = Record<string, any>,
	TEditViews extends Record<string, any> | string = string,
> {
	/** View factory — per-view typed config extracted from ViewDefinition */
	v: EditViewFactory<TEditViews>;
	/** Field reference proxy - returns field names as strings */
	f: { [K in keyof TFields]: K };
}

/**
 * Admin methods added to CollectionBuilder via monkey patching.
 */
interface CollectionBuilderAdminMethods<
	TFields extends Record<string, any> = Record<string, any>,
	TListViewNames extends string = string,
	TEditViewNames extends string = string,
	TComponents extends Record<string, any> | string = string,
> {
	/**
	 * Set admin metadata for the collection.
	 */
	admin(
		configOrFn:
			| AdminCollectionConfig
			| ((ctx: AdminConfigContext<TComponents>) => AdminCollectionConfig),
	): this;

	/**
	 * Configure list view for the collection.
	 */
	list(
		configFn: (
			ctx: ListViewConfigContext<TFields, TListViewNames>,
		) => ListViewConfig,
	): this;

	/**
	 * Configure form view for the collection.
	 */
	form(
		configFn: (
			ctx: FormViewConfigContext<TFields, TEditViewNames>,
		) => FormViewConfig,
	): this;

	/**
	 * Configure preview for the collection.
	 */
	preview(config: PreviewConfig): this;

	/**
	 * Configure actions for the collection.
	 * Enables built-in actions and custom actions with forms.
	 *
	 * @example
	 * ```ts
	 * .actions(({ a, c, fr }) => ({
	 *   builtin: [a.create(), a.delete(), a.deleteMany()],
	 *   custom: [
	 *     a.action({
	 *       id: "publish",
	 *       label: { en: "Publish" },
	 *       icon: c.icon("ph:check-circle"),
	 *       handler: async ({ itemId }) => {
	 *         return { type: "success", toast: { message: "Published!" } };
	 *       },
	 *     }),
	 *   ],
	 * }))
	 * ```
	 */
	actions(
		configFn: (
			ctx: ActionsConfigContext<TFields, TComponents>,
		) => ServerActionsConfig,
	): this;
}

/**
 * Admin methods added to GlobalBuilder via monkey patching.
 */
interface GlobalBuilderAdminMethods<
	TFields extends Record<string, any> = Record<string, any>,
	TEditViewNames extends string = string,
	TComponents extends Record<string, any> | string = string,
> {
	/**
	 * Set admin metadata for the global.
	 */
	admin(
		configOrFn:
			| AdminGlobalConfig
			| ((ctx: AdminConfigContext<TComponents>) => AdminGlobalConfig),
	): this;

	/**
	 * Configure form view for the global.
	 */
	form(
		configFn: (
			ctx: FormViewConfigContext<TFields, TEditViewNames>,
		) => FormViewConfig,
	): this;
}
