/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Typed factory functions with plugin extensions. Regenerate with: questpie generate

// ── Core Imports ───────────────────────────────────────────
import {
	CollectionBuilder,
	GlobalBuilder,
	wrapBuilderWithExtensions,
	builtinFields,
	type EmptyCollectionState,
	type EmptyGlobalState,
	type BuiltinFields,
} from "questpie";

// ── Runtime Field Imports ──────────────────────────────────
import { adminFields } from "@questpie/admin/server";

// Merged field factories — builtins + module-contributed (e.g. richText, blocks) + user fields
const _allFieldDefs = { ...builtinFields, ...adminFields } as const;

import {
	type LocaleConfig,
	type GlobalHooksInput,
	type CollectionAccess,
	type ContextResolver,
	createFieldNameProxy,
} from "questpie";

// ── Plugin Imports ─────────────────────────────────────────
import {
	type AdminCollectionConfig,
	type AdminConfigContext,
	type ListViewConfig,
	type ListViewConfigContext,
	type FilterViewsByKind,
	type FormViewConfig,
	type FormViewConfigContext,
	type PreviewConfig,
	type ServerActionsConfig,
	type ActionsConfigContext,
	type AdminGlobalConfig,
	type ServerBrandingConfig,
	type AdminLocaleConfig,
	type SidebarContribution,
	type DashboardContribution,
	createViewCallbackProxy,
	createComponentCallbackProxy,
	createActionCallbackProxy,
} from "@questpie/admin/server";

// ════════════════════════════════════════════════════════════
// Type extraction — driven by CategoryDeclaration
// ════════════════════════════════════════════════════════════

type _ViewsNames = (keyof Questpie.ViewsRegistry & string) | (string & {});
type _ViewsRecord = Questpie.ViewsRegistry;
type _ComponentsNames =
	| (keyof Questpie.ComponentsRegistry & string)
	| (string & {});
type _ComponentsNames_Strict = keyof Questpie.ComponentsRegistry & string;
type _ComponentsRecord = Questpie.ComponentsRegistry;

// Field types — populated by module codegen via Questpie.FieldTypesMap
type _AllFieldTypes = Questpie.FieldTypesMap;

// ════════════════════════════════════════════════════════════
// Type augmentations — generated from plugin registries
// ════════════════════════════════════════════════════════════

declare module "questpie" {
	interface CollectionBuilder<TState> {
		admin(
			configFn:
				| AdminCollectionConfig
				| ((
						ctx: AdminConfigContext<_ComponentsRecord>,
				  ) => AdminCollectionConfig),
		): CollectionBuilder<TState>;
		list(
			configFn: (
				ctx: ListViewConfigContext<
					TState extends {
						fieldDefinitions: infer F extends Record<string, any>;
					}
						? F
						: Record<string, any>,
					FilterViewsByKind<_ViewsRecord, "list">
				>,
			) => ListViewConfig,
		): CollectionBuilder<TState>;
		form(
			configFn: (
				ctx: FormViewConfigContext<
					TState extends {
						fieldDefinitions: infer F extends Record<string, any>;
					}
						? F
						: Record<string, any>,
					FilterViewsByKind<_ViewsRecord, "form">
				>,
			) => FormViewConfig,
		): CollectionBuilder<TState>;
		preview(config: PreviewConfig): CollectionBuilder<TState>;
		actions(
			configFn: (
				ctx: ActionsConfigContext<Record<string, unknown>, _ComponentsRecord>,
			) => ServerActionsConfig,
		): CollectionBuilder<TState>;
	}
	interface GlobalBuilder<TState> {
		admin(
			configFn:
				| AdminGlobalConfig
				| ((ctx: AdminConfigContext<_ComponentsRecord>) => AdminGlobalConfig),
		): GlobalBuilder<TState>;
		form(
			configFn: (
				ctx: FormViewConfigContext<
					TState extends {
						fieldDefinitions: infer F extends Record<string, any>;
					}
						? F
						: Record<string, any>,
					FilterViewsByKind<_ViewsRecord, "form">
				>,
			) => FormViewConfig,
		): GlobalBuilder<TState>;
	}
}

declare global {
	namespace Questpie {
		interface FieldTypesMap extends BuiltinFields {}
		interface FieldTypeRegistry extends Record<keyof _AllFieldTypes, {}> {}
	}
}

declare module "@questpie/admin/server" {
	interface ComponentTypeRegistry extends Record<_ComponentsNames_Strict, {}> {}
}

// ════════════════════════════════════════════════════════════
// Extension registries
// ════════════════════════════════════════════════════════════

const _collExt: Record<string, { stateKey: string; resolve: (v: any) => any }> =
	{
		admin: {
			stateKey: "admin",
			resolve(configOrFn: any) {
				if (typeof configOrFn === "function")
					return configOrFn({ c: createComponentCallbackProxy() });
				return configOrFn;
			},
		},
		list: {
			stateKey: "adminList",
			resolve(configOrFn: any) {
				const resolved =
					typeof configOrFn === "function"
						? configOrFn({
								v: createViewCallbackProxy(),
								f: createFieldNameProxy(),
								a: createActionCallbackProxy(),
							})
						: configOrFn;
				return {
					...{
						view: "collection-table",
						showSearch: true,
						showFilters: true,
						showToolbar: true,
					},
					...resolved,
				};
			},
		},
		form: {
			stateKey: "adminForm",
			resolve(configOrFn: any) {
				const resolved =
					typeof configOrFn === "function"
						? configOrFn({
								v: createViewCallbackProxy(),
								f: createFieldNameProxy(),
							})
						: configOrFn;
				return { ...{ view: "collection-form", showMeta: true }, ...resolved };
			},
		},
		preview: { stateKey: "adminPreview", resolve: (v: any) => v },
		actions: {
			stateKey: "adminActions",
			resolve(configOrFn: any) {
				if (typeof configOrFn === "function")
					return configOrFn({
						a: createActionCallbackProxy(),
						c: createComponentCallbackProxy(),
						f: createFieldNameProxy(),
					});
				return configOrFn;
			},
		},
	};

const _globExt: Record<string, { stateKey: string; resolve: (v: any) => any }> =
	{
		admin: {
			stateKey: "admin",
			resolve(configOrFn: any) {
				if (typeof configOrFn === "function")
					return configOrFn({ c: createComponentCallbackProxy() });
				return configOrFn;
			},
		},
		form: {
			stateKey: "adminForm",
			resolve(configOrFn: any) {
				const resolved =
					typeof configOrFn === "function"
						? configOrFn({
								v: createViewCallbackProxy(),
								f: createFieldNameProxy(),
							})
						: configOrFn;
				return { ...{ view: "global-form", showMeta: true }, ...resolved };
			},
		},
	};

// ════════════════════════════════════════════════════════════
// Factory functions
// ════════════════════════════════════════════════════════════

/**
 * Create a typed collection builder with plugin extensions.
 *
 * @example
 * ```ts
 * import { collection } from "#questpie/factories";
 *
 * export default collection("posts")
 *   .fields(({ f }) => ({ title: f.text({ required: true }) }))
 *   .admin(({ c }) => ({ icon: c.icon("ph:article") }))
 *   .list(({ v, f }) => v.collectionTable({ columns: [f.title] }))
 * ```
 */
export function collection<TName extends string>(
	name: TName,
): CollectionBuilder<EmptyCollectionState<TName, undefined, _AllFieldTypes>> {
	return wrapBuilderWithExtensions(
		CollectionBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs),
		_collExt,
		CollectionBuilder,
	) as any;
}

/**
 * Create a typed global builder with plugin extensions.
 */
export function global<TName extends string>(
	name: TName,
): GlobalBuilder<EmptyGlobalState<TName, undefined, _AllFieldTypes>> {
	return wrapBuilderWithExtensions(
		GlobalBuilder.create<TName, _AllFieldTypes>(name, _allFieldDefs),
		_globExt,
		GlobalBuilder,
	) as any;
}

// ════════════════════════════════════════════════════════════
// Singleton factory functions
// ════════════════════════════════════════════════════════════

/** Typed factory for locale config. */
export function locale<T extends LocaleConfig>(config: T): T {
	return config;
}

/** Typed factory for hooks config. */
export function hooks<T extends GlobalHooksInput>(config: T): T {
	return config;
}

/** Typed factory for access config. */
export function access<T extends CollectionAccess>(config: T): T {
	return config;
}

/** Typed factory for context config. */
export function context<T extends ContextResolver>(config: T): T {
	return config;
}

/** Typed factory for branding config. */
export function branding<T extends ServerBrandingConfig>(config: T): T {
	return config;
}

/** Typed factory for adminLocale config. */
export function adminLocale<T extends AdminLocaleConfig>(config: T): T {
	return config;
}

/** Typed factory for sidebar config. Accepts plain config or callback. */
export function sidebar<T extends SidebarContribution>(config: T): T;
export function sidebar<T extends (...args: any[]) => SidebarContribution>(
	cb: T,
): T;
export function sidebar(v: any): any {
	return v;
}

/** Typed factory for dashboard config. Accepts plain config or callback. */
export function dashboard<T extends DashboardContribution>(config: T): T;
export function dashboard<T extends (...args: any[]) => DashboardContribution>(
	cb: T,
): T;
export function dashboard(v: any): any {
	return v;
}
