/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, extractAppServices, type Questpie, type AppContext, type Registry, type QuestpieConfig, type QueueClient } from "questpie";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_siteSettings from "../globals/site-settings";

// ── Blocks ─────────────────────────────────────────────────
import { accordionBlock as _bloc_accordion } from "../blocks/accordion";
import { announcementBannerBlock as _bloc_announcementBanner } from "../blocks/announcement-banner";
import { columnsBlock as _bloc_columns } from "../blocks/columns";
import { contactsListBlock as _bloc_contactsList } from "../blocks/contacts-list";
import { ctaBlock as _bloc_cta } from "../blocks/cta";
import { dividerBlock as _bloc_divider } from "../blocks/divider";
import { documentsListBlock as _bloc_documentsList } from "../blocks/documents-list";
import { galleryBlock as _bloc_gallery } from "../blocks/gallery";
import { headingBlock as _bloc_heading } from "../blocks/heading";
import { heroBlock as _bloc_hero } from "../blocks/hero";
import { imageBlock as _bloc_image } from "../blocks/image";
import { imageTextBlock as _bloc_imageText } from "../blocks/image-text";
import { latestNewsBlock as _bloc_latestNews } from "../blocks/latest-news";
import { spacerBlock as _bloc_spacer } from "../blocks/spacer";
import { textBlock as _bloc_text } from "../blocks/text";
import { videoBlock as _bloc_video } from "../blocks/video";

// ── Core Singles ───────────────────────────────────────────
import _auth from "../auth";
import _contextResolver from "../context";
import _locale from "../locale";

// ── Plugin Singles ─────────────────────────────────────────
import _adminLocale from "../admin-locale";
import _branding from "../branding";
import _dashboard from "../dashboard";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

type _U2I<U> = (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;
type _Module = (typeof _modules)[number];
type _MPRaw<K extends string> = _U2I<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;
type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;

type _ModuleCollections = _MP<"collections">;
type _ModuleGlobals = _MP<"globals">;
type _ModuleJobs = _MP<"jobs">;
type _ModuleFunctions = _MP<"functions">;
type _ModuleRoutes = _MP<"routes">;
type _ModuleServices = _MP<"services">;
type _ModuleViews = _MP<"views">;
type _ModuleComponents = _MP<"components">;
type _ModuleBlocks = _MP<"blocks">;
// Recursive module property extraction (for fields contributed at each level)
type _ExtractProp<M, K extends string> = (M extends { modules: infer Sub extends readonly any[] } ? _ExtractPropArr<Sub, K> : {}) & (K extends keyof M ? M[K] extends Record<string, any> ? M[K] : {} : {});
type _ExtractPropArr<A extends readonly any[], K extends string> = A extends readonly [infer H, ...infer T extends readonly any[]] ? _ExtractProp<H, K> & _ExtractPropArr<T, K> : {};

type _AllModuleFields = _ExtractProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	announcements: typeof _coll_announcements;
	cities: typeof _coll_cities;
	cityMembers: typeof _coll_cityMembers;
	contacts: typeof _coll_contacts;
	documents: typeof _coll_documents;
	news: typeof _coll_news;
	pages: typeof _coll_pages;
	submissions: typeof _coll_submissions;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	siteSettings: typeof _glob_siteSettings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All functions in the app (modules + user, user overrides) */
export type AppFunctions = _ModuleFunctions;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All services in the app (modules + user, user overrides). Values are service instances. */
export type AppServices = _ModuleServices;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** All views in the app (modules + user, user overrides) */
export type AppViews = _ModuleViews;

/** All components in the app (modules + user, user overrides) */
export type AppComponents = _ModuleComponents;

/** All blocks in the app (modules + user, user overrides) */
export type AppBlocks = _ModuleBlocks & {
	accordion: typeof _bloc_accordion;
	announcementBanner: typeof _bloc_announcementBanner;
	columns: typeof _bloc_columns;
	contactsList: typeof _bloc_contactsList;
	cta: typeof _bloc_cta;
	divider: typeof _bloc_divider;
	documentsList: typeof _bloc_documentsList;
	gallery: typeof _bloc_gallery;
	heading: typeof _bloc_heading;
	hero: typeof _bloc_hero;
	image: typeof _bloc_image;
	imageText: typeof _bloc_imageText;
	latestNews: typeof _bloc_latestNews;
	spacer: typeof _bloc_spacer;
	text: typeof _bloc_text;
	video: typeof _bloc_video;
};

/** @internal — used only for type derivation, not exported */
type _AppInternal = Questpie<QuestpieConfig & {
	collections: AppCollections;
	globals: AppGlobals;
	jobs: AppJobs;
	functions: AppFunctions;
	routes: AppRoutes;
	services: AppServices;
	views: AppViews;
	components: AppComponents;
	blocks: AppBlocks;
}>;

// ── AppContext augmentation — auto-types ALL handlers ──────
declare global {
	namespace Questpie {
		interface AppContext {
			// Infrastructure
			db: _AppInternal['db'];
			email: _AppInternal['email'];
			queue: QueueClient<AppJobs>;
			storage: _AppInternal['storage'];
			kv: _AppInternal['kv'];
			logger: _AppInternal['logger'];
			search: _AppInternal['search'];
			realtime: _AppInternal['realtime'];

			// Entity APIs
			collections: _AppInternal['api']['collections'];
			globals: _AppInternal['api']['globals'];
			tables: _AppInternal['tables'];

			// Request-scoped
			session: _AppInternal['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;
		}

		interface Registry {
			"~fieldTypes": _AllModuleFields;
		}
	}
}

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections & Record<string, any>;
	globals: AppGlobals & Record<string, any>;
	functions: AppFunctions;
	routes: AppRoutes;
	auth: typeof _auth;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app = createApp(
	{
		modules: _modules as any,
		collections: {
			announcements: _coll_announcements,
			cities: _coll_cities,
			cityMembers: _coll_cityMembers,
			contacts: _coll_contacts,
			documents: _coll_documents,
			news: _coll_news,
			pages: _coll_pages,
			submissions: _coll_submissions,
		},
		globals: {
			siteSettings: _glob_siteSettings,
		},
		blocks: {
			accordion: _bloc_accordion,
			announcementBanner: _bloc_announcementBanner,
			columns: _bloc_columns,
			contactsList: _bloc_contactsList,
			cta: _bloc_cta,
			divider: _bloc_divider,
			documentsList: _bloc_documentsList,
			gallery: _bloc_gallery,
			heading: _bloc_heading,
			hero: _bloc_hero,
			image: _bloc_image,
			imageText: _bloc_imageText,
			latestNews: _bloc_latestNews,
			spacer: _bloc_spacer,
			text: _bloc_text,
			video: _bloc_video,
		},
		auth: _auth as any,
		contextResolver: _contextResolver as any,
		locale: _locale as any,
		adminLocale: _adminLocale as any,
		branding: _branding as any,
		dashboard: _dashboard as any,
		sidebar: _sidebar as any,
	},
	_runtime,
) as unknown as _AppInternal;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export async function createContext(options?: {
	accessMode?: 'system' | 'user';
}): Promise<AppContext> {
	const reqCtx = await (app as any).createContext({
		accessMode: options?.accessMode ?? 'system',
	});
	const services = extractAppServices(app, {
		db: (app as any).db,
		session: reqCtx.session,
	});
	return { ...services, locale: reqCtx.locale } as unknown as AppContext;
}

// Factories: import { collection, global, ... } from '#questpie/factories';
