/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate

import { createApp, createContextFactory, extractAppServices, type Questpie, type AppContext, type Registry, type QuestpieConfig, type QueueClient } from "questpie";

// ── Runtime ────────────────────────────────────────────────
import _runtime from "../questpie.config";

// ── Modules ────────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_announcements from "../collections/announcements";
import _coll_cities from "../collections/cities";
import _coll_cityMembers from "../collections/city-members";
import _coll_contacts from "../collections/contacts";
import _coll_documents from "../collections/documents";
import _coll_news from "../collections/news";
import _coll_pages from "../collections/pages";
import _coll_submissions from "../collections/submissions";

// ── Globals ────────────────────────────────────────────────
import _glob_site_settings from "../globals/site-settings";

// ── Core Singles ───────────────────────────────────────────
import _auth from "../auth";
import _contextResolver from "../context";
import _locale from "../locale";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { UnionToIntersection } from "questpie";
type _Module = (typeof _modules)[number];
type _MPRaw<K extends string> = UnionToIntersection<_Module extends infer M ? M extends Record<K, infer V> ? V : never : never>;
type _MP<K extends string> = [_MPRaw<K>] extends [never] ? {} : _MPRaw<K>;

type _ModuleCollections = _MP<"collections">;
type _ModuleGlobals = _MP<"globals">;
type _ModuleJobs = _MP<"jobs">;
type _ModuleRoutes = _MP<"routes">;
type _ModuleServices = _MP<"services">;
// Recursive module property extraction (for fields contributed at each level)
import type { ExtractModuleProp } from "questpie";

type _AllModuleFields = ExtractModuleProp<{ modules: typeof _modules }, "fields">;

/** All collections in the app (modules + user, user overrides) */
export type AppCollections = _ModuleCollections & {
	announcements: typeof _coll_announcements;
	cities: typeof _coll_cities;
	cityMembers: typeof _coll_cityMembers;
	contacts: typeof _coll_contacts;
	documents: typeof _coll_documents;
	news: typeof _coll_news;
	pages: typeof _coll_pages;
	submissions: typeof _coll_submissions;
};

/** All globals in the app (modules + user, user overrides) */
export type AppGlobals = _ModuleGlobals & {
	site_settings: typeof _glob_site_settings;
	site_settings: typeof _glob_site_settings;
};

/** All jobs in the app (modules + user, user overrides) */
export type AppJobs = _ModuleJobs;

/** All routes in the app (modules + user, user overrides) */
export type AppRoutes = _ModuleRoutes;

/** All services in the app (modules + user, user overrides). Values are service instances. */
export type AppServices = _ModuleServices;

/** All email templates in the app — use with email.sendTemplate() */
export type AppEmailTemplates = Record<string, never>;

/** @internal — used only for type derivation, not exported */
type _AppInternal = Questpie<QuestpieConfig & {
	collections: AppCollections;
	globals: AppGlobals;
	jobs: AppJobs;
	routes: AppRoutes;
	services: AppServices;
}>;

// ── AppContext augmentation — auto-types ALL handlers ──────
declare global {
	namespace Questpie {
		interface AppContext {
			// Infrastructure
			db: _AppInternal['db'];
			email: _AppInternal['email'];
			queue: QueueClient<AppJobs>;
			storage: _AppInternal['storage'];
			kv: _AppInternal['kv'];
			logger: _AppInternal['logger'];
			search: _AppInternal['search'];
			realtime: _AppInternal['realtime'];

			// Entity APIs
			collections: _AppInternal['api']['collections'];
			globals: _AppInternal['api']['globals'];
			tables: _AppInternal['tables'];

			// Request-scoped
			session: _AppInternal['auth'] extends { api: { getSession: (...args: any[]) => Promise<infer TSession> } } ? NonNullable<TSession> | null : null;
			t: (key: string, params?: Record<string, unknown>, locale?: string) => string;
		}

		interface Registry {
			collections: _Registry_Collections;
			globals: _Registry_Globals;
			jobs: _Registry_Jobs;
			functions: _Registry_Functions;
			routes: _Registry_Routes;
			services: _Registry_Services;
			emails: _Registry_Emails;
			views: _Registry_Views;
			components: _Registry_Components;
			blocks: _Registry_Blocks;
			"~fieldTypes": _AllModuleFields;
		}
	}
}

/**
 * Flat config type for client APIs.
 * Use with `createClient<AppConfig>()` and `createAdminAuthClient<AppConfig>()`.
 * For handler context, use `AppContext` (auto-typed via module augmentation).
 */
export type AppConfig = {
	collections: AppCollections & Record<string, any>;
	globals: AppGlobals & Record<string, any>;
	routes: AppRoutes;
	auth: typeof _auth;
};

// ════════════════════════════════════════════════════════════
// RUNTIME — create the app instance
// ════════════════════════════════════════════════════════════

export const app = await createApp(
	{
		modules: _modules as any,
		collections: {
			announcements: _coll_announcements,
			cities: _coll_cities,
			cityMembers: _coll_cityMembers,
			contacts: _coll_contacts,
			documents: _coll_documents,
			news: _coll_news,
			pages: _coll_pages,
			submissions: _coll_submissions,
		},
		globals: {
			site_settings: _glob_site_settings,
		},
		auth: _auth as any,
		contextResolver: _contextResolver as any,
		locale: _locale as any,
	},
	_runtime,
) as unknown as _AppInternal;

// ── createContext — typed context for scripts ──────────────
/**
 * Create a typed AppContext for use in scripts, tests, or standalone code.
 * Resolves all services and provides flat access to infrastructure.
 *
 * @example
 * ```ts
 * import { createContext } from "#questpie";
 *
 * const ctx = await createContext();
 * const posts = await ctx.collections.posts.find({});
 * ```
 */
export const createContext = createContextFactory(app);

// Factories: import { collection, global, ... } from '#questpie/factories';
