import { convert } from "html-to-text";

import { extractAppServices } from "#questpie/server/config/app-context.js";
import { tryGetContext } from "#questpie/server/config/context.js";

import type { MailAdapter } from "./adapter.js";
import { ConsoleAdapter } from "./adapters/console.adapter.js";
import type {
	EmailTemplateDefinition,
	EmailTemplateNames,
	GetEmailTemplate,
	InferEmailTemplateInput,
	EmailResult,
} from "./template.js";
import type {
	MailerConfig,
	MailOptions,
	SerializableMailOptions,
} from "./types.js";

const isDev = process.env.NODE_ENV !== "production";

/**
 * Main mailer service
 */
export class MailerService<
	TTemplates extends Record<string, any> = Record<string, any>,
> {
	private templates: Map<string, EmailTemplateDefinition<any, any>>;
	private defaultFrom?: string;
	private defaultAdapter: MailAdapter | null = null;

	constructor(private config: MailerConfig<TTemplates>) {
		this.templates = new Map();
		if (config.templates) {
			for (const [key, template] of Object.entries(config.templates)) {
				// Key by record key (camelCase) — matches AppEmailTemplates generated by codegen.
				// e.g. "newBlogPost" from emails/new-blog-post.ts
				this.templates.set(key, template);
			}
		}
		this.defaultFrom = config.defaults?.from;
	}

	/**
	 * Get the mail adapter, falling back to ConsoleAdapter in development
	 */
	private async getAdapter(): Promise<MailAdapter> {
		const adapter = await this.config.adapter;
		if (adapter) {
			return adapter;
		}

		// In development, use ConsoleAdapter as default
		if (isDev) {
			if (!this.defaultAdapter) {
				this.defaultAdapter = new ConsoleAdapter();
			}
			return this.defaultAdapter;
		}

		throw new Error(
			"QUESTPIE: Email adapter is not configured. Provide adapter in .build({ email: { adapter: ... } })",
		);
	}

	/**
	 * Resolve the handler context from AsyncLocalStorage.
	 * Returns AppContext services if running inside a request/job scope.
	 */
	private resolveHandlerContext(): any {
		const stored = tryGetContext();
		if (!stored?.app) return {};
		return extractAppServices(stored.app, {
			db: stored.db,
			session: stored.session,
		});
	}

	/**
	 * Serialize mail options (convert HTML to plain text if needed)
	 */
	private serializeMailOptions(options: MailOptions): SerializableMailOptions {
		let { html, text } = options;

		if (html && !text) {
			text = convert(html);
		}

		if (!html && !text) {
			throw new Error("No text or html provided");
		}

		return {
			...options,
			from: options.from || this.defaultFrom || "noreply@example.com",
			text: text || "",
			html: html || "",
		};
	}

	/**
	 * Send an email
	 */
	async send(options: MailOptions): Promise<void> {
		const serializedMail = this.serializeMailOptions(options);
		const adapter = await this.getAdapter();
		return adapter.send(serializedMail);
	}

	/**
	 * Render an email template without sending it.
	 * Useful for previewing emails in the admin UI.
	 *
	 * @returns The rendered email result with subject, html, and optional text
	 */
	async renderTemplate<K extends EmailTemplateNames<TTemplates>>(options: {
		template: K;
		input: InferEmailTemplateInput<GetEmailTemplate<TTemplates, K>>;
		locale?: string;
	}): Promise<EmailResult> {
		const templateDef = this.templates.get(options.template as string);
		if (!templateDef) {
			throw new Error(`Template "${String(options.template)}" not found.`);
		}

		// Validate input with Zod schema
		const validatedInput = templateDef.schema.parse(options.input);

		// Build handler args: AppContext + input + locale
		const appServices = this.resolveHandlerContext();
		const handlerArgs = {
			...appServices,
			input: validatedInput,
			locale: options.locale,
		};

		// Call handler (may be async)
		const result = await templateDef.handler(handlerArgs as any);

		if (!result.subject) {
			throw new Error(
				`Email handler for "${String(options.template)}" must return a subject`,
			);
		}
		if (!result.html) {
			throw new Error(
				`Email handler for "${String(options.template)}" must return html`,
			);
		}

		return result;
	}

	/**
	 * Send an email using a defined template
	 */
	async sendTemplate<K extends EmailTemplateNames<TTemplates>>(options: {
		template: K;
		input: InferEmailTemplateInput<GetEmailTemplate<TTemplates, K>>;
		to: string | string[];
		subject?: string;
		from?: string;
		cc?: string | string[];
		bcc?: string | string[];
		locale?: string;
	}): Promise<void> {
		const result = await this.renderTemplate({
			template: options.template,
			input: options.input,
			locale: options.locale,
		});

		return this.send({
			to: options.to,
			subject: options.subject || result.subject,
			from: options.from,
			cc: options.cc,
			bcc: options.bcc,
			html: result.html,
			text: result.text,
		});
	}
}
