/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module
import "./registries.js";


// ── Sub-Modules ────────────────────────────────────────────
import _modules from "../modules";

// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account";
import _coll_adminLocks from "../collections/admin-locks";
import _coll_adminPreferences from "../collections/admin-preferences";
import _coll_adminSavedViews from "../collections/admin-saved-views";
import _coll_apikey from "../collections/apikey";
import _coll_assets from "../collections/assets";
import _coll_session from "../collections/session";
import _coll_user from "../collections/user";
import _coll_verification from "../collections/verification";

// ── Routes ────────────────────────────────────────────
import { adminConfigFunctions as _route_adminConfig } from "../routes/admin-config";
import { actionFunctions as _route_executeAction } from "../routes/execute-action";
import { localeFunctions as _route_locales } from "../routes/locales";
import { previewFunctions as _route_preview } from "../routes/preview";
import { reactiveFunctions as _route_reactive } from "../routes/reactive";
import { setupFunctions as _route_setup } from "../routes/setup";
import { translationFunctions as _route_translations } from "../routes/translations";
import { widgetDataFunctions as _route_widgetData } from "../routes/widget-data";

// ── Views ────────────────────────────────────────────
import _view_form from "../views/form";
import _view_globalForm from "../views/global-form";
import _view_table from "../views/table";

// ── Components ────────────────────────────────────────────
import _comp_badge from "../components/badge";
import _comp_icon from "../components/icon";

// ── Singles ────────────────────────────────────────────────
import _fields from "../fields";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AdminCollections {
	account: typeof _coll_account;
	adminLocks: typeof _coll_adminLocks;
	adminPreferences: typeof _coll_adminPreferences;
	adminSavedViews: typeof _coll_adminSavedViews;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
}

export type AdminRoutes = typeof _route_adminConfig & typeof _route_executeAction & typeof _route_locales & typeof _route_preview & typeof _route_reactive & typeof _route_setup & typeof _route_translations & typeof _route_widgetData;

export interface AdminViews {
	form: typeof _view_form;
	globalForm: typeof _view_globalForm;
	table: typeof _view_table;
}

export interface AdminComponents {
	badge: typeof _comp_badge;
	icon: typeof _comp_icon;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-admin" as const,
	modules: _modules,
	collections: {
		account: _coll_account,
		adminLocks: _coll_adminLocks,
		adminPreferences: _coll_adminPreferences,
		adminSavedViews: _coll_adminSavedViews,
		apikey: _coll_apikey,
		assets: _coll_assets,
		session: _coll_session,
		user: _coll_user,
		verification: _coll_verification,
	} as AdminCollections,
	routes: {
		..._route_adminConfig,
		..._route_executeAction,
		..._route_locales,
		..._route_preview,
		..._route_reactive,
		..._route_setup,
		..._route_translations,
		..._route_widgetData,
	} as AdminRoutes,
	views: {
		form: _view_form,
		globalForm: _view_globalForm,
		table: _view_table,
	} as AdminViews,
	components: {
		badge: _comp_badge,
		icon: _comp_icon,
	} as AdminComponents,
	globals: {},
	jobs: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	blocks: {},
	fields: _fields,
	sidebar: [_sidebar],
	dashboard: [] as const,
};

export type AdminModule = typeof _module;
export default _module;
