/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Factory registry augmentations for module. Separate file to avoid circular refs.
// IMPORTANT: This file must NOT import from module.ts to avoid circular imports.

import type _view_collectionForm from "../views/form";
import type _view_collectionTable from "../views/table";
import type _view_globalForm from "../views/global-form";

interface _RegViews {
	collectionForm: typeof _view_collectionForm;
	collectionTable: typeof _view_collectionTable;
	globalForm: typeof _view_globalForm;
}

import type _comp_badge from "../components/badge";
import type _comp_icon from "../components/icon";

interface _RegComponents {
	badge: typeof _comp_badge;
	icon: typeof _comp_icon;
}

import type _fields from "../fields";
type _FieldTypes = typeof _fields;

declare global {
	namespace Questpie {
		interface ViewsRegistry extends _RegViews {}
		interface ComponentsRegistry extends _RegComponents {}
		interface FieldTypesMap extends _FieldTypes {}
	}
}
