/**
 * Widget Definition & Factory
 *
 * Defines dashboard widgets.
 * The `widget()` factory returns a plain frozen object.
 */

import type { MaybeLazyComponent } from "../types/common";

/**
 * Widget definition — a plain frozen object describing a dashboard widget.
 */
export interface WidgetDefinition<TName extends string = string> {
	readonly name: TName;
	readonly component: MaybeLazyComponent;
}

/**
 * Create a dashboard widget as a plain frozen object.
 *
 * @example
 * ```ts
 * // Generated by `questpie generate`:
 * export default widget("stats", {
 *   component: () => import("./stats-widget.js"),
 * });
 * ```
 */
export function widget<
	TName extends string,
	TComponent extends MaybeLazyComponent,
>(name: TName, config: { component: TComponent }): WidgetDefinition<TName> {
	return Object.freeze({
		name,
		component: config.component,
	});
}
