/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiPreviewRouteImport } from './routes/api/preview'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AppCitySlugRouteImport } from './routes/_app/$citySlug'
import { Route as AppCitySlugIndexRouteImport } from './routes/_app/$citySlug.index'
import { Route as AppCitySlugDocumentsRouteImport } from './routes/_app/$citySlug.documents'
import { Route as AppCitySlugContactRouteImport } from './routes/_app/$citySlug.contact'
import { Route as AppCitySlugAnnouncementsRouteImport } from './routes/_app/$citySlug.announcements'
import { Route as AppCitySlugNewsIndexRouteImport } from './routes/_app/$citySlug.news.index'
import { Route as AppCitySlugPagesSlugRouteImport } from './routes/_app/$citySlug.pages.$slug'
import { Route as AppCitySlugNewsSlugRouteImport } from './routes/_app/$citySlug.news.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AppCitySlugRoute = AppCitySlugRouteImport.update({
  id: '/_app/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCitySlugIndexRoute = AppCitySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const AppCitySlugDocumentsRoute = AppCitySlugDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const AppCitySlugContactRoute = AppCitySlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const AppCitySlugAnnouncementsRoute =
  AppCitySlugAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AppCitySlugRoute,
  } as any)
const AppCitySlugNewsIndexRoute = AppCitySlugNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const AppCitySlugPagesSlugRoute = AppCitySlugPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AppCitySlugRoute,
} as any)
const AppCitySlugNewsSlugRoute = AppCitySlugNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => AppCitySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/$citySlug': typeof AppCitySlugRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/$citySlug/announcements': typeof AppCitySlugAnnouncementsRoute
  '/$citySlug/contact': typeof AppCitySlugContactRoute
  '/$citySlug/documents': typeof AppCitySlugDocumentsRoute
  '/$citySlug/': typeof AppCitySlugIndexRoute
  '/$citySlug/news/$slug': typeof AppCitySlugNewsSlugRoute
  '/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
  '/$citySlug/news': typeof AppCitySlugNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/$citySlug/announcements': typeof AppCitySlugAnnouncementsRoute
  '/$citySlug/contact': typeof AppCitySlugContactRoute
  '/$citySlug/documents': typeof AppCitySlugDocumentsRoute
  '/$citySlug': typeof AppCitySlugIndexRoute
  '/$citySlug/news/$slug': typeof AppCitySlugNewsSlugRoute
  '/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
  '/$citySlug/news': typeof AppCitySlugNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/_app/$citySlug': typeof AppCitySlugRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/api/preview': typeof ApiPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/$citySlug/announcements': typeof AppCitySlugAnnouncementsRoute
  '/_app/$citySlug/contact': typeof AppCitySlugContactRoute
  '/_app/$citySlug/documents': typeof AppCitySlugDocumentsRoute
  '/_app/$citySlug/': typeof AppCitySlugIndexRoute
  '/_app/$citySlug/news/$slug': typeof AppCitySlugNewsSlugRoute
  '/_app/$citySlug/pages/$slug': typeof AppCitySlugPagesSlugRoute
  '/_app/$citySlug/news/': typeof AppCitySlugNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$citySlug'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/admin/'
    | '/$citySlug/announcements'
    | '/$citySlug/contact'
    | '/$citySlug/documents'
    | '/$citySlug/'
    | '/$citySlug/news/$slug'
    | '/$citySlug/pages/$slug'
    | '/$citySlug/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/admin'
    | '/$citySlug/announcements'
    | '/$citySlug/contact'
    | '/$citySlug/documents'
    | '/$citySlug'
    | '/$citySlug/news/$slug'
    | '/$citySlug/pages/$slug'
    | '/$citySlug/news'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_app/$citySlug'
    | '/admin/$'
    | '/api/$'
    | '/api/preview'
    | '/admin/'
    | '/_app/$citySlug/announcements'
    | '/_app/$citySlug/contact'
    | '/_app/$citySlug/documents'
    | '/_app/$citySlug/'
    | '/_app/$citySlug/news/$slug'
    | '/_app/$citySlug/pages/$slug'
    | '/_app/$citySlug/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppCitySlugRoute: typeof AppCitySlugRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/$citySlug': {
      id: '/_app/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof AppCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$citySlug/': {
      id: '/_app/$citySlug/'
      path: '/'
      fullPath: '/$citySlug/'
      preLoaderRoute: typeof AppCitySlugIndexRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/documents': {
      id: '/_app/$citySlug/documents'
      path: '/documents'
      fullPath: '/$citySlug/documents'
      preLoaderRoute: typeof AppCitySlugDocumentsRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/contact': {
      id: '/_app/$citySlug/contact'
      path: '/contact'
      fullPath: '/$citySlug/contact'
      preLoaderRoute: typeof AppCitySlugContactRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/announcements': {
      id: '/_app/$citySlug/announcements'
      path: '/announcements'
      fullPath: '/$citySlug/announcements'
      preLoaderRoute: typeof AppCitySlugAnnouncementsRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/news/': {
      id: '/_app/$citySlug/news/'
      path: '/news'
      fullPath: '/$citySlug/news'
      preLoaderRoute: typeof AppCitySlugNewsIndexRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/pages/$slug': {
      id: '/_app/$citySlug/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/$citySlug/pages/$slug'
      preLoaderRoute: typeof AppCitySlugPagesSlugRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
    '/_app/$citySlug/news/$slug': {
      id: '/_app/$citySlug/news/$slug'
      path: '/news/$slug'
      fullPath: '/$citySlug/news/$slug'
      preLoaderRoute: typeof AppCitySlugNewsSlugRouteImport
      parentRoute: typeof AppCitySlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCitySlugRouteChildren {
  AppCitySlugAnnouncementsRoute: typeof AppCitySlugAnnouncementsRoute
  AppCitySlugContactRoute: typeof AppCitySlugContactRoute
  AppCitySlugDocumentsRoute: typeof AppCitySlugDocumentsRoute
  AppCitySlugIndexRoute: typeof AppCitySlugIndexRoute
  AppCitySlugNewsSlugRoute: typeof AppCitySlugNewsSlugRoute
  AppCitySlugPagesSlugRoute: typeof AppCitySlugPagesSlugRoute
  AppCitySlugNewsIndexRoute: typeof AppCitySlugNewsIndexRoute
}

const AppCitySlugRouteChildren: AppCitySlugRouteChildren = {
  AppCitySlugAnnouncementsRoute: AppCitySlugAnnouncementsRoute,
  AppCitySlugContactRoute: AppCitySlugContactRoute,
  AppCitySlugDocumentsRoute: AppCitySlugDocumentsRoute,
  AppCitySlugIndexRoute: AppCitySlugIndexRoute,
  AppCitySlugNewsSlugRoute: AppCitySlugNewsSlugRoute,
  AppCitySlugPagesSlugRoute: AppCitySlugPagesSlugRoute,
  AppCitySlugNewsIndexRoute: AppCitySlugNewsIndexRoute,
}

const AppCitySlugRouteWithChildren = AppCitySlugRoute._addFileChildren(
  AppCitySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppCitySlugRoute: AppCitySlugRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiPreviewRoute: ApiPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
