/* eslint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { auditLogCollection as _coll_admin_audit_log } from "../collections/audit-log.collection";
// ── Singles ────────────────────────────────────────────────
import _dashboard from "../dashboard";
import _hooks from "../hooks";
// ── Jobs ────────────────────────────────────────────
import { auditCleanupJob as _job_auditCleanup_job } from "../jobs/audit-cleanup.job";
import _sidebar from "../sidebar";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AuditCollections {
	admin_audit_log: typeof _coll_admin_audit_log;
}

export interface AuditJobs {
	"auditCleanup.job": typeof _job_auditCleanup_job;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-audit" as const,
	collections: {
		admin_audit_log: _coll_admin_audit_log,
	} as AuditCollections,
	jobs: {
		"auditCleanup.job": _job_auditCleanup_job,
	} as AuditJobs,
	globals: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	views: {},
	components: {},
	blocks: {},
	dashboard: [_dashboard],
	hooks: _hooks,
	sidebar: [_sidebar],
};

export type AuditModule = typeof _module;
export default _module;
