/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Routes ──────────────────────────────────────────────
import _route_health from "../routes/health";

// ── Services ────────────────────────────────────────────
import _svc_auth from "../services/auth";
import _svc_collectionsApi from "../services/collections-api";
import _svc_db from "../services/db";
import _svc_email from "../services/email";
import _svc_globalsApi from "../services/globals-api";
import _svc_i18n from "../services/i18n";
import _svc_kv from "../services/kv";
import _svc_logger from "../services/logger";
import _svc_queue from "../services/queue";
import _svc_realtime from "../services/realtime";
import _svc_search from "../services/search";
import _svc_storage from "../services/storage";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface CoreServices {
	auth: typeof _svc_auth;
	collectionsApi: typeof _svc_collectionsApi;
	db: typeof _svc_db;
	email: typeof _svc_email;
	globalsApi: typeof _svc_globalsApi;
	i18n: typeof _svc_i18n;
	kv: typeof _svc_kv;
	logger: typeof _svc_logger;
	queue: typeof _svc_queue;
	realtime: typeof _svc_realtime;
	search: typeof _svc_search;
	storage: typeof _svc_storage;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-core" as const,
	collections: {},
	globals: {},
	jobs: {},
	routes: {
		health: _route_health,
	},
	messages: {},
	services: {
		auth: _svc_auth,
		collectionsApi: _svc_collectionsApi,
		db: _svc_db,
		email: _svc_email,
		globalsApi: _svc_globalsApi,
		i18n: _svc_i18n,
		kv: _svc_kv,
		logger: _svc_logger,
		queue: _svc_queue,
		realtime: _svc_realtime,
		search: _svc_search,
		storage: _svc_storage,
	} as CoreServices,
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
};

export type CoreModule = typeof _module;
export default _module;
