/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

import _job_indexRecords from "../jobs/index-records";
import _job_scheduledTransition from "../jobs/scheduled-transition";

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

export interface CoreJobs {
	indexRecords: typeof _job_indexRecords;
	scheduledTransition: typeof _job_scheduledTransition;
}

const _module = {
	name: "questpie-core" as const,
	collections: {},
	globals: {},
	jobs: {
		indexRecords: _job_indexRecords,
		scheduledTransition: _job_scheduledTransition,
	} as CoreJobs,
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
};

export type CoreModule = typeof _module;
export default _module;
