/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Jobs ────────────────────────────────────────────
import _job_indexRecords from "../jobs/index-records";
import _job_scheduledTransition from "../jobs/scheduled-transition";

// ── Routes ────────────────────────────────────────────
import _route_collection from "../routes/[collection]";
import _route_collection_PATCH from "../routes/[collection].patch";
import _route_collection_POST from "../routes/[collection].post";
import _route_collection_id from "../routes/[collection]/[id]";
import _route_collection_id_DELETE from "../routes/[collection]/[id].delete";
import _route_collection_id_PATCH from "../routes/[collection]/[id].patch";
import _route_collection_id_audit from "../routes/[collection]/[id]/audit";
import _route_collection_id_restore from "../routes/[collection]/[id]/restore";
import _route_collection_id_revert from "../routes/[collection]/[id]/revert";
import _route_collection_id_transition from "../routes/[collection]/[id]/transition";
import _route_collection_id_versions from "../routes/[collection]/[id]/versions";
import _route_collection_count from "../routes/[collection]/count";
import _route_collection_deleteMany from "../routes/[collection]/delete-many";
import _route_collection_files_spread_key from "../routes/[collection]/files/[...key]";
import _route_collection_meta from "../routes/[collection]/meta";
import _route_collection_schema from "../routes/[collection]/schema";
import _route_collection_updateBatch from "../routes/[collection]/update-batch";
import _route_collection_upload from "../routes/[collection]/upload";
import _route_auth_spread_path from "../routes/auth/[...path]";
import _route_globals_name from "../routes/globals/[name]";
import _route_globals_name_PATCH from "../routes/globals/[name].patch";
import _route_globals_name_audit from "../routes/globals/[name]/audit";
import _route_globals_name_meta from "../routes/globals/[name]/meta";
import _route_globals_name_revert from "../routes/globals/[name]/revert";
import _route_globals_name_schema from "../routes/globals/[name]/schema";
import _route_globals_name_transition from "../routes/globals/[name]/transition";
import _route_globals_name_versions from "../routes/globals/[name]/versions";
import _route_health from "../routes/health";
import _route_realtime from "../routes/realtime";
import _route_search from "../routes/search";
import _route_search_reindex_collection from "../routes/search/reindex/[collection]";
import _route_storage_files_spread_key from "../routes/storage/files/[...key]";

// ── Services ────────────────────────────────────────────
import _svc_auth from "../services/auth";
import _svc_collectionsApi from "../services/collections-api";
import _svc_db from "../services/db";
import _svc_email from "../services/email";
import _svc_globalsApi from "../services/globals-api";
import _svc_i18n from "../services/i18n";
import _svc_kv from "../services/kv";
import _svc_logger from "../services/logger";
import _svc_queue from "../services/queue";
import _svc_realtime from "../services/realtime";
import _svc_search from "../services/search";
import _svc_storage from "../services/storage";

// ── FieldTypes ────────────────────────────────────────────
import { booleanFieldType as _ftype_boolean } from "../fields/boolean";
import { fromFieldType as _ftype_custom } from "../fields/from";
import { dateFieldType as _ftype_date } from "../fields/date";
import { datetimeFieldType as _ftype_datetime } from "../fields/datetime";
import { emailFieldType as _ftype_email } from "../fields/email";
import { jsonFieldType as _ftype_json } from "../fields/json";
import { numberFieldType as _ftype_number } from "../fields/number";
import { objectFieldType as _ftype_object } from "../fields/object";
import { relationFieldType as _ftype_relation } from "../fields/relation";
import { selectFieldType as _ftype_select } from "../fields/select";
import { textFieldType as _ftype_text } from "../fields/text";
import { textareaFieldType as _ftype_textarea } from "../fields/textarea";
import { timeFieldType as _ftype_time } from "../fields/time";
import { uploadFieldType as _ftype_upload } from "../fields/upload";
import { urlFieldType as _ftype_url } from "../fields/url";

// ── Singles ────────────────────────────────────────────────
import _appConfig from "../config/app";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

import type { RouteParamsFromKey, RouteWithParams } from "questpie";

export interface CoreJobs {
	indexRecords: typeof _job_indexRecords;
	scheduledTransition: typeof _job_scheduledTransition;
}

export interface CoreRoutes {
	"[collection]": RouteWithParams<typeof _route_collection, RouteParamsFromKey<"[collection]">>;
	"[collection]:PATCH": RouteWithParams<typeof _route_collection_PATCH, RouteParamsFromKey<"[collection]:PATCH">>;
	"[collection]:POST": RouteWithParams<typeof _route_collection_POST, RouteParamsFromKey<"[collection]:POST">>;
	"[collection]/[id]": RouteWithParams<typeof _route_collection_id, RouteParamsFromKey<"[collection]/[id]">>;
	"[collection]/[id]:DELETE": RouteWithParams<typeof _route_collection_id_DELETE, RouteParamsFromKey<"[collection]/[id]:DELETE">>;
	"[collection]/[id]:PATCH": RouteWithParams<typeof _route_collection_id_PATCH, RouteParamsFromKey<"[collection]/[id]:PATCH">>;
	"[collection]/[id]/audit": RouteWithParams<typeof _route_collection_id_audit, RouteParamsFromKey<"[collection]/[id]/audit">>;
	"[collection]/[id]/restore": RouteWithParams<typeof _route_collection_id_restore, RouteParamsFromKey<"[collection]/[id]/restore">>;
	"[collection]/[id]/revert": RouteWithParams<typeof _route_collection_id_revert, RouteParamsFromKey<"[collection]/[id]/revert">>;
	"[collection]/[id]/transition": RouteWithParams<typeof _route_collection_id_transition, RouteParamsFromKey<"[collection]/[id]/transition">>;
	"[collection]/[id]/versions": RouteWithParams<typeof _route_collection_id_versions, RouteParamsFromKey<"[collection]/[id]/versions">>;
	"[collection]/count": RouteWithParams<typeof _route_collection_count, RouteParamsFromKey<"[collection]/count">>;
	"[collection]/deleteMany": RouteWithParams<typeof _route_collection_deleteMany, RouteParamsFromKey<"[collection]/deleteMany">>;
	"[collection]/files/[...key]": RouteWithParams<typeof _route_collection_files_spread_key, RouteParamsFromKey<"[collection]/files/[...key]">>;
	"[collection]/meta": RouteWithParams<typeof _route_collection_meta, RouteParamsFromKey<"[collection]/meta">>;
	"[collection]/schema": RouteWithParams<typeof _route_collection_schema, RouteParamsFromKey<"[collection]/schema">>;
	"[collection]/updateBatch": RouteWithParams<typeof _route_collection_updateBatch, RouteParamsFromKey<"[collection]/updateBatch">>;
	"[collection]/upload": RouteWithParams<typeof _route_collection_upload, RouteParamsFromKey<"[collection]/upload">>;
	"auth/[...path]": RouteWithParams<typeof _route_auth_spread_path, RouteParamsFromKey<"auth/[...path]">>;
	"globals/[name]": RouteWithParams<typeof _route_globals_name, RouteParamsFromKey<"globals/[name]">>;
	"globals/[name]:PATCH": RouteWithParams<typeof _route_globals_name_PATCH, RouteParamsFromKey<"globals/[name]:PATCH">>;
	"globals/[name]/audit": RouteWithParams<typeof _route_globals_name_audit, RouteParamsFromKey<"globals/[name]/audit">>;
	"globals/[name]/meta": RouteWithParams<typeof _route_globals_name_meta, RouteParamsFromKey<"globals/[name]/meta">>;
	"globals/[name]/revert": RouteWithParams<typeof _route_globals_name_revert, RouteParamsFromKey<"globals/[name]/revert">>;
	"globals/[name]/schema": RouteWithParams<typeof _route_globals_name_schema, RouteParamsFromKey<"globals/[name]/schema">>;
	"globals/[name]/transition": RouteWithParams<typeof _route_globals_name_transition, RouteParamsFromKey<"globals/[name]/transition">>;
	"globals/[name]/versions": RouteWithParams<typeof _route_globals_name_versions, RouteParamsFromKey<"globals/[name]/versions">>;
	health: RouteWithParams<typeof _route_health, RouteParamsFromKey<"health">>;
	realtime: RouteWithParams<typeof _route_realtime, RouteParamsFromKey<"realtime">>;
	search: RouteWithParams<typeof _route_search, RouteParamsFromKey<"search">>;
	"search/reindex/[collection]": RouteWithParams<typeof _route_search_reindex_collection, RouteParamsFromKey<"search/reindex/[collection]">>;
	"storage/files/[...key]": RouteWithParams<typeof _route_storage_files_spread_key, RouteParamsFromKey<"storage/files/[...key]">>;
}

export interface CoreServices {
	auth: typeof _svc_auth;
	collectionsApi: typeof _svc_collectionsApi;
	db: typeof _svc_db;
	email: typeof _svc_email;
	globalsApi: typeof _svc_globalsApi;
	i18n: typeof _svc_i18n;
	kv: typeof _svc_kv;
	logger: typeof _svc_logger;
	queue: typeof _svc_queue;
	realtime: typeof _svc_realtime;
	search: typeof _svc_search;
	storage: typeof _svc_storage;
}

export interface CoreFieldTypes {
	boolean: typeof _ftype_boolean;
	custom: typeof _ftype_custom;
	date: typeof _ftype_date;
	datetime: typeof _ftype_datetime;
	email: typeof _ftype_email;
	json: typeof _ftype_json;
	number: typeof _ftype_number;
	object: typeof _ftype_object;
	relation: typeof _ftype_relation;
	select: typeof _ftype_select;
	text: typeof _ftype_text;
	textarea: typeof _ftype_textarea;
	time: typeof _ftype_time;
	upload: typeof _ftype_upload;
	url: typeof _ftype_url;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-core" as const,
	jobs: {
		indexRecords: _job_indexRecords,
		scheduledTransition: _job_scheduledTransition,
	} as CoreJobs,
	routes: {
		"[collection]": _route_collection,
		"[collection]:PATCH": _route_collection_PATCH,
		"[collection]:POST": _route_collection_POST,
		"[collection]/[id]": _route_collection_id,
		"[collection]/[id]:DELETE": _route_collection_id_DELETE,
		"[collection]/[id]:PATCH": _route_collection_id_PATCH,
		"[collection]/[id]/audit": _route_collection_id_audit,
		"[collection]/[id]/restore": _route_collection_id_restore,
		"[collection]/[id]/revert": _route_collection_id_revert,
		"[collection]/[id]/transition": _route_collection_id_transition,
		"[collection]/[id]/versions": _route_collection_id_versions,
		"[collection]/count": _route_collection_count,
		"[collection]/deleteMany": _route_collection_deleteMany,
		"[collection]/files/[...key]": _route_collection_files_spread_key,
		"[collection]/meta": _route_collection_meta,
		"[collection]/schema": _route_collection_schema,
		"[collection]/updateBatch": _route_collection_updateBatch,
		"[collection]/upload": _route_collection_upload,
		"auth/[...path]": _route_auth_spread_path,
		"globals/[name]": _route_globals_name,
		"globals/[name]:PATCH": _route_globals_name_PATCH,
		"globals/[name]/audit": _route_globals_name_audit,
		"globals/[name]/meta": _route_globals_name_meta,
		"globals/[name]/revert": _route_globals_name_revert,
		"globals/[name]/schema": _route_globals_name_schema,
		"globals/[name]/transition": _route_globals_name_transition,
		"globals/[name]/versions": _route_globals_name_versions,
		health: _route_health,
		realtime: _route_realtime,
		search: _route_search,
		"search/reindex/[collection]": _route_search_reindex_collection,
		"storage/files/[...key]": _route_storage_files_spread_key,
	} as CoreRoutes,
	services: {
		auth: _svc_auth,
		collectionsApi: _svc_collectionsApi,
		db: _svc_db,
		email: _svc_email,
		globalsApi: _svc_globalsApi,
		i18n: _svc_i18n,
		kv: _svc_kv,
		logger: _svc_logger,
		queue: _svc_queue,
		realtime: _svc_realtime,
		search: _svc_search,
		storage: _svc_storage,
	} as CoreServices,
	fieldTypes: {
		boolean: _ftype_boolean,
		custom: _ftype_custom,
		date: _ftype_date,
		datetime: _ftype_datetime,
		email: _ftype_email,
		json: _ftype_json,
		number: _ftype_number,
		object: _ftype_object,
		relation: _ftype_relation,
		select: _ftype_select,
		text: _ftype_text,
		textarea: _ftype_textarea,
		time: _ftype_time,
		upload: _ftype_upload,
		url: _ftype_url,
	} as CoreFieldTypes,
	collections: {},
	globals: {},
	messages: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	config: {
		app: _appConfig,
	},
};

export type CoreModule = typeof _module;
export default _module;
