/**
 * Admin Module
 *
 * Complete backend module for running the QUESTPIE admin panel.
 *
 * Exports:
 * - `adminModule` — static module definition (generated by codegen from file convention)
 * - `AdminModule` — type of the static module
 * - `AdminCollections` — named interface for admin collections (prevents TS7056)
 * - `adminRpc` — admin RPC functions derived from `adminModule.functions`
 *
 * The admin module itself follows the file convention:
 * - collections/  → merged starter collections + admin UI config
 * - functions/    → RPC handlers for admin panel operations
 * - modules.ts    → [starterModule] dependency
 * - sidebar.ts    → admin sidebar contribution
 */

// ── Generated module ──────────────────────────────────────────────────────────
export type { AdminModule, AdminCollections } from "./.generated/module.js";
export { default as adminModule } from "./.generated/module.js";

// ── Admin RPC bundle — derived from generated module (no manual duplication) ─
import adminModule from "./.generated/module.js";

/**
 * Admin RPC functions — flat spread of all admin function definitions.
 * Automatically registered when adminModule is included in your app modules.
 */
export const adminRpc = adminModule.functions;

// ── Utility re-exports ────────────────────────────────────────────────────────
// These are specific values/types used directly by user code (not just via module).

// Saved views collection types — for type-safe filter/sort config
export {
	type FilterOperator,
	type FilterRule,
	type SortConfig,
	savedViewsCollection,
	type ViewConfiguration,
} from "../admin-preferences/collections/saved-views.collection.js";

// Action execution (used in HTTP adapter for custom action handling)
export {
	actionFunctions,
	type ExecuteActionRequest,
	type ExecuteActionResponse,
	executeAction,
	executeActionFn,
	getActionsConfig,
	getActionsConfigFn,
} from "./functions/execute-action.js";

// Preview token utilities (used for public preview routes)
export {
	createPreviewFunctions,
	createPreviewTokenVerifier,
	type PreviewTokenPayload,
	verifyPreviewTokenDirect,
} from "./functions/preview.js";

// Reactive field utilities (used for field options/reactivity)
export { batchReactive, fieldOptions, reactiveFunctions } from "./functions/reactive.js";

// Setup utilities (used in CLI / first-run setup)
export { createFirstAdmin, isSetupRequired, setupFunctions } from "./functions/setup.js";

// Widget data utilities (used in dashboard widgets)
export { fetchWidgetData, widgetDataFunctions } from "./functions/widget-data.js";
