import {
	resolveAppUrl,
	resolveDbConfig,
	resolveSecret,
	resolveStorageConfig,
} from "#questpie/server/config/cloud-env.js";
import type { GlobalHooksState } from "#questpie/server/config/global-hooks-types.js";
import type {
	AppDefinition,
	ModuleDefinition,
	RuntimeConfig,
	RuntimeConfigInput,
} from "#questpie/server/config/module-types.js";
import { Questpie } from "#questpie/server/config/questpie.js";
import type {
	QuestpieConfig,
	StorageConfig,
} from "#questpie/server/config/types.js";
import {
	mergeMessagesIntoConfig,
	mergeTranslationsConfig,
} from "#questpie/server/i18n/translator.js";
import { mergeAuthOptions } from "#questpie/server/integrated/auth/merge.js";

// ============================================================================
// module() — identity function for type inference
// ============================================================================

/**
 * Define a module as a plain data object.
 * Modules contribute collections, globals, jobs, routes, fields,
 * auth config, migrations, messages, etc.
 *
 * @example
 * ```ts
 * import { module, collection } from "questpie";
 *
 * export const myModule = module({
 *   name: "my-module",
 *   collections: { posts: postCollection },
 *   jobs: { sendNewsletter },
 *   messages: { en: { "my.key": "Hello" } },
 * });
 * ```
 */
export function module<T extends ModuleDefinition>(definition: T): T {
	return definition;
}

// ============================================================================
// config() — identity function for type inference (legacy)
// ============================================================================

// ============================================================================
// runtimeConfig() — cloud-aware runtime config with env auto-detection
// ============================================================================

/**
 * Define the runtime configuration for `questpie.config.ts`.
 * Contains only runtime infrastructure (db, adapters, secret) and plugin registrations.
 * No entity definitions — those come from the definition object generated by codegen.
 *
 * **Cloud-aware**: `app` and `db` are optional. When omitted they are resolved
 * automatically from environment variables:
 *
 * | Field     | QUESTPIE Cloud env        | Standard fallback       | Default              |
 * |-----------|---------------------------|-------------------------|----------------------|
 * | `app.url` | `QUESTPIE_APP_URL`        | `APP_URL`               | `http://localhost:3000` |
 * | `db.url`  | `QUESTPIE_DB`             | `DATABASE_URL`          | *(throws)*           |
 * | `secret`  | `QUESTPIE_SECRET`         | `BETTER_AUTH_SECRET`    | `undefined`          |
 * | `storage` | `QUESTPIE_STORAGE_*`      | —                       | local `./uploads`    |
 *
 * When `QUESTPIE_STORAGE_ENDPOINT`, `QUESTPIE_STORAGE_BUCKET`,
 * `QUESTPIE_STORAGE_ACCESS_KEY`, and `QUESTPIE_STORAGE_SECRET_KEY` are all set,
 * an S3-compatible storage driver is auto-configured (requires `@aws-sdk/client-s3`).
 *
 * @example Zero-config on QUESTPIE Cloud:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 * });
 * ```
 *
 * @example Explicit overrides:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: process.env.APP_URL! },
 *   db: { url: process.env.DATABASE_URL! },
 *   secret: process.env.SECRET,
 *   email: { adapter: new ConsoleAdapter() },
 * });
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §3.1 (Functions)
 */
export function runtimeConfig(input: RuntimeConfigInput): RuntimeConfig {
	return {
		...input,
		app: { url: resolveAppUrl(input.app?.url) },
		db: resolveDbConfig(input.db),
		secret: resolveSecret(input.secret as string | undefined),
		storage: resolveStorageConfig(input.storage as StorageConfig | undefined),
	};
}

// ============================================================================
// Module resolution — depth-first, left-to-right
// ============================================================================

/**
 * Flatten modules depth-first per RFC §13.7.
 * Dependencies are resolved before the module that depends on them.
 * Duplicate modules (by name) are deduplicated — last occurrence wins.
 */
function resolveModules(modules: ModuleDefinition[]): ModuleDefinition[] {
	const flat: ModuleDefinition[] = [];
	for (const mod of modules) {
		if (mod.modules && mod.modules.length > 0) {
			flat.push(...resolveModules(mod.modules));
		}
		flat.push(mod);
	}
	// Deduplicate by name — keep last occurrence (later wins)
	const seen = new Map<string, number>();
	for (let i = 0; i < flat.length; i++) {
		seen.set(flat[i].name, i);
	}
	return flat.filter((_, i) => {
		const mod = flat[i];
		return seen.get(mod.name) === i;
	});
}

// ============================================================================
// Merge infrastructure
// ============================================================================

/**
 * Merge function: `(existing, incoming) → merged`.
 *
 * Plugins can provide custom merge functions for their contributed keys.
 * Common helpers are exported for reuse:
 * - {@link mergeRecord} — spread-merge two objects
 * - {@link mergeConcat} — concatenate two arrays
 * - {@link lastWins} — incoming replaces existing
 */
export type MergeFn = (existing: any, incoming: any) => any;

/** Spread-merge two records: `{ ...a, ...b }`. */
export const mergeRecord: MergeFn = (a, b) => ({
	...(a || {}),
	...(b || {}),
});

/** Concatenate two arrays: `[...a, ...b]`. */
export const mergeConcat: MergeFn = (a, b) => [...(a || []), ...(b || [])];

/** Merge two objects by concatenating any array-valued properties and merging the rest. */
export const mergeDeepConcat: MergeFn = (a, b) => {
	const result = { ...(a || {}) };
	for (const [key, value] of Object.entries(b || {})) {
		if (Array.isArray(result[key]) && Array.isArray(value)) {
			result[key] = [...result[key], ...value];
		} else if (result[key] !== undefined && typeof result[key] === "object" && typeof value === "object" && !Array.isArray(value)) {
			result[key] = { ...result[key], ...value };
		} else {
			result[key] = value;
		}
	}
	return result;
};

/** Last value wins (incoming replaces existing). */
export const lastWins: MergeFn = (_a, b) => b;

/** Deep-merge message dictionaries by locale. */
function mergeMessages(
	a: Record<string, Record<string, string>>,
	b?: Record<string, Record<string, string>>,
): Record<string, Record<string, string>> {
	if (!b) return a;
	const result: Record<string, Record<string, string>> = { ...a };
	for (const [locale, msgs] of Object.entries(b)) {
		result[locale] = { ...(result[locale] || {}), ...msgs };
	}
	return result;
}

/** Normalize a hooks value into an array (handles single entry or already-array). */
function normalizeHookEntries<T>(value: T | T[] | undefined): T[] {
	if (!value) return [];
	if (Array.isArray(value)) return value;
	return [value];
}

/** Concatenate global hook arrays (normalizes single-entry inputs). */
function mergeGlobalHooks(
	a: GlobalHooksState | undefined,
	b: GlobalHooksState | undefined,
): GlobalHooksState | undefined {
	if (!a && !b) return undefined;
	if (!a) return b;
	if (!b) return a;
	return {
		collections: [...normalizeHookEntries(a.collections), ...normalizeHookEntries(b.collections)],
		globals: [...normalizeHookEntries(a.globals), ...normalizeHookEntries(b.globals)],
	};
}

/**
 * Merge functions for known module keys.
 *
 * Each entry maps a key name to its merge function: `(existing, incoming) → merged`.
 * Keys not in this map use auto-detect merge (see {@link mergeGenericKey}):
 * - Object + Object → spread merge
 * - Array + Array → concatenate
 * - Otherwise → incoming wins
 *
 * Uses actual functions (not string strategies) so plugins can provide
 * arbitrary merge logic for their contributed keys.
 *
 * Common helpers are exported for reuse:
 * {@link mergeRecord}, {@link mergeConcat}, {@link lastWins}.
 *
 * @example
 * ```ts
 * // A plugin can register custom merge for its keys:
 * MERGE_FNS.set("auditRules", mergeConcat);
 * ```
 */
// ============================================================================
// Config bucket merge
// ============================================================================

/**
 * Per-config-key sub-property merge strategies.
 * Each config key (app, admin, auth, etc.) can declare how its sub-properties
 * should be merged when multiple modules contribute the same config key.
 *
 * Keys not listed here use lastWins (incoming replaces existing).
 * Config keys not in this map at all use lastWins on the whole object.
 */
const CONFIG_KEY_MERGE = new Map<string, Map<string, MergeFn>>([
	[
		"app",
		new Map<string, MergeFn>([
			["locale", lastWins],
			["access", lastWins],
			["hooks", (a, b) => mergeGlobalHooks(a, b)],
			["context", lastWins],
		]),
	],
	[
		"admin",
		new Map<string, MergeFn>([
			["sidebar", mergeDeepConcat],
			["dashboard", mergeDeepConcat],
			["branding", lastWins],
			["locale", lastWins],
		]),
	],
]);

/**
 * Merge a single config key using its declared sub-property merge strategies.
 * Falls back to lastWins for unknown sub-keys.
 */
function mergeConfigKey(
	configKey: string,
	existing: any,
	incoming: any,
): any {
	// Special case: auth is deep-merged as a whole via mergeAuthOptions
	if (configKey === "auth") {
		return mergeAuthOptions(existing ?? {}, incoming ?? {});
	}

	const subKeyMerges = CONFIG_KEY_MERGE.get(configKey);
	if (!subKeyMerges) {
		// No sub-key merge declared — lastWins on the whole config key
		return incoming;
	}

	// Sub-key-level merge
	const result = { ...(existing || {}) };
	for (const [key, value] of Object.entries(incoming || {})) {
		const subMerge = subKeyMerges.get(key);
		if (subMerge && result[key] !== undefined) {
			result[key] = subMerge(result[key], value);
		} else {
			result[key] = value;
		}
	}
	return result;
}

/**
 * Merge the `config` bucket from two module-like objects.
 * Each key in the config bucket (app, auth, admin, openapi, etc.)
 * is merged independently using its per-key merge strategy.
 */
function mergeConfigBucket(existing: any, incoming: any): any {
	const result = { ...(existing || {}) };
	for (const [key, value] of Object.entries(incoming || {})) {
		if (result[key] !== undefined) {
			result[key] = mergeConfigKey(key, result[key], value);
		} else {
			result[key] = value;
		}
	}
	return result;
}

// ============================================================================
// Module merge functions
// ============================================================================

const MERGE_FNS = new Map<string, MergeFn>([
	["collections", mergeRecord],
	["globals", mergeRecord],
	["jobs", mergeRecord],
	["routes", mergeRecord],
	["fields", mergeRecord],
	["services", mergeRecord],
	["messages", (a, b) => mergeMessages(a, b)],
	["migrations", mergeConcat],
	["seeds", mergeConcat],
	["config", mergeConfigBucket],
]);

/** Keys skipped during module merging (structural, not data). */
const STRUCTURAL_KEYS = new Set(["name", "modules", "plugin"]);

/**
 * Known infrastructure keys on RuntimeConfig that should NOT be forwarded
 * to `instance.state`. Only truly unknown extension keys pass through.
 *
 * @see RuntimeConfig in module-types.ts for the full list.
 */
const RUNTIME_CONSUMED_KEYS = new Set([
	"plugins",
	"app",
	"db",
	"secret",
	"storage",
	"email",
	"queue",
	"search",
	"realtime",
	"logger",
	"kv",
	"translations",
	"autoMigrate",
	"autoSeed",
	"cli",
]);

/**
 * Keys consumed by QuestpieConfig construction or definition metadata.
 * Everything NOT in this set flows to `instance.state` for plugins to read
 * (e.g., admin reads sidebar, dashboard, branding, blocks, views, components).
 *
 * Fully generic — any plugin's extension keys automatically flow through
 * without being listed anywhere.
 */
const CONFIG_CONSUMED_KEYS = new Set([
	// Module-mergeable keys (from MERGE_FNS → become QuestpieConfig properties)
	...MERGE_FNS.keys(),
	// Derived key (computed from messages + config, not from modules directly)
	"translations",
	// Definition-only keys (used directly in config construction, not merged)
	"emailTemplates",
	// Structural
	"name",
	"modules",
	// Codegen-only (never leaks to instance.state)
	"plugin",
]);

/** Create an empty merged state with correct initial values for known keys. */
function emptyMergedState(): Record<string, any> {
	return {
		collections: {},
		globals: {},
		jobs: {},
		routes: {},
		fields: {},
		services: {},
		migrations: [],
		seeds: [],
		messages: {},
		config: {},
		translations: undefined,
	};
}

/**
 * Merge a module (or module-like object) into accumulated state.
 *
 * For keys in {@link MERGE_FNS}, the declared merge function is used.
 * For unknown keys (plugin extensions), auto-detect merge is applied.
 * Structural keys ("name", "modules") are skipped.
 */
function mergeModuleIntoState(
	state: Record<string, any>,
	mod: Record<string, any>,
): Record<string, any> {
	const result: Record<string, any> = { ...state };

	for (const key of Object.keys(mod)) {
		if (STRUCTURAL_KEYS.has(key)) continue;

		const incoming = mod[key];
		if (incoming === undefined) continue;

		const mergeFn = MERGE_FNS.get(key);
		if (mergeFn) {
			result[key] = mergeFn(state[key], incoming);
		} else {
			mergeGenericKey(result, key, state[key], incoming);
		}
	}

	return result;
}

/**
 * Auto-detect merge for extension keys (not in {@link MERGE_FNS}):
 * - Array + Array → concatenate
 * - Object + Object → spread merge
 * - Otherwise → incoming wins
 */
function mergeGenericKey(
	result: Record<string, any>,
	key: string,
	existing: any,
	incoming: any,
): void {
	if (Array.isArray(incoming) && Array.isArray(existing)) {
		result[key] = [...existing, ...incoming];
	} else if (Array.isArray(incoming)) {
		result[key] = [...incoming];
	} else if (
		incoming != null &&
		typeof incoming === "object" &&
		!Array.isArray(incoming) &&
		typeof existing === "object" &&
		!Array.isArray(existing) &&
		existing != null
	) {
		result[key] = { ...existing, ...incoming };
	} else {
		result[key] = incoming;
	}
}

// ============================================================================
// Extension state extraction
// ============================================================================

/**
 * Extract extension state — all merged keys NOT consumed by QuestpieConfig.
 * Stored on `instance.state` for plugins to read (e.g., admin reads
 * sidebar, dashboard, branding, blocks, views, components).
 *
 * Fully generic — any plugin's extension keys automatically flow through
 * without being listed anywhere.
 *
 * @param merged - Fully merged state from all modules + user entities
 * @param configOverrides - Config-level overrides (legacy createApp only)
 */
function buildExtensionState(
	merged: Record<string, any>,
	configOverrides?: Record<string, unknown>,
): Record<string, unknown> {
	const extensionState: Record<string, unknown> = {};

	// Extract all non-config keys from merged state
	for (const [key, value] of Object.entries(merged)) {
		if (!CONFIG_CONSUMED_KEYS.has(key) && value !== undefined) {
			extensionState[key] = value;
		}
	}

	// Apply config-level overrides (legacy mode only)
	if (configOverrides) {
		for (const [key, value] of Object.entries(configOverrides)) {
			if (CONFIG_CONSUMED_KEYS.has(key) || value === undefined) continue;

			const existing = extensionState[key];

			// Array: append config-level to module-level
			if (Array.isArray(existing) && value != null) {
				extensionState[key] = Array.isArray(value)
					? [...existing, ...value]
					: [...existing, value];
			}
			// Otherwise: config-level overrides
			else {
				extensionState[key] = value;
			}
		}
	}

	// Auto-build any builder instances in extension state records.
	// This handles e.g. BlockBuilder → BlockDefinition without coupling
	// the core engine to specific builder types from other packages.
	// Duck-type check: if a value has a .build() method, call it.
	for (const [key, value] of Object.entries(extensionState)) {
		if (value && typeof value === "object" && !Array.isArray(value)) {
			const record = value as Record<string, unknown>;
			let rebuilt = false;
			const builtRecord: Record<string, unknown> = {};
			for (const [k, v] of Object.entries(record)) {
				if (v && typeof (v as any).build === "function") {
					builtRecord[k] = (v as any).build();
					rebuilt = true;
				} else {
					builtRecord[k] = v;
				}
			}
			if (rebuilt) {
				extensionState[key] = builtRecord;
			}
		}
	}

	return extensionState;
}

/**
 * Extract unknown extension keys from RuntimeConfig.
 * Filters out known infrastructure keys so only truly unknown
 * plugin-contributed keys (e.g. `channels`, `workflows`) flow through
 * to `instance.state`.
 */
function extractRuntimeExtensions(
	runtime: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
	if (!runtime) return undefined;
	const extensions: Record<string, unknown> = {};
	let hasAny = false;
	for (const [key, value] of Object.entries(runtime)) {
		if (!RUNTIME_CONSUMED_KEYS.has(key) && value !== undefined) {
			extensions[key] = value;
			hasAny = true;
		}
	}
	return hasAny ? extensions : undefined;
}

// ============================================================================
// createApp() — the main entry point
// ============================================================================

/**
 * Create and return a fully initialized Questpie CMS app.
 *
 * ```ts
 * createApp(definition, runtime)
 * ```
 * - `definition` — generated by codegen, contains modules + user entities + config bucket
 * - `runtime` — from `questpie.config.ts`, contains db/adapters/secret/plugins
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App — .generated/index.ts)
 */
export async function createApp(
	definition: AppDefinition,
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>> {
	return createAppFromDefinition(definition, runtime);
}

// ============================================================================
// New architecture: createApp(definition, runtime)
// ============================================================================

/**
 * Create a Questpie app from a definition object + runtime config.
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1
 */
async function createAppFromDefinition(
	definition: AppDefinition,
	runtime: RuntimeConfig,
): Promise<Questpie<QuestpieConfig>> {
	// 1. Resolve modules depth-first
	const flatModules = resolveModules(definition.modules ?? []);

	// 2. Merge all module contributions
	let merged = emptyMergedState();
	for (const mod of flatModules) {
		merged = mergeModuleIntoState(merged, mod);
	}

	// 3. Merge user entities on top (user always wins over modules)
	// All keys flow through: known keys use MERGE_FNS, extensions use auto-detect.
	// Definition-only keys (locale, contextResolver, emailTemplates) pass through
	// merged state but are filtered from extension state by CONFIG_CONSUMED_KEYS.
	merged = mergeModuleIntoState(merged, { name: "user", ...definition });

	// 4. Convert messages to translations config
	const mergedTranslations = mergeMessagesIntoConfig(
		merged.translations,
		merged.messages,
	);
	const finalTranslations = runtime.translations
		? mergeTranslationsConfig(mergedTranslations, runtime.translations)
		: mergedTranslations;

	// 5. Build QuestpieConfig — extract consumed config keys
	const allJobs = merged.jobs;
	const hasJobs = Object.keys(allJobs).length > 0;

	// Extract config bucket values
	const cfg = merged.config ?? {};
	const appCfg = cfg.app ?? {};
	const authCfg = cfg.auth ?? {};

	const cmsConfig: QuestpieConfig = {
		app: runtime.app,
		db: runtime.db,
		secret: runtime.secret,
		collections: merged.collections,
		globals: merged.globals,
		locale: appCfg.locale,
		auth: authCfg,
		storage: runtime.storage,
		email: definition.emailTemplates
			? { ...(runtime.email ?? {}), templates: definition.emailTemplates }
			: runtime.email,
		queue:
			hasJobs && runtime.queue
				? {
						jobs: allJobs,
						adapter: runtime.queue.adapter,
					}
				: undefined,
		routes: Object.keys(merged.routes).length > 0 ? merged.routes : undefined,
		search: runtime.search,
		realtime: runtime.realtime,
		logger: runtime.logger,
		kv: runtime.kv,
		migrations: {
			migrations: [...merged.migrations],
		},
		seeds: {
			seeds: [...merged.seeds],
		},
		autoMigrate: runtime.autoMigrate,
		autoSeed: runtime.autoSeed,
		translations: finalTranslations,
		contextResolver: appCfg.context,
		globalHooks: appCfg.hooks,
		defaultAccess: appCfg.access,
		services:
			Object.keys(merged.services).length > 0 ? merged.services : undefined,
	};

	// 6. Create Questpie instance
	const instance = new Questpie(cmsConfig);

	// 7. Store extension state + config bucket on instance.state
	const runtimeExtensions = extractRuntimeExtensions(
		runtime as Record<string, unknown>,
	);
	const extensionState = buildExtensionState(merged, runtimeExtensions);

	// The entire merged config bucket goes to instance.state.config — no filtering.
	// Runtime already extracted what it needs (locale, hooks, auth, etc.) into cmsConfig.
	// state.config is the single source of truth for all plugin configs at runtime.
	if (Object.keys(cfg).length > 0) {
		extensionState.config = cfg;
	}

	instance.state = extensionState;

	await instance._initServices();

	return instance;
}

