import type { BetterAuthOptions } from "better-auth";
import type { CollectionAccess } from "#questpie/server/collection/builder/types.js";

// ============================================================================
// Auth Config — type for auth.ts file convention
// ============================================================================

/**
 * Auth configuration type for the `auth.ts` file convention.
 * Accepts Better Auth options (email/password, social providers, plugins, etc.).
 *
 * @example
 * ```ts
 * // auth.ts
 * import type { AuthConfig } from "questpie";
 *
 * export default {
 *   emailAndPassword: { enabled: true },
 *   socialProviders: {
 *     google: { clientId: "...", clientSecret: "..." },
 *   },
 * } satisfies AuthConfig;
 * ```
 *
 * @see RFC §9 (Auth)
 */
export type AuthConfig = BetterAuthOptions;

export type {
	CallbackParamDefinition,
	CategoryDeclaration,
	CodegenPlugin,
	CodegenResult,
	CodegenTargetContribution,
	CodegenTargetGenerateContext,
	CodegenTargetOutput,
	CrossTargetValidator,
	DiscoveredFile,
	DiscoverPattern,
	DiscoveryResult,
	MultiTargetCodegenResult,
	ProjectionError,
	RegistryExtension,
	ResolvedTarget,
	ScaffoldConfig,
	ScaffoldContext,
	SingletonFactory,
} from "#questpie/cli/codegen/types.js";

import type { CodegenPlugin } from "#questpie/cli/codegen/types.js";
import type { GlobalHooksState } from "#questpie/server/config/global-hooks-types.js";
import type {
	AnyCollectionOrBuilder,
	AnyGlobalOrBuilder,
	ContextResolver,
	DbConfig,
	LocaleConfig,
	StorageConfig,
} from "#questpie/server/config/types.js";
import type { RouteDefinition } from "#questpie/server/routes/types.js";
import type { TranslationsConfig } from "#questpie/server/i18n/types.js";
import type { KVConfig } from "#questpie/server/integrated/kv/index.js";
import type { LoggerConfig } from "#questpie/server/integrated/logger/index.js";
import type { MailerConfig } from "#questpie/server/integrated/mailer/index.js";
import type {
	JobDefinition,
	QueueAdapter,
} from "#questpie/server/integrated/queue/types.js";
import type { RealtimeConfig } from "#questpie/server/integrated/realtime/index.js";
import type { SearchAdapter } from "#questpie/server/integrated/search/index.js";
import type { Migration } from "#questpie/server/migration/types.js";
import type { Seed, SeedCategory } from "#questpie/server/seed/types.js";

// ============================================================================
// Module Definition — what module() accepts
// ============================================================================

/**
 * Module definition — a static plain object describing what a module contributes.
 * Modules are generated by codegen from the file system. No factory functions.
 *
 * Admin-specific properties (listViews, formViews, components, blocks,
 * sidebar, dashboard, branding, adminLocale) are added via declaration
 * merging by `@questpie/admin`.
 *
 * @see RFC-MODULE-ARCHITECTURE §2 (Core Concepts)
 */
export interface ModuleDefinition {
	/** Unique module name (e.g. "questpie-starter", "questpie-admin"). */
	name: string;

	/** Dependency modules — resolved depth-first before this module. */
	modules?: ModuleDefinition[];

	/** Collections this module contributes. Later modules override by key. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals this module contributes. Later modules override by key. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Job definitions this module contributes. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Route definitions this module contributes. */
	routes?: Record<string, RouteDefinition>;

	/** Custom field types this module contributes (extends the `f` proxy). */
	fields?: Record<string, any>;

	/** Services this module contributes. Keyed by service name. */
	services?: Record<
		string,
		import("#questpie/server/services/define-service.js").ServiceBuilder<any>
	>;

	/** Partial auth config — deep-merged with other modules and user config. */
	auth?: BetterAuthOptions | Record<string, any>;

	/** Migrations this module contributes — concatenated with others. */
	migrations?: Migration[];

	/** Seeds this module contributes — concatenated with others. */
	seeds?: Seed[];

	/**
	 * Backend messages keyed by locale.
	 * Deep-merged per locale — later modules override individual keys.
	 */
	messages?: Record<string, Record<string, string>>;

	/** Default access control. Last module with this set wins. */
	defaultAccess?: CollectionAccess;

	/**
	 * Global lifecycle hooks. Arrays are concatenated across modules.
	 */
	hooks?: GlobalHooksState;

	/**
	 * Extensible — admin module augments this interface to add:
	 * listViews, formViews, components, blocks, sidebar, dashboard, branding, adminLocale.
	 */
	[key: string]: unknown;
}

// ============================================================================
// Runtime Config — what questpie.config.ts exports (new architecture)
// ============================================================================

/**
 * Runtime configuration — the shape of `questpie.config.ts` in the new architecture.
 * Contains only runtime infrastructure (db, adapters, secret) and plugin registrations.
 * No entity definitions (collections, globals, etc.) — those come from the definition
 * object generated by codegen.
 *
 * Created via `runtimeConfig({ ... })`.
 *
 * @example
 * ```ts
 * // questpie.config.ts
 * import { runtimeConfig } from "questpie";
 * import { adminPlugin } from "@questpie/admin/server";
 *
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: process.env.APP_URL! },
 *   db: { url: process.env.DATABASE_URL! },
 *   secret: process.env.SECRET,
 *   email: { adapter: new ConsoleAdapter() },
 * });
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §3.1 (Functions), §8.1 (User Project)
 */
export interface RuntimeConfig {
	/** Codegen plugins — discover additional file patterns and extend generated output. */
	plugins?: CodegenPlugin[];

	/** Application URL (required). */
	app: { url: string };

	/** Database connection (required). */
	db: DbConfig;

	/** Secret key for signing tokens. */
	secret?: string;

	/** Storage configuration. */
	storage?: StorageConfig;

	/** Email configuration with adapter. */
	email?: MailerConfig;

	/** Queue configuration with adapter. */
	queue?: { adapter: QueueAdapter };

	/** Search adapter for full-text search. */
	search?: SearchAdapter;

	/** Realtime configuration. */
	realtime?: RealtimeConfig;

	/** Logger configuration. */
	logger?: LoggerConfig;

	/** KV store configuration. */
	kv?: KVConfig;

	/** I18n translations config (backend messages). */
	translations?: TranslationsConfig;

	/** Auto-migrate on startup. */
	autoMigrate?: boolean;

	/** Auto-seed on startup. */
	autoSeed?: boolean | SeedCategory | SeedCategory[];

	/** CLI-specific configuration (used by `questpie` CLI commands). */
	cli?: {
		/** Migration directory for generated migrations. @default "./src/migrations" */
		migrations?: { directory?: string };
		/** Seed directory for generated seeds. @default "./src/seeds" */
		seeds?: { directory?: string };
	};

	/**
	 * Extensible — admin plugin may read additional keys from here.
	 */
	[key: string]: unknown;
}

// ============================================================================
// RuntimeConfigInput — input type for runtimeConfig() with cloud defaults
// ============================================================================

/**
 * Input type for {@link runtimeConfig} — accepts the same shape as
 * {@link RuntimeConfig} but `app` and `db` are **optional** because they can
 * be auto-resolved from environment variables.
 *
 * **Resolution order** (for each field):
 * 1. Explicit value passed by the user (wins).
 * 2. `QUESTPIE_*` environment variables (set by QUESTPIE Cloud).
 * 3. Standard env vars (`DATABASE_URL`, `APP_URL`, `BETTER_AUTH_SECRET`).
 * 4. Sensible defaults (`http://localhost:3000` for app URL).
 *
 * If `db` cannot be resolved from any source, `runtimeConfig()` throws.
 *
 * @example Zero-config for QUESTPIE Cloud:
 * ```ts
 * // questpie.config.ts — just works when QUESTPIE_* env vars are set
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 * });
 * ```
 *
 * @example Explicit overrides:
 * ```ts
 * export default runtimeConfig({
 *   plugins: [adminPlugin()],
 *   app: { url: "https://my-app.example.com" },
 *   db: { url: process.env.MY_CUSTOM_DB! },
 * });
 * ```
 *
 * @see {@link RuntimeConfig} for the resolved output type.
 */
export type RuntimeConfigInput = Partial<Pick<RuntimeConfig, "app" | "db">> &
	Omit<RuntimeConfig, "app" | "db">;

// ============================================================================
// App Definition — what codegen generates (first arg to createApp)
// ============================================================================

/**
 * Application definition — the full entity tree generated by codegen.
 * Passed as the first argument to `createApp(definition, runtime)`.
 *
 * Contains modules (from `modules.ts`), user entities (from file convention),
 * and plugin-discovered items (e.g. blocks, sidebar, dashboard, branding).
 *
 * @example
 * ```ts
 * // .generated/index.ts
 * export const app: App = createApp(
 *   {
 *     modules: _modules,
 *     collections: { posts: _coll_posts },
 *     globals: { siteSettings: _glob_siteSettings },
 *     routes: { "webhooks/stripe": _route_webhooks_stripe, createBooking: _fn_createBooking },
 *     auth: _auth,
 *     locale: _locale,
 *     sidebar: _sidebar,
 *     dashboard: _dashboard,
 *     branding: _branding,
 *   },
 *   _runtime,
 * ) as unknown as App;
 * ```
 *
 * @see RFC-MODULE-ARCHITECTURE §9.1 (Root App)
 */
export interface AppDefinition {
	/** Modules from `modules.ts` — static module imports. */
	modules?: ModuleDefinition[];

	/** Collections discovered from `collections/` directory. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals discovered from `globals/` directory. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Jobs discovered from `jobs/` directory. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Routes discovered from `routes/` directory. */
	routes?: Record<string, RouteDefinition>;

	/** Services discovered from `services/` directory. */
	services?: Record<
		string,
		import("#questpie/server/services/define-service.js").ServiceBuilder<any>
	>;

	/** Email templates discovered from `emails/` directory. */
	emailTemplates?: Record<
		string,
		import("#questpie/server/integrated/mailer/index.js").EmailTemplateDefinition<
			any,
			any
		>
	>;

	/** Auth config from `auth.ts`. Deep-merged on top of module auth. */
	auth?: BetterAuthOptions | Record<string, any>;

	/** Content locale config from `locale.ts`. */
	locale?: LocaleConfig;

	/** Global lifecycle hooks from `hooks.ts`. */
	hooks?: GlobalHooksState;

	/** Default access rules from `access.ts`. */
	defaultAccess?: CollectionAccess;

	/** Context resolver from `context.ts`. */
	contextResolver?: ContextResolver;

	/**
	 * Messages from `messages/` directory, keyed by locale.
	 * Deep-merged on top of module messages.
	 */
	messages?: Record<string, Record<string, string>>;

	/** User-level migrations. */
	migrations?: Migration[];

	/** User-level seeds. */
	seeds?: Seed[];

	/**
	 * Extensible — admin plugin augments this interface to add:
	 * blocks, sidebar, dashboard, branding, adminLocale.
	 */
	[key: string]: unknown;
}

// ============================================================================
// Config Input — what config() accepts (legacy, use RuntimeConfig for new code)
// ============================================================================

/**
 * Application configuration — the shape of `questpie.config.ts`.
 * Created via `config({ ... })`. Passed to `createApp()` along with
 * discovered entities from file convention (or hand-written).
 *
 * For new code, use `RuntimeConfig` with `runtimeConfig()` instead.
 *
 * @see RFC §12 (config() Full API), §12.1 (Config Shape)
 */
export interface AppConfig {
	/** Modules to compose — order matters, later overrides earlier. */
	modules?: ModuleDefinition[];

	/** Application URL (required). */
	app: { url: string };

	/** Database connection (required). */
	db: DbConfig;

	/** Secret key for signing tokens. */
	secret?: string;

	/** Storage configuration. */
	storage?: StorageConfig;

	/** Email configuration with adapter. */
	email?: MailerConfig;

	/** Queue configuration with adapter. */
	queue?: { adapter: QueueAdapter };

	/** Search adapter for full-text search. */
	search?: SearchAdapter;

	/** Realtime configuration. */
	realtime?: RealtimeConfig;

	/** Logger configuration. */
	logger?: LoggerConfig;

	/** KV store configuration. */
	kv?: KVConfig;

	/** Auth configuration — deep-merged with module auth contributions. */
	auth?: BetterAuthOptions | Record<string, any>;

	/** Content localization. */
	locale?: LocaleConfig;

	/** Default access control (applied when entities don't define their own). */
	defaultAccess?: CollectionAccess;

	/** Global lifecycle hooks. */
	hooks?: GlobalHooksState;

	/** Context resolver for extending request context. */
	contextResolver?: ContextResolver;

	/** I18n translations config (backend messages). */
	translations?: TranslationsConfig;

	/** Auto-migrate on startup. */
	autoMigrate?: boolean;

	/** Auto-seed on startup. */
	autoSeed?: boolean | SeedCategory | SeedCategory[];

	/** CLI-specific configuration (used by `questpie` CLI commands). */
	cli?: {
		/** Migration directory for generated migrations. @default "./src/migrations" */
		migrations?: { directory?: string };
		/** Seed directory for generated seeds. @default "./src/seeds" */
		seeds?: { directory?: string };
	};

	/** User-level migrations (from project, not modules). */
	migrations?: Migration[];

	/** User-level seeds (from project, not modules). */
	seeds?: Seed[];

	/**
	 * Extensible — admin module augments this interface to add:
	 * adminLocale, branding, sidebar, dashboard.
	 */
	[key: string]: unknown;
}

// ============================================================================
// App Entities — what codegen discovers (second arg to legacy createApp)
// ============================================================================

/**
 * Entities discovered by file convention or codegen.
 * Passed as the second argument to the legacy `createApp(config, entities)`.
 *
 * For new code, use `AppDefinition` with `createApp(definition, runtime)`.
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */
export interface AppEntities {
	/** Collections discovered from `collections/` directory. */
	collections?: Record<string, AnyCollectionOrBuilder>;

	/** Globals discovered from `globals/` directory. */
	globals?: Record<string, AnyGlobalOrBuilder>;

	/** Jobs discovered from `jobs/` directory. */
	jobs?: Record<string, JobDefinition<any, any>>;

	/** Routes discovered from `routes/` directory. */
	routes?: Record<string, RouteDefinition>;

	/** Auth config from `auth.ts`. Deep-merged on top of module auth. */
	auth?: BetterAuthOptions | Record<string, any>;

	/**
	 * Messages from `messages/` directory, keyed by locale.
	 * Deep-merged on top of module messages.
	 */
	messages?: Record<string, Record<string, string>>;

	/** User-level migrations. */
	migrations?: Migration[];

	/** User-level seeds. */
	seeds?: Seed[];

	/**
	 * Extensible — admin module augments this interface to add:
	 * blocks.
	 */
	[key: string]: unknown;
}

// ============================================================================
// Module Type Extraction Utilities
// ============================================================================

/**
 * Extract property `K` from a single module type, recursing into sub-modules.
 * Resolution order: depth-first, sub-modules first, then self (self overrides sub-modules).
 *
 * @example
 * ```ts
 * type AdminCollections = ExtractFromModule<ReturnType<typeof admin>, "collections">;
 * // { user: ..., assets: ..., session: ..., adminSavedViews: ..., ... }
 * ```
 */
export type ExtractFromModule<M, K extends string> = (M extends {
	modules: infer Sub extends readonly any[];
}
	? ExtractFromModuleArray<Sub, K>
	: // biome-ignore lint/complexity/noBannedTypes: empty object needed for intersection base
		{}) &
	// biome-ignore lint/complexity/noBannedTypes: empty object used as intersection identity
	(K extends keyof M ? (M[K] extends Record<string, any> ? M[K] : {}) : {});

/**
 * Extract property `K` from an array of module types, left-to-right.
 * Later modules override earlier ones (intersection semantics).
 *
 * @example
 * ```ts
 * type AllModuleCollections = ExtractFromModuleArray<typeof [starterModule, adminModule], "collections">;
 * ```
 */
export type ExtractFromModuleArray<
	A extends readonly any[],
	K extends string,
> = A extends readonly [infer First, ...infer Rest]
	? ExtractFromModule<First, K> & ExtractFromModuleArray<Rest, K>
	: // biome-ignore lint/complexity/noBannedTypes: empty object needed for tuple base case
		{};

/**
 * Extract property `K` from a config type's `modules` array.
 * Top-level entry point for extracting module contributions.
 *
 * @example
 * ```ts
 * // In .generated/index.ts:
 * import _config from "../questpie.config";
 *
 * type ModuleCollections = ExtractModulesProperty<typeof _config, "collections">;
 * type ModuleJobs = ExtractModulesProperty<typeof _config, "jobs">;
 * type ModuleRoutes = ExtractModulesProperty<typeof _config, "routes">;
 * ```
 *
 * @see RFC §15.1 (Complete .generated/index.ts Example)
 */
export type ExtractModulesProperty<Config, K extends string> = Config extends {
	modules: infer M extends readonly any[];
}
	? ExtractFromModuleArray<M, K>
	: // biome-ignore lint/complexity/noBannedTypes: empty object needed for config without modules
		{};
