/**
 * Tests: codegen module template generation
 *
 * Covers:
 * 1. `generateModuleTemplate` — minimal module (empty)
 * 2. Collections — record emission with type interfaces
 * 3. Jobs — record emission
 * 4. Routes — flat emission with bundles
 * 5. Migrations, seeds — array emission
 * 6. Singles — auth, fields, sidebar (moduleEmit: "array")
 * 7. Sub-modules via modules.ts
 * 8. Registry augmentation via registryKey
 * 9. Type prefix derivation (questpie-admin → Admin)
 * 10. Named vs default import generation
 * 11. Extra module properties with extracted consts
 * 12. Empty stubs for declared categories without files
 * 13. keyFromProperty categories skip named type interfaces
 */
import { describe, expect, it } from "bun:test";
import { generateModuleTemplate } from "../../src/cli/codegen/module-template.js";
import type {
	CategoryDeclaration,
	DiscoveredFile,
	DiscoveryResult,
} from "../../src/cli/codegen/types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function makeFile(
	key: string,
	opts: {
		varName?: string;
		importPath?: string;
		exportType?: "default" | "named" | "unknown";
		namedExportName?: string;
		source?: string;
		isBundle?: boolean;
	} = {},
): DiscoveredFile {
	return {
		absolutePath: `/root/${key}.ts`,
		key,
		varName: opts.varName ?? `_${key.replace(/[./]/g, "_")}`,
		importPath: opts.importPath ?? `../${key}`,
		exportType: opts.exportType ?? "default",
		namedExportName: opts.namedExportName,
		source: opts.source ?? `${key}.ts`,
		isBundle: opts.isBundle,
	};
}

function emptyResult(categoryNames: string[] = []): DiscoveryResult {
	const categories = new Map<string, Map<string, DiscoveredFile>>();
	for (const name of categoryNames) {
		categories.set(name, new Map());
	}
	return {
		categories,
		singles: new Map(),
		spreads: new Map(),
	};
}

/** Minimal category meta with just collections and jobs. */
function baseCategoryMeta(): Map<string, CategoryDeclaration> {
	return new Map<string, CategoryDeclaration>([
		[
			"collections",
			{
				dirs: ["collections"],
				prefix: "coll",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"globals",
			{
				dirs: ["globals"],
				prefix: "glob",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"jobs",
			{
				dirs: ["jobs"],
				prefix: "job",
				emit: "record",
				registryKey: true,
			},
		],
		[
			"routes",
			{
				dirs: ["routes", "functions"],
				prefix: "route",
				emit: "record",
				recursive: true,
				keySeparator: "/",
				registryKey: true,
				includeInAppState: true,
			},
		],
		[
			"migrations",
			{
				dirs: ["migrations"],
				prefix: "mig",
				emit: "array",
				typeEmit: "none",
			},
		],
		[
			"seeds",
			{
				dirs: ["seeds"],
				prefix: "seed",
				emit: "array",
				typeEmit: "none",
			},
		],
		[
			"messages",
			{
				dirs: ["messages"],
				prefix: "msg",
				emit: "record",
				typeEmit: "messages",
			},
		],
	]);
}

function cat(
	result: DiscoveryResult,
	name: string,
): Map<string, DiscoveredFile> {
	let map = result.categories.get(name);
	if (!map) {
		map = new Map();
		result.categories.set(name, map);
	}
	return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Minimal module
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — minimal", () => {
	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: emptyResult(),
		categoryMeta: new Map(),
	});

	it("emits auto-generated header", () => {
		expect(output).toContain("AUTO-GENERATED by questpie codegen");
	});

	it("emits module name as const", () => {
		expect(output).toContain('"questpie-test" as const');
	});

	it("emits module type export", () => {
		expect(output).toContain("export type TestModule = typeof _module;");
	});

	it("emits default export", () => {
		expect(output).toContain("export default _module;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Type prefix derivation
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — type prefix", () => {
	it("derives Admin from questpie-admin", () => {
		const output = generateModuleTemplate({
			moduleName: "questpie-admin",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type AdminModule = typeof _module;");
	});

	it("derives Billing from billing (no questpie- prefix)", () => {
		const output = generateModuleTemplate({
			moduleName: "billing",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type BillingModule = typeof _module;");
	});

	it("derives UserAuth from questpie-user-auth (multi-segment)", () => {
		const output = generateModuleTemplate({
			moduleName: "questpie-user-auth",
			discovered: emptyResult(),
			categoryMeta: new Map(),
		});
		expect(output).toContain("export type UserAuthModule = typeof _module;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Collections — record emission with type interface
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — collections", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set(
		"posts",
		makeFile("posts", {
			varName: "_coll_posts",
			importPath: "../collections/posts",
		}),
	);
	colls.set(
		"comments",
		makeFile("comments", {
			varName: "_coll_comments",
			importPath: "../collections/comments",
		}),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-blog",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits imports for each collection", () => {
		expect(output).toContain(
			'import _coll_comments from "../collections/comments";',
		);
		expect(output).toContain('import _coll_posts from "../collections/posts";');
	});

	it("emits type interface for collections", () => {
		expect(output).toContain("export interface BlogCollections {");
		expect(output).toContain("comments: typeof _coll_comments;");
		expect(output).toContain("posts: typeof _coll_posts;");
	});

	it("emits record in module object with type assertion", () => {
		expect(output).toContain("collections: {");
		expect(output).toContain("comments: _coll_comments,");
		expect(output).toContain("posts: _coll_posts,");
		expect(output).toContain("} as BlogCollections,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Routes — nested emission with bundles
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — routes with slash-separated keys", () => {
	const result = emptyResult(["routes"]);
	const routes = cat(result, "routes");
	routes.set(
		"admin/stats",
		makeFile("admin/stats", { varName: "_route_admin_stats" }),
	);
	routes.set(
		"admin/users/export",
		makeFile("admin/users/export", { varName: "_route_admin_users_export" }),
	);
	routes.set(
		"getConfig",
		makeFile("getConfig", { varName: "_route_getConfig" }),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits flat record with camelCase slash keys", () => {
		expect(output).toContain("routes: {");
		expect(output).toContain('"admin/stats": _route_admin_stats,');
		expect(output).toContain(
			'"admin/users/export": _route_admin_users_export,',
		);
		expect(output).toContain("getConfig: _route_getConfig,");
	});

	it("emits flat type interface with camelCase slash keys", () => {
		expect(output).toContain("export interface TestRoutes {");
		expect(output).toContain('"admin/stats": typeof _route_admin_stats;');
		expect(output).toContain(
			'"admin/users/export": typeof _route_admin_users_export;',
		);
		expect(output).toContain("getConfig: typeof _route_getConfig;");
	});
});

describe("generateModuleTemplate — bundle routes", () => {
	const result = emptyResult(["routes"]);
	const routes = cat(result, "routes");
	routes.set(
		"setup",
		makeFile("setup", { varName: "_route_setup", isBundle: true }),
	);
	routes.set(
		"getConfig",
		makeFile("getConfig", { varName: "_route_getConfig" }),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("spreads bundle files into routes object", () => {
		expect(output).toContain("..._route_setup,");
	});

	it("emits leaf files as record values", () => {
		expect(output).toContain("getConfig: _route_getConfig,");
	});

	it("includes all entries in type (intersection for bundles)", () => {
		// When bundles are present, type is emitted as intersection, not interface
		expect(output).toContain("export type TestRoutes =");
		expect(output).toContain("getConfig: typeof _route_getConfig");
		expect(output).toContain("typeof _route_setup");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Migrations, seeds — array emission
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — array emission", () => {
	const result = emptyResult(["migrations"]);
	const migs = cat(result, "migrations");
	migs.set("001_init", makeFile("001_init", { varName: "_mig_001_init" }));
	migs.set(
		"002_addUsers",
		makeFile("002_addUsers", { varName: "_mig_002_addUsers" }),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits flat array", () => {
		expect(output).toContain("migrations: [_mig_001_init, _mig_002_addUsers],");
	});

	it("does not emit type interface for array categories", () => {
		expect(output).not.toContain("TestMigrations");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Named imports
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — named imports", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set(
		"posts",
		makeFile("posts", {
			varName: "_coll_posts",
			exportType: "named",
			namedExportName: "postsCollection",
			importPath: "../collections/posts",
		}),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits named import with alias", () => {
		expect(output).toContain(
			'import { postsCollection as _coll_posts } from "../collections/posts";',
		);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Sub-modules via modules.ts
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — sub-modules", () => {
	const result = emptyResult();
	result.singles.set(
		"modules",
		makeFile("modules", {
			varName: "_modules",
			importPath: "../modules",
		}),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits modules import", () => {
		expect(output).toContain('import _modules from "../modules";');
	});

	it("emits modules in module object", () => {
		expect(output).toContain("modules: _modules,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Singles (auth, fields, sidebar with moduleEmit: "array")
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — singles", () => {
	const result = emptyResult();
	result.singles.set(
		"fields",
		makeFile("fields", { varName: "_fields", importPath: "../fields" }),
	);
	result.singles.set(
		"defaultAccess",
		makeFile("defaultAccess", {
			varName: "_defaultAccess",
			importPath: "../default-access",
		}),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("emits singles as direct properties", () => {
		expect(output).toContain("defaultAccess: _defaultAccess,");
		expect(output).toContain("fields: _fields,");
	});
});

describe("generateModuleTemplate — singles with moduleEmit: array", () => {
	const result = emptyResult();
	result.singles.set(
		"sidebar",
		makeFile("sidebar", { varName: "_sidebar", importPath: "../sidebar" }),
	);

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: new Map(),
	});

	it("wraps moduleEmit: array singles in array", () => {
		expect(output).toContain("sidebar: [_sidebar],");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Registry augmentation
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — no Registry augmentation", () => {
	const result = emptyResult(["collections"]);
	const colls = cat(result, "collections");
	colls.set("posts", makeFile("posts", { varName: "_coll_posts" }));

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
		expect(output).not.toContain("declare global {");
	});
});

describe("generateModuleTemplate — no Registry even with custom registryKey", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: "~views",
			},
		],
	]);

	const result = emptyResult(["views"]);
	const views = cat(result, "views");
	views.set("table", makeFile("table", { varName: "_view_table" }));

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: meta,
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Empty stubs for declared categories
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — empty stubs", () => {
	const result = emptyResult(["collections", "jobs", "migrations"]);
	// Only collections has files
	const colls = cat(result, "collections");
	colls.set("posts", makeFile("posts", { varName: "_coll_posts" }));

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits empty record for declared categories without files", () => {
		expect(output).toContain("globals: {},");
		expect(output).toContain("jobs: {},");
		expect(output).toContain("routes: {},");
		expect(output).toContain("messages: {},");
	});

	it("emits empty array for array categories without files", () => {
		expect(output).toContain("migrations: [] as const,");
		expect(output).toContain("seeds: [] as const,");
	});

	it("does not emit empty stub for collections (has files)", () => {
		// collections should be a real record, not an empty stub
		expect(output).toContain("posts: _coll_posts,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Extra module properties with extracted consts
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — extra module properties", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"listViews",
			{
				dirs: [],
				prefix: "lv",
				emit: "record",
				registryKey: "listViews",
			},
		],
	]);

	const output = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: emptyResult(),
		categoryMeta: meta,
		extraModuleProperties: [
			"listViews: { table: _reg_table, form: _reg_form },",
		],
	});

	it("extracts registry properties to const before _module", () => {
		expect(output).toContain(
			"const _reg_listViews = { table: _reg_table, form: _reg_form };",
		);
	});

	it("references extracted const in module object", () => {
		expect(output).toContain("listViews: _reg_listViews,");
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// keyFromProperty — skips named type interface
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — keyFromProperty", () => {
	const meta = new Map<string, CategoryDeclaration>([
		[
			"views",
			{
				dirs: ["views"],
				prefix: "view",
				emit: "record",
				registryKey: true,
				keyFromProperty: "name",
			},
		],
	]);

	const result = emptyResult(["views"]);
	const views = cat(result, "views");
	views.set("table", makeFile("table", { varName: "_view_table" }));

	const output = generateModuleTemplate({
		moduleName: "questpie-admin",
		discovered: result,
		categoryMeta: meta,
	});

	it("uses keyFromProperty in module object", () => {
		expect(output).toContain("[_view_table.name]: _view_table,");
	});

	it("does not emit named type interface for keyFromProperty categories", () => {
		expect(output).not.toContain("export interface AdminViews");
	});

	it("does NOT emit Registry augmentation (handled by root template)", () => {
		expect(output).not.toContain("interface Registry {");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Messages — typeEmit: "messages" skips named type
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — messages", () => {
	const result = emptyResult(["messages"]);
	const msgs = cat(result, "messages");
	msgs.set("en", makeFile("en", { varName: "_msg_en" }));
	msgs.set("sk", makeFile("sk", { varName: "_msg_sk" }));

	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: result,
		categoryMeta: baseCategoryMeta(),
	});

	it("emits messages as record without type assertion", () => {
		expect(output).toContain("messages: {");
		expect(output).toContain("en: _msg_en,");
		expect(output).toContain("sk: _msg_sk,");
		// No "as TestMessages" assertion
		expect(output).not.toContain("as TestMessages");
	});

	it("does not emit named type interface for messages", () => {
		expect(output).not.toContain("export interface TestMessages");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Extra imports and type declarations
// ─────────────────────────────────────────────────────────────────────────────

describe("generateModuleTemplate — extra imports", () => {
	const output = generateModuleTemplate({
		moduleName: "questpie-test",
		discovered: emptyResult(),
		categoryMeta: new Map(),
		extraImports: [{ name: "{ filterViewsByKind }", path: "questpie/admin" }],
		extraTypeDeclarations: ["export type CustomType = string;"],
	});

	it("emits extra plugin imports", () => {
		expect(output).toContain(
			'import { filterViewsByKind } from "questpie/admin";',
		);
	});

	it("emits extra type declarations", () => {
		expect(output).toContain("export type CustomType = string;");
	});
});
