/**
 * Tests: codegen template generation
 *
 * Covers:
 * 1. `generateTemplate` — throws without modules.ts
 * 2. Minimal template (just modules.ts) — correct structure emitted
 * 3. Collections, globals, jobs — object syntax in createApp
 * 4. Migrations, seeds — flat array syntax in createApp
 * 5. Named vs default import generation
 * 6. Services — ServiceInstanceOf import
 * 7. Emails — MailerService import
 * 8. Routes — flat record with slash-separated keys
 */
import { describe, expect, it } from "bun:test";

import {
	coreCodegenPlugin,
	resolveTargetGraph,
	runAllTargets,
} from "../../src/cli/codegen/index.js";
import { generateTemplate } from "../../src/cli/codegen/template.js";
import type {
	CategoryDeclaration,
	CodegenPlugin,
	CodegenResult,
	CrossTargetValidator,
	DiscoveredFile,
	DiscoveryResult,
	SingletonFactory,
} from "../../src/cli/codegen/types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Resolve the "server" target from the core plugin (and optional extras). */
function serverTarget(extraPlugins: CodegenPlugin[] = []) {
	const graph = resolveTargetGraph([coreCodegenPlugin(), ...extraPlugins]);
	return graph.get("server")!;
}

/** Get merged categories from the resolved server target. */
function coreCategories(): Record<string, CategoryDeclaration> {
	return serverTarget().categories;
}

/** Get merged singleton factories from the resolved server target. */
function coreSingletonFactories(): Record<string, SingletonFactory> {
	return serverTarget().registries.singletonFactories;
}

function makeFile(
	key: string,
	opts: {
		varName?: string;
		importPath?: string;
		exportType?: "default" | "named" | "unknown";
		namedExportName?: string;
		source?: string;
	} = {},
): DiscoveredFile {
	return {
		absolutePath: `/root/${key}.ts`,
		key,
		varName: opts.varName ?? `_test_${key.replace(/\./g, "_")}`,
		importPath: opts.importPath ?? `../${key}`,
		exportType: opts.exportType ?? "default",
		namedExportName: opts.namedExportName,
		source: opts.source ?? `${key}.ts`,
	};
}

function makeModulesFile(): DiscoveredFile {
	return makeFile("modules", {
		varName: "_modules",
		importPath: "../modules",
		exportType: "default",
	});
}

/** Helper to create an empty DiscoveryResult with optional pre-initialized categories */
function emptyResult(categoryNames: string[] = []): DiscoveryResult {
	const categories = new Map<string, Map<string, DiscoveredFile>>();
	for (const name of categoryNames) {
		categories.set(name, new Map());
	}
	return {
		categories,
		singles: new Map(),
		spreads: new Map(),
	};
}

/**
 * Minimal result with modules.ts as a single.
 * Pre-initializes core category maps so tests can add files to them.
 */
function minimalResult(): DiscoveryResult {
	const result = emptyResult([
		"collections",
		"globals",
		"jobs",
		"routes",
		"messages",
		"services",
		"emails",
		"migrations",
		"seeds",
	]);
	result.singles.set("modules", makeModulesFile());
	return result;
}

/** Helper to get or create a category map */
function cat(
	result: DiscoveryResult,
	name: string,
): Map<string, DiscoveredFile> {
	let map = result.categories.get(name);
	if (!map) {
		map = new Map();
		result.categories.set(name, map);
	}
	return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Error cases
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — error cases", () => {
	it("throws when modules.ts is missing", () => {
		expect(() =>
			generateTemplate({
				configImportPath: "../questpie.config",
				discovered: emptyResult(),
			}),
		).toThrow(/modules\.ts is required/);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Minimal template
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — minimal (modules.ts only)", () => {
	let code: string;

	code = generateTemplate({
		configImportPath: "../questpie.config",
		discovered: minimalResult(),
		categories: coreCategories(),
		singletonFactories: coreSingletonFactories(),
	});

	it("emits auto-generated header", () => {
		expect(code).toContain("AUTO-GENERATED by questpie codegen");
		expect(code).toContain("DO NOT EDIT");
	});

	it("imports createApp from questpie", () => {
		expect(code).toContain("import { createApp");
		expect(code).toContain('from "questpie"');
	});

	it("imports runtime config", () => {
		expect(code).toContain('import _runtime from "../questpie.config"');
	});

	it("imports modules file", () => {
		expect(code).toContain('import _modules from "../modules"');
	});

	it("emits AppCollections type alias (no user collections)", () => {
		expect(code).toContain("export type AppCollections = _ModuleCollections;");
	});

	it("emits AppGlobals type alias (no user globals)", () => {
		expect(code).toContain("export type AppGlobals = _ModuleGlobals;");
	});

	it("emits AppJobs type alias (no user jobs)", () => {
		expect(code).toContain("export type AppJobs = _ModuleJobs;");
	});

	it("emits AppRoutes type alias (no user routes)", () => {
		expect(code).toContain("export type AppRoutes = _ModuleRoutes;");
	});

	it("emits declare global augmentation for AppContext", () => {
		expect(code).toContain("declare global {");
		expect(code).toContain("namespace Questpie {");
		expect(code).toContain("interface AppContext");
		expect(code).toContain("collections: _CollectionsAPI;");
	});

	it("emits AppConfig type", () => {
		expect(code).toContain("export type AppConfig = {");
		expect(code).toContain("collections: AppCollections & Record<string, any>;");
		expect(code).toContain("globals: AppGlobals & Record<string, any>;");
	});

	it("emits createApp call with modules", () => {
		expect(code).toContain("export const app = await createApp(");
		expect(code).toContain("modules: _modules,");
		expect(code).not.toContain("ModuleDefinition[]");
	});

	it("derives session from auth config instead of typeof app", () => {
		expect(code).toContain("type _AppSession =");
		expect(code).toContain("InferSessionFromAuthConfig<_AppAuthConfig>");
		expect(code).toContain("session: _AppSession;");
		expect(code).not.toContain("(typeof app)['auth']");
	});

	it("emits createContext helper", () => {
		expect(code).toContain(
			"export const createContext = createContextFactory(app);",
		);
	});

	it("emits factory comment", () => {
		expect(code).toContain("Factories:");
	});

	it("does not emit migrations section when no migrations", () => {
		expect(code).not.toContain("migrations:");
	});

	it("does not emit seeds section when no seeds", () => {
		expect(code).not.toContain("seeds:");
	});
});

describe("generateTemplate — registry dedupe", () => {
	it("emits ~fieldTypes exactly once when category and singleton both contribute", () => {
		const result = minimalResult();
		result.categories.set(
			"fieldTypes",
			new Map([
				[
					"color",
					makeFile("color", {
						varName: "_ftype_color",
						importPath: "../fields/color",
						exportType: "named",
						namedExportName: "colorField",
					}),
				],
			]),
		);
		result.singles.set(
			"fields",
			makeFile("fields", {
				varName: "_fields",
				importPath: "../fields",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
			discoverPatterns: serverTarget().discover,
		});

		const fieldTypeLines = code
			.split("\n")
			.filter((line) => line.includes('"~fieldTypes":'));
		expect(fieldTypeLines).toEqual([
			'\t\t\t"~fieldTypes": _Registry_FieldTypes & _AllModuleFields;',
		]);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Collections
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — collections", () => {
	it("emits named import for named export collection", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				importPath: "../collections/posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			'import { posts as _coll_posts } from "../collections/posts"',
		);
	});

	it("emits default import for default export collection", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				importPath: "../collections/posts",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _coll_posts from "../collections/posts"');
	});

	it("emits collections object in createApp", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("collections: {");
		expect(code).toContain("posts: _coll_posts,");
	});

	it("emits AppCollections type intersection when user collections exist", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			"export type AppCollections = _ModuleCollections & {",
		);
		expect(code).toContain("posts: typeof _coll_posts;");
	});

	it("emits multiple collections sorted alphabetically", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"users",
			makeFile("users", {
				varName: "_coll_users",
				exportType: "named",
				namedExportName: "users",
			}),
		);
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		const postsIdx = code.indexOf("posts: _coll_posts,");
		const usersIdx = code.indexOf("users: _coll_users,");
		expect(postsIdx).toBeLessThan(usersIdx);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Globals
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — globals", () => {
	it("emits globals object in createApp", () => {
		const result = minimalResult();
		cat(result, "globals").set(
			"siteSettings",
			makeFile("siteSettings", {
				varName: "_glob_siteSettings",
				exportType: "named",
				namedExportName: "siteSettings",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("globals: {");
		expect(code).toContain("siteSettings: _glob_siteSettings,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Migrations — flat array
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — migrations", () => {
	it("emits migrations as flat array in createApp", () => {
		const result = minimalResult();
		cat(result, "migrations").set(
			"001Init",
			makeFile("001Init", { varName: "_mig_001Init", exportType: "default" }),
		);
		cat(result, "migrations").set(
			"002AddUsers",
			makeFile("002AddUsers", {
				varName: "_mig_002AddUsers",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Flat array (sorted alphabetically by key: 001Init < 002AddUsers)
		expect(code).toContain("migrations: [_mig_001Init, _mig_002AddUsers],");
	});

	it("emits migration imports", () => {
		const result = minimalResult();
		cat(result, "migrations").set(
			"001Init",
			makeFile("001Init", {
				varName: "_mig_001Init",
				importPath: "../migrations/001-init",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _mig_001Init from "../migrations/001-init"');
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Seeds — flat array
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — seeds", () => {
	it("emits seeds as flat array in createApp", () => {
		const result = minimalResult();
		cat(result, "seeds").set(
			"demoData",
			makeFile("demoData", {
				varName: "_seed_demoData",
				exportType: "default",
			}),
		);
		cat(result, "seeds").set(
			"siteSettings",
			makeFile("siteSettings", {
				varName: "_seed_siteSettings",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Flat array (sorted: demoData < siteSettings)
		expect(code).toContain("seeds: [_seed_demoData, _seed_siteSettings],");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Services
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — services", () => {
	it("imports ServiceInstanceOf type utility", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("ServiceInstanceOf");
	});

	it("emits services in AppServices type", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("type _AppServiceDefinitions = _ModuleServices & {");
		expect(code).toContain("stripe: typeof _svc_stripe;");
		expect(code).toContain(
			"[K in keyof _AppServiceDefinitions]: ServiceInstanceOf<_AppServiceDefinitions[K]>;",
		);
	});

	it("emits namespace-aware service context helpers", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			"type _AppTopLevelServices = ServiceTopLevelInstances<_AppServiceDefinitions>;",
		);
		expect(code).toContain(
			"type _AppCustomServiceNamespaces = ServiceCustomNamespaceInstances<_AppServiceDefinitions>;",
		);
		expect(code).toContain(
			"interface AppContext extends _AppTopLevelServices, _AppCustomServiceNamespaces {",
		);
		expect(code).toContain("services: _AppDefaultServices;");
		expect(code).toContain(
			"interface ServiceCreateContext extends AppContext {}",
		);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Emails
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — emails", () => {
	it("emits MailerService import when emails exist", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import type { MailerService } from "questpie"');
	});

	it("emits email: MailerService<AppEmailTemplates> in AppContext", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("email: MailerService<AppEmailTemplates>;");
	});

	it("emits emailTemplates object in createApp", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("emailTemplates: {");
		expect(code).toContain("welcome: _email_welcome,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Routes — flat record with slash-separated keys
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — routes (flat record)", () => {
	it("emits flat route as direct key", () => {
		const result = minimalResult();
		cat(result, "routes").set(
			"ping",
			makeFile("ping", { varName: "_route_ping", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("routes: {");
		expect(code).toContain("ping: _route_ping,");
	});

	it("emits slash-separated route key as quoted string key", () => {
		const result = minimalResult();
		cat(result, "routes").set(
			"admin/stats",
			makeFile("admin/stats", {
				varName: "_route_admin_stats",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("routes: {");
		expect(code).toContain('"admin/stats": _route_admin_stats,');
	});

	it("emits multiple routes as flat record entries", () => {
		const result = minimalResult();
		cat(result, "routes").set(
			"admin/stats",
			makeFile("admin/stats", {
				varName: "_route_admin_stats",
				exportType: "default",
			}),
		);
		cat(result, "routes").set(
			"admin/users",
			makeFile("admin/users", {
				varName: "_route_admin_users",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('"admin/stats": _route_admin_stats,');
		expect(code).toContain('"admin/users": _route_admin_users,');
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Auth
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — auth", () => {
	it("emits auth import and includes it in createApp and AppConfig", () => {
		const result = minimalResult();
		result.singles.set(
			"auth",
			makeFile("auth", {
				varName: "_auth",
				importPath: "../auth",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _auth from "../auth"');
		expect(code).toContain("auth: _auth as any,");
		expect(code).toContain("auth: typeof _auth;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Plugin singles (sidebar, dashboard, branding)
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — plugin singles", () => {
	it("emits plugin singles in createApp", () => {
		const result = minimalResult();
		result.singles.set(
			"sidebar",
			makeFile("sidebar", {
				varName: "_sidebar",
				importPath: "../sidebar",
				exportType: "default",
			}),
		);
		result.singles.set(
			"branding",
			makeFile("branding", {
				varName: "_branding",
				importPath: "../branding",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _sidebar from "../sidebar"');
		expect(code).toContain("sidebar: _sidebar as any,");
		expect(code).toContain("branding: _branding as any,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Core singles (locale, hooks, access)
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — core singles", () => {
	it("emits locale single in createApp", () => {
		const result = minimalResult();
		result.singles.set(
			"locale",
			makeFile("locale", {
				varName: "_locale",
				importPath: "../locale",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("locale: _locale as any,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Spreads (mergeStrategy: "spread")
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — spreads", () => {
	function makeSpreadResult(files: DiscoveredFile[]): DiscoveryResult {
		const result = minimalResult();
		result.spreads.set("sidebar", files);
		return result;
	}

	it("imports all spread files", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", {
				varName: "_sidebar_root",
				importPath: "../sidebar",
				exportType: "default",
			}),
			makeFile("sidebar", {
				varName: "_sidebar_admin",
				importPath: "../features/admin/sidebar",
				exportType: "default",
			}),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _sidebar_root from "../sidebar"');
		expect(code).toContain(
			'import _sidebar_admin from "../features/admin/sidebar"',
		);
	});

	it("emits spread array in createApp", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
			makeFile("sidebar", { varName: "_sidebar_admin", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			"sidebar: [...(_sidebar_root as any ?? []), ...(_sidebar_admin as any ?? [])],",
		);
	});

	it("emits a single-item spread array when only root file exists", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("sidebar: [...(_sidebar_root as any ?? [])],");
	});

	it("emits _Module<Key> type for module contributions", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('type _ModuleSidebar = _MP<"sidebar">');
	});

	it("does not put spread keys into singles or plugin singles section", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Spread singles should not appear as plain singles (no "sidebar: _sidebar_root as any,")
		expect(code).not.toContain("sidebar: _sidebar_root as any,");
	});

	it("emits spread section label in imports", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("Sidebar (spread)");
	});

	it("supports multiple spread keys", () => {
		const result = minimalResult();
		result.spreads.set("sidebar", [
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);
		result.spreads.set("dashboard", [
			makeFile("dashboard", {
				varName: "_dashboard_root",
				exportType: "default",
			}),
			makeFile("dashboard", {
				varName: "_dashboard_admin",
				exportType: "default",
			}),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("sidebar: [...(_sidebar_root as any ?? [])],");
		expect(code).toContain(
			"dashboard: [...(_dashboard_root as any ?? []), ...(_dashboard_admin as any ?? [])],",
		);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Plugin factory re-exports
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — factory re-exports", () => {
	it("includes factory comment in output", () => {
		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: minimalResult(),
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Factory re-exports are now emitted as a comment
		expect(code).toContain("Factories:");
		expect(code).toContain("collection");
		expect(code).toContain("global");
	});

	it("generates valid code with plugin singleton factories", () => {
		const adminPlugin: CodegenPlugin = {
			name: "admin",
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
					registries: {
						singletonFactories: {
							branding: {
								configType: "BrandingConfig",
								imports: [],
							},
						},
					},
				},
			},
		};
		const target = serverTarget([adminPlugin]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: minimalResult(),
			categories: target.categories,
			singletonFactories: target.registries.singletonFactories,
		});

		// Template still generates valid output
		expect(code).toContain("createApp");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// 10. Multi-target (runAllTargets)
// ─────────────────────────────────────────────────────────────────────────────

describe("runAllTargets", () => {
	it("generates the server target by default (single target)", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		// Create a temp directory with a minimal setup
		const dir = await mkdtemp(join(tmpdir(), "codegen-multi-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		// Create a modules.ts
		await writeFile(join(dir, "modules.ts"), "export default [];");

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [],
		});

		expect(result.targets.size).toBe(1);
		expect(result.targets.has("server")).toBe(true);
		expect(result.errors.length).toBe(0);

		const serverResult = result.targets.get("server")!;
		expect(serverResult.targetId).toBe("server");
		expect(serverResult.code).toContain("createApp");
		expect(serverResult.outputPath).toContain(".generated");
	});

	it("runs custom generator for non-default targets", async () => {
		const { mkdtemp, writeFile } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-custom-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(dir, "modules.ts"), "export default [];");

		// Create a plugin with a custom target that has a generator
		const customPlugin: CodegenPlugin = {
			name: "test-custom",
			targets: {
				"custom-target": {
					root: ".",
					outputFile: "custom.ts",
					generate: async ({ target, discovered }) => {
						return {
							code: `// Custom target: ${target.id}\n// Categories: ${discovered.categories.size}\nexport const custom = true;\n`,
						};
					},
				},
			},
		};

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [customPlugin],
		});

		expect(result.targets.size).toBe(2);
		expect(result.targets.has("server")).toBe(true);
		expect(result.targets.has("custom-target")).toBe(true);
		expect(result.errors.length).toBe(0);

		const customResult = result.targets.get("custom-target")!;
		expect(customResult.targetId).toBe("custom-target");
		expect(customResult.code).toContain("Custom target: custom-target");
		expect(customResult.code).toContain("export const custom = true;");
	});

	it("reports errors per target without failing other targets", async () => {
		const { mkdtemp, writeFile } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-err-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(dir, "modules.ts"), "export default [];");

		// Plugin with a target that throws during generation
		const failingPlugin: CodegenPlugin = {
			name: "test-failing",
			targets: {
				"failing-target": {
					root: ".",
					outputFile: "fail.ts",
					generate: async () => {
						throw new Error("Intentional test failure");
					},
				},
			},
		};

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [failingPlugin],
		});

		// Server should succeed, failing-target should error
		expect(result.targets.has("server")).toBe(true);
		expect(result.targets.has("failing-target")).toBe(false);
		expect(result.errors.length).toBe(1);
		expect(result.errors[0].targetId).toBe("failing-target");
		expect(result.errors[0].error.message).toBe("Intentional test failure");
	});

	it("generates admin-client target with discovered blocks", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		// Create temp dir simulating project layout:
		// server/ — server root
		// admin/  — admin client root (sibling)
		const dir = await mkdtemp(join(tmpdir(), "codegen-admin-client-"));
		const serverDir = join(dir, "server");
		const adminDir = join(dir, "admin");
		await mkdir(serverDir, { recursive: true });
		await mkdir(join(adminDir, "blocks"), { recursive: true });

		// Create server config + modules
		const configPath = join(serverDir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(serverDir, "modules.ts"), "export default [];");

		// Create a block renderer in admin/blocks/
		await writeFile(
			join(adminDir, "blocks", "hero.tsx"),
			"export default function HeroBlock() { return null; }",
		);
		await writeFile(
			join(adminDir, "blocks", "cta.tsx"),
			"export default function CTABlock() { return null; }",
		);

		// Plugin that mimics the admin-client target structure
		const adminClientPlugin: CodegenPlugin = {
			name: "test-admin-client",
			targets: {
				"admin-client": {
					root: "../admin",
					outputFile: "client.ts",
					categories: {
						blocks: {
							dirs: ["blocks"],
							prefix: "block",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
					generate: async ({ target, discovered }) => {
						const blocks = discovered.categories.get("blocks");
						const lines = [
							"// Generated admin client config",
							'import { coreAdminModule } from "@questpie/admin/client";',
							"",
						];

						if (blocks && blocks.size > 0) {
							for (const file of blocks.values()) {
								lines.push(`import ${file.varName} from "${file.importPath}";`);
							}
							lines.push("");

							const entries = [...blocks.values()]
								.sort((a, b) => a.key.localeCompare(b.key))
								.map((f) => `\t${JSON.stringify(f.key)}: ${f.varName},`);
							lines.push("const _admin = coreAdminModule.blocks({");
							lines.push(...entries);
							lines.push("});");
						} else {
							lines.push("const _admin = coreAdminModule;");
						}

						lines.push("");
						lines.push("export default _admin;");
						lines.push("");

						return { code: lines.join("\n") };
					},
				},
			},
		};

		const result = await runAllTargets({
			rootDir: serverDir,
			configPath,
			plugins: [adminClientPlugin],
		});

		expect(result.targets.size).toBe(2);
		expect(result.targets.has("server")).toBe(true);
		expect(result.targets.has("admin-client")).toBe(true);
		expect(result.errors.length).toBe(0);

		const adminResult = result.targets.get("admin-client")!;
		expect(adminResult.targetId).toBe("admin-client");
		expect(adminResult.code).toContain("coreAdminModule");
		expect(adminResult.code).toContain('"cta"');
		expect(adminResult.code).toContain('"hero"');
		expect(adminResult.outputPath).toContain("admin");
		expect(adminResult.outputPath).toContain(".generated");
		expect(adminResult.outputPath).toContain("client.ts");
	});

	it("returns empty validationErrors when no validators registered", async () => {
		const { mkdtemp, writeFile } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-noval-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(dir, "modules.ts"), "export default [];");

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [],
		});

		expect(result.validationErrors).toEqual([]);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// 11. Cross-target projection validators
// ─────────────────────────────────────────────────────────────────────────────

describe("cross-target projection validators", () => {
	/**
	 * Helper: create a minimal CodegenResult with specified category files.
	 */
	function makeFakeResult(
		targetId: string,
		categories: Record<string, string[]>,
	): CodegenResult {
		const catMap = new Map<string, Map<string, DiscoveredFile>>();
		for (const [catName, keys] of Object.entries(categories)) {
			const fileMap = new Map<string, DiscoveredFile>();
			for (const key of keys) {
				fileMap.set(
					key,
					makeFile(key, {
						varName: `_${catName}_${key}`,
						importPath: `../${catName}/${key}`,
						exportType: "default",
					}),
				);
			}
			catMap.set(catName, fileMap);
		}

		return {
			targetId,
			code: "// fake",
			outputPath: `/fake/.generated/${targetId}.ts`,
			discovered: {
				categories: catMap,
				singles: new Map(),
				spreads: new Map(),
			},
		};
	}

	/**
	 * Simple projection validator for testing — checks that server "blocks"
	 * keys all exist in admin-client "blocks" keys.
	 */
	const testBlocksValidator: CrossTargetValidator = (targets) => {
		const server = targets.get("server");
		const client = targets.get("admin-client");
		if (!server || !client) return [];

		const errors: import("../../src/cli/codegen/types.js").ProjectionError[] =
			[];
		const serverBlocks = server.discovered.categories.get("blocks");
		const clientBlocks = client.discovered.categories.get("blocks");

		if (!serverBlocks) return [];
		const clientKeys = new Set(clientBlocks?.keys() ?? []);

		for (const [key, file] of serverBlocks) {
			if (!clientKeys.has(key)) {
				errors.push({
					severity: "error",
					category: "blocks",
					key,
					sourceTarget: "server",
					consumerTarget: "admin-client",
					message: `Server block "${key}" has no admin client renderer. Create admin/blocks/${key}.tsx`,
				});
			}
		}
		return errors;
	};

	it("reports no errors when server and client blocks match", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-proj-ok-"));
		const serverDir = join(dir, "server");
		const adminDir = join(dir, "admin");
		await mkdir(join(serverDir, "blocks"), { recursive: true });
		await mkdir(join(adminDir, "blocks"), { recursive: true });

		const configPath = join(serverDir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(serverDir, "modules.ts"), "export default [];");

		// Both server and client have "hero" block
		await writeFile(
			join(serverDir, "blocks", "hero.ts"),
			"export default { name: 'hero' };",
		);
		await writeFile(
			join(adminDir, "blocks", "hero.tsx"),
			"export default function HeroBlock() { return null; }",
		);

		const plugin: CodegenPlugin = {
			name: "test-proj",
			validators: [testBlocksValidator],
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
					discover: {
						blocks: "blocks/*.ts",
					},
				},
				"admin-client": {
					root: "../admin",
					outputFile: "client.ts",
					categories: {
						blocks: {
							dirs: ["blocks"],
							prefix: "block",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
					generate: async () => ({ code: "// ok" }),
				},
			},
		};

		const result = await runAllTargets({
			rootDir: serverDir,
			configPath,
			plugins: [plugin],
		});

		expect(result.validationErrors).toEqual([]);
	});

	it("reports errors when server blocks have no admin client counterpart", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-proj-fail-"));
		const serverDir = join(dir, "server");
		const adminDir = join(dir, "admin");
		await mkdir(join(serverDir, "blocks"), { recursive: true });
		await mkdir(join(adminDir, "blocks"), { recursive: true });

		const configPath = join(serverDir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(serverDir, "modules.ts"), "export default [];");

		// Server has "hero" and "gallery" blocks, client only has "hero"
		await writeFile(
			join(serverDir, "blocks", "hero.ts"),
			"export default { name: 'hero' };",
		);
		await writeFile(
			join(serverDir, "blocks", "gallery.ts"),
			"export default { name: 'gallery' };",
		);
		await writeFile(
			join(adminDir, "blocks", "hero.tsx"),
			"export default function HeroBlock() { return null; }",
		);

		const plugin: CodegenPlugin = {
			name: "test-proj-fail",
			validators: [testBlocksValidator],
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
					discover: {
						blocks: "blocks/*.ts",
					},
				},
				"admin-client": {
					root: "../admin",
					outputFile: "client.ts",
					categories: {
						blocks: {
							dirs: ["blocks"],
							prefix: "block",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
					generate: async () => ({ code: "// ok" }),
				},
			},
		};

		const result = await runAllTargets({
			rootDir: serverDir,
			configPath,
			plugins: [plugin],
		});

		expect(result.validationErrors.length).toBe(1);
		expect(result.validationErrors[0].severity).toBe("error");
		expect(result.validationErrors[0].category).toBe("blocks");
		expect(result.validationErrors[0].key).toBe("gallery");
		expect(result.validationErrors[0].sourceTarget).toBe("server");
		expect(result.validationErrors[0].consumerTarget).toBe("admin-client");
		expect(result.validationErrors[0].message).toContain("gallery");
	});

	it("reports multiple validation errors from multiple categories", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-proj-multi-"));
		const serverDir = join(dir, "server");
		const adminDir = join(dir, "admin");
		await mkdir(join(serverDir, "blocks"), { recursive: true });
		await mkdir(join(serverDir, "components"), { recursive: true });
		await mkdir(join(adminDir, "blocks"), { recursive: true });
		// Note: no admin/components/ directory

		const configPath = join(serverDir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(serverDir, "modules.ts"), "export default [];");

		// Server has blocks and components, client has neither
		await writeFile(
			join(serverDir, "blocks", "hero.ts"),
			"export default { name: 'hero' };",
		);
		await writeFile(
			join(serverDir, "components", "rating.ts"),
			"export default { name: 'rating' };",
		);

		// Validator for both blocks and components
		const multiValidator: CrossTargetValidator = (targets) => {
			const server = targets.get("server");
			const client = targets.get("admin-client");
			if (!server || !client) return [];

			const errors: import("../../src/cli/codegen/types.js").ProjectionError[] =
				[];
			for (const cat of ["blocks", "components"]) {
				const serverFiles = server.discovered.categories.get(cat);
				const clientFiles = client.discovered.categories.get(cat);
				if (!serverFiles) continue;
				const clientKeys = new Set(clientFiles?.keys() ?? []);
				for (const [key] of serverFiles) {
					if (!clientKeys.has(key)) {
						errors.push({
							severity: "error",
							category: cat,
							key,
							sourceTarget: "server",
							consumerTarget: "admin-client",
							message: `Missing ${cat}/${key}`,
						});
					}
				}
			}
			return errors;
		};

		const plugin: CodegenPlugin = {
			name: "test-multi-val",
			validators: [multiValidator],
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
					discover: {
						blocks: "blocks/*.ts",
						components: "components/*.ts",
					},
				},
				"admin-client": {
					root: "../admin",
					outputFile: "client.ts",
					categories: {
						blocks: {
							dirs: ["blocks"],
							prefix: "block",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
						components: {
							dirs: ["components"],
							prefix: "comp",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
					generate: async () => ({ code: "// ok" }),
				},
			},
		};

		const result = await runAllTargets({
			rootDir: serverDir,
			configPath,
			plugins: [plugin],
		});

		expect(result.validationErrors.length).toBe(2);
		const blockErr = result.validationErrors.find(
			(e) => e.category === "blocks",
		);
		const compErr = result.validationErrors.find(
			(e) => e.category === "components",
		);
		expect(blockErr).toBeDefined();
		expect(blockErr!.key).toBe("hero");
		expect(compErr).toBeDefined();
		expect(compErr!.key).toBe("rating");
	});

	it("skips validation when one target is missing", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-proj-skip-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(dir, "modules.ts"), "export default [];");

		// Validator that checks server + admin-client, but admin-client target doesn't exist
		const skippedValidator: CrossTargetValidator = (targets) => {
			const server = targets.get("server");
			const client = targets.get("admin-client");
			if (!server || !client) return [];
			return [
				{
					severity: "error",
					category: "test",
					key: "should-not-appear",
					sourceTarget: "server",
					consumerTarget: "admin-client",
					message: "This should never be reached",
				},
			];
		};

		const plugin: CodegenPlugin = {
			name: "test-skip",
			validators: [skippedValidator],
			targets: {},
		};

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [plugin],
		});

		// No admin-client target → validator returns [] → no validation errors
		expect(result.validationErrors).toEqual([]);
	});

	it("aggregates validators from multiple plugins", async () => {
		const { mkdtemp, writeFile, mkdir } = await import("node:fs/promises");
		const { tmpdir } = await import("node:os");
		const { join } = await import("node:path");

		const dir = await mkdtemp(join(tmpdir(), "codegen-proj-agg-"));
		const configPath = join(dir, "questpie.config.ts");
		await writeFile(
			configPath,
			'export default { app: { url: "http://localhost" }, db: { url: "sqlite://:memory:" } };',
		);
		await writeFile(join(dir, "modules.ts"), "export default [];");

		// Two plugins each with a validator that returns one error
		const plugin1: CodegenPlugin = {
			name: "plugin-1",
			validators: [
				() => [
					{
						severity: "error" as const,
						category: "test1",
						key: "a",
						sourceTarget: "server",
						consumerTarget: "other",
						message: "Error from plugin 1",
					},
				],
			],
			targets: {},
		};

		const plugin2: CodegenPlugin = {
			name: "plugin-2",
			validators: [
				() => [
					{
						severity: "warning" as const,
						category: "test2",
						key: "b",
						sourceTarget: "server",
						consumerTarget: "other",
						message: "Warning from plugin 2",
					},
				],
			],
			targets: {},
		};

		const result = await runAllTargets({
			rootDir: dir,
			configPath,
			plugins: [plugin1, plugin2],
		});

		expect(result.validationErrors.length).toBe(2);
		expect(result.validationErrors[0].category).toBe("test1");
		expect(result.validationErrors[0].severity).toBe("error");
		expect(result.validationErrors[1].category).toBe("test2");
		expect(result.validationErrors[1].severity).toBe("warning");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// 12. resolveTargetGraph — conflict detection
// ─────────────────────────────────────────────────────────────────────────────

describe("resolveTargetGraph — conflict detection", () => {
	it("throws on root conflict for the same target", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: "./src",
					outputFile: "index.ts",
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: "./lib",
					outputFile: "index.ts",
				},
			},
		};

		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/root conflict/,
		);
		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/plugin "plugin-b"/,
		);
	});

	it("throws on outDir conflict for the same target", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outDir: ".generated",
					outputFile: "index.ts",
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outDir: ".codegen",
					outputFile: "index.ts",
				},
			},
		};

		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/outDir conflict/,
		);
		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/plugin "plugin-b"/,
		);
	});

	it("throws on outputFile conflict for the same target", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "main.ts",
				},
			},
		};

		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/outputFile conflict/,
		);
		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/plugin "plugin-b"/,
		);
	});

	it("throws when two plugins provide a generator for the same target", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					generate: async () => ({ code: "// a" }),
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					generate: async () => ({ code: "// b" }),
				},
			},
		};

		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/multiple generators/,
		);
		expect(() => resolveTargetGraph([plugin1, plugin2])).toThrow(
			/Plugin "plugin-b"/,
		);
	});

	it("allows compatible contributions from two plugins to the same target", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					categories: {
						blocks: {
							dirs: ["blocks"],
							prefix: "block",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					categories: {
						views: {
							dirs: ["views"],
							prefix: "view",
							registryKey: false,
							includeInAppState: false,
							extractFromModules: false,
						},
					},
					discover: {
						branding: "branding.ts",
					},
				},
			},
		};

		const graph = resolveTargetGraph([plugin1, plugin2]);
		const target = graph.get("my-target")!;

		expect(target).toBeDefined();
		expect(target.categories.blocks).toBeDefined();
		expect(target.categories.views).toBeDefined();
		expect(target.discover.branding).toBe("branding.ts");
	});

	it("allows omitting outDir (defaults to .generated) without conflict", () => {
		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					// no outDir — defaults to .generated
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					// also no outDir — should not conflict
				},
			},
		};

		const graph = resolveTargetGraph([plugin1, plugin2]);
		expect(graph.get("my-target")!.outDir).toBe(".generated");
	});

	it("merges transforms from multiple plugins in order", () => {
		const order: string[] = [];

		const plugin1: CodegenPlugin = {
			name: "plugin-a",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					transform: () => {
						order.push("a");
					},
				},
			},
		};
		const plugin2: CodegenPlugin = {
			name: "plugin-b",
			targets: {
				"my-target": {
					root: ".",
					outputFile: "index.ts",
					transform: () => {
						order.push("b");
					},
				},
			},
		};

		const graph = resolveTargetGraph([plugin1, plugin2]);
		const target = graph.get("my-target")!;

		expect(target.transforms.length).toBe(2);
		// Execute transforms to verify order
		for (const t of target.transforms) {
			t({} as any);
		}
		expect(order).toEqual(["a", "b"]);
	});

	it("creates separate targets for different target IDs", () => {
		const plugin: CodegenPlugin = {
			name: "multi-target",
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
				},
				"admin-client": {
					root: "../admin",
					outputFile: "client.ts",
				},
			},
		};

		const graph = resolveTargetGraph([plugin]);
		expect(graph.size).toBe(2);
		expect(graph.get("server")!.root).toBe(".");
		expect(graph.get("admin-client")!.root).toBe("../admin");
	});
});
