/**
 * Tests: codegen template generation
 *
 * Covers:
 * 1. `generateTemplate` — throws without modules.ts
 * 2. Minimal template (just modules.ts) — correct structure emitted
 * 3. Collections, globals, jobs — object syntax in createApp
 * 4. Migrations, seeds — flat array syntax in createApp
 * 5. Named vs default import generation
 * 6. Services — ServiceInstanceOf import
 * 7. Emails — MailerService import
 * 8. Nested functions — dot-separated keys build nested object
 */
import { describe, expect, it } from "bun:test";
import {
	coreCodegenPlugin,
	resolveTargetGraph,
} from "../../src/cli/codegen/index.js";
import { generateTemplate } from "../../src/cli/codegen/template.js";
import type {
	CategoryDeclaration,
	CodegenPlugin,
	DiscoveredFile,
	DiscoveryResult,
	SingletonFactory,
} from "../../src/cli/codegen/types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Resolve the "server" target from the core plugin (and optional extras). */
function serverTarget(extraPlugins: CodegenPlugin[] = []) {
	const graph = resolveTargetGraph([coreCodegenPlugin(), ...extraPlugins]);
	return graph.get("server")!;
}

/** Get merged categories from the resolved server target. */
function coreCategories(): Record<string, CategoryDeclaration> {
	return serverTarget().categories;
}

/** Get merged singleton factories from the resolved server target. */
function coreSingletonFactories(): Record<string, SingletonFactory> {
	return serverTarget().registries.singletonFactories;
}

function makeFile(
	key: string,
	opts: {
		varName?: string;
		importPath?: string;
		exportType?: "default" | "named" | "unknown";
		namedExportName?: string;
		source?: string;
	} = {},
): DiscoveredFile {
	return {
		absolutePath: `/root/${key}.ts`,
		key,
		varName: opts.varName ?? `_test_${key.replace(/\./g, "_")}`,
		importPath: opts.importPath ?? `../${key}`,
		exportType: opts.exportType ?? "default",
		namedExportName: opts.namedExportName,
		source: opts.source ?? `${key}.ts`,
	};
}

function makeModulesFile(): DiscoveredFile {
	return makeFile("modules", {
		varName: "_modules",
		importPath: "../modules",
		exportType: "default",
	});
}

/** Helper to create an empty DiscoveryResult with optional pre-initialized categories */
function emptyResult(categoryNames: string[] = []): DiscoveryResult {
	const categories = new Map<string, Map<string, DiscoveredFile>>();
	for (const name of categoryNames) {
		categories.set(name, new Map());
	}
	return {
		categories,
		auth: null,
		singles: new Map(),
		spreads: new Map(),
	};
}

/**
 * Minimal result with modules.ts as a single.
 * Pre-initializes core category maps so tests can add files to them.
 */
function minimalResult(): DiscoveryResult {
	const result = emptyResult([
		"collections",
		"globals",
		"jobs",
		"functions",
		"routes",
		"messages",
		"services",
		"emails",
		"migrations",
		"seeds",
	]);
	result.singles.set("modules", makeModulesFile());
	return result;
}

/** Helper to get or create a category map */
function cat(
	result: DiscoveryResult,
	name: string,
): Map<string, DiscoveredFile> {
	let map = result.categories.get(name);
	if (!map) {
		map = new Map();
		result.categories.set(name, map);
	}
	return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Error cases
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — error cases", () => {
	it("throws when modules.ts is missing", () => {
		expect(() =>
			generateTemplate({
				configImportPath: "../questpie.config",
				discovered: emptyResult(),
			}),
		).toThrow(/modules\.ts is required/);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Minimal template
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — minimal (modules.ts only)", () => {
	let code: string;

	code = generateTemplate({
		configImportPath: "../questpie.config",
		discovered: minimalResult(),
		categories: coreCategories(),
		singletonFactories: coreSingletonFactories(),
	});

	it("emits auto-generated header", () => {
		expect(code).toContain("AUTO-GENERATED by questpie codegen");
		expect(code).toContain("DO NOT EDIT");
	});

	it("imports createApp from questpie", () => {
		expect(code).toContain("import { createApp");
		expect(code).toContain('from "questpie"');
	});

	it("imports runtime config", () => {
		expect(code).toContain('import _runtime from "../questpie.config"');
	});

	it("imports modules file", () => {
		expect(code).toContain('import _modules from "../modules"');
	});

	it("emits AppCollections type alias (no user collections)", () => {
		expect(code).toContain("export type AppCollections = _ModuleCollections;");
	});

	it("emits AppGlobals type alias (no user globals)", () => {
		expect(code).toContain("export type AppGlobals = _ModuleGlobals;");
	});

	it("emits AppJobs type alias (no user jobs)", () => {
		expect(code).toContain("export type AppJobs = _ModuleJobs;");
	});

	it("emits AppFunctions type alias (no user functions)", () => {
		expect(code).toContain("export type AppFunctions = _ModuleFunctions;");
	});

	it("emits declare module augmentation for AppContext", () => {
		expect(code).toContain('declare module "questpie"');
		expect(code).toContain("interface AppContext");
	});

	it("emits AppConfig type", () => {
		expect(code).toContain("export type AppConfig = {");
		expect(code).toContain("collections: AppCollections;");
		expect(code).toContain("globals: AppGlobals;");
	});

	it("emits createApp call with modules", () => {
		expect(code).toContain("export const app = createApp(");
		expect(code).toContain("modules: _modules as any");
	});

	it("emits createContext helper", () => {
		expect(code).toContain("export async function createContext(");
	});

	it("emits factory re-export", () => {
		expect(code).toContain('from "./factories.js"');
	});

	it("does not emit migrations section when no migrations", () => {
		expect(code).not.toContain("migrations:");
	});

	it("does not emit seeds section when no seeds", () => {
		expect(code).not.toContain("seeds:");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Collections
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — collections", () => {
	it("emits named import for named export collection", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				importPath: "../collections/posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			'import { posts as _coll_posts } from "../collections/posts"',
		);
	});

	it("emits default import for default export collection", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				importPath: "../collections/posts",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _coll_posts from "../collections/posts"');
	});

	it("emits collections object in createApp", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("collections: {");
		expect(code).toContain("posts: _coll_posts,");
	});

	it("emits AppCollections type intersection when user collections exist", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			"export type AppCollections = _ModuleCollections & {",
		);
		expect(code).toContain("posts: typeof _coll_posts;");
	});

	it("emits multiple collections sorted alphabetically", () => {
		const result = minimalResult();
		cat(result, "collections").set(
			"users",
			makeFile("users", {
				varName: "_coll_users",
				exportType: "named",
				namedExportName: "users",
			}),
		);
		cat(result, "collections").set(
			"posts",
			makeFile("posts", {
				varName: "_coll_posts",
				exportType: "named",
				namedExportName: "posts",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		const postsIdx = code.indexOf("posts: _coll_posts,");
		const usersIdx = code.indexOf("users: _coll_users,");
		expect(postsIdx).toBeLessThan(usersIdx);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Globals
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — globals", () => {
	it("emits globals object in createApp", () => {
		const result = minimalResult();
		cat(result, "globals").set(
			"siteSettings",
			makeFile("siteSettings", {
				varName: "_glob_siteSettings",
				exportType: "named",
				namedExportName: "siteSettings",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("globals: {");
		expect(code).toContain("siteSettings: _glob_siteSettings,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Migrations — flat array
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — migrations", () => {
	it("emits migrations as flat array in createApp", () => {
		const result = minimalResult();
		cat(result, "migrations").set(
			"001Init",
			makeFile("001Init", { varName: "_mig_001Init", exportType: "default" }),
		);
		cat(result, "migrations").set(
			"002AddUsers",
			makeFile("002AddUsers", {
				varName: "_mig_002AddUsers",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Flat array (sorted alphabetically by key: 001Init < 002AddUsers)
		expect(code).toContain("migrations: [_mig_001Init, _mig_002AddUsers],");
	});

	it("emits migration imports", () => {
		const result = minimalResult();
		cat(result, "migrations").set(
			"001Init",
			makeFile("001Init", {
				varName: "_mig_001Init",
				importPath: "../migrations/001-init",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _mig_001Init from "../migrations/001-init"');
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Seeds — flat array
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — seeds", () => {
	it("emits seeds as flat array in createApp", () => {
		const result = minimalResult();
		cat(result, "seeds").set(
			"demoData",
			makeFile("demoData", {
				varName: "_seed_demoData",
				exportType: "default",
			}),
		);
		cat(result, "seeds").set(
			"siteSettings",
			makeFile("siteSettings", {
				varName: "_seed_siteSettings",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Flat array (sorted: demoData < siteSettings)
		expect(code).toContain("seeds: [_seed_demoData, _seed_siteSettings],");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Services
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — services", () => {
	it("emits ServiceInstanceOf import when services exist", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import type { ServiceInstanceOf } from "questpie"');
	});

	it("emits services in AppServices type", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("stripe: ServiceInstanceOf<typeof _svc_stripe>;");
	});

	it("exposes services flat on AppContext", () => {
		const result = minimalResult();
		cat(result, "services").set(
			"stripe",
			makeFile("stripe", {
				varName: "_svc_stripe",
				exportType: "named",
				namedExportName: "stripe",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Should appear inside declare module "questpie" { interface AppContext
		expect(code).toContain("stripe: ServiceInstanceOf<typeof _svc_stripe>;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Emails
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — emails", () => {
	it("emits MailerService import when emails exist", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import type { MailerService } from "questpie"');
	});

	it("emits email: MailerService<AppEmailTemplates> in AppContext", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("email: MailerService<AppEmailTemplates>;");
	});

	it("emits emailTemplates object in createApp", () => {
		const result = minimalResult();
		cat(result, "emails").set(
			"welcome",
			makeFile("welcome", { varName: "_email_welcome", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("emailTemplates: {");
		expect(code).toContain("welcome: _email_welcome,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Functions — nested dot-key builder
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — functions (nested keys)", () => {
	it("emits flat function as direct key", () => {
		const result = minimalResult();
		cat(result, "functions").set(
			"getUsers",
			makeFile("getUsers", { varName: "_fn_getUsers", exportType: "default" }),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("functions: {");
		expect(code).toContain("getUsers: _fn_getUsers,");
	});

	it("emits nested function as nested object", () => {
		const result = minimalResult();
		cat(result, "functions").set(
			"admin.getStats",
			makeFile("admin.getStats", {
				varName: "_fn_admin_getStats",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("admin: {");
		expect(code).toContain("getStats: _fn_admin_getStats,");
	});

	it("groups nested functions under shared parent", () => {
		const result = minimalResult();
		cat(result, "functions").set(
			"admin.getStats",
			makeFile("admin.getStats", {
				varName: "_fn_admin_getStats",
				exportType: "default",
			}),
		);
		cat(result, "functions").set(
			"admin.deleteUser",
			makeFile("admin.deleteUser", {
				varName: "_fn_admin_deleteUser",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// admin appears once as a group
		const adminCount = (code.match(/admin: \{/g) || []).length;
		expect(adminCount).toBeGreaterThanOrEqual(1);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Auth
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — auth", () => {
	it("emits auth import and includes it in createApp and AppConfig", () => {
		const result = minimalResult();
		result.auth = makeFile("auth", {
			varName: "_auth",
			importPath: "../auth",
			exportType: "default",
		});

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _auth from "../auth"');
		expect(code).toContain("auth: _auth,");
		expect(code).toContain("auth: typeof _auth;");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Plugin singles (sidebar, dashboard, branding)
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — plugin singles", () => {
	it("emits plugin singles in createApp", () => {
		const result = minimalResult();
		result.singles.set(
			"sidebar",
			makeFile("sidebar", {
				varName: "_sidebar",
				importPath: "../sidebar",
				exportType: "default",
			}),
		);
		result.singles.set(
			"branding",
			makeFile("branding", {
				varName: "_branding",
				importPath: "../branding",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _sidebar from "../sidebar"');
		expect(code).toContain("sidebar: _sidebar as any,");
		expect(code).toContain("branding: _branding as any,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Core singles (locale, hooks, access, contextResolver)
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — core singles", () => {
	it("emits locale single in createApp", () => {
		const result = minimalResult();
		result.singles.set(
			"locale",
			makeFile("locale", {
				varName: "_locale",
				importPath: "../locale",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("locale: _locale as any,");
	});

	it("emits contextResolver single in createApp", () => {
		const result = minimalResult();
		result.singles.set(
			"contextResolver",
			makeFile("contextResolver", {
				varName: "_contextResolver",
				importPath: "../context",
				exportType: "default",
			}),
		);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("contextResolver: _contextResolver as any,");
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Spreads (mergeStrategy: "spread")
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — spreads", () => {
	function makeSpreadResult(files: DiscoveredFile[]): DiscoveryResult {
		const result = minimalResult();
		result.spreads.set("sidebar", files);
		return result;
	}

	it("imports all spread files", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", {
				varName: "_sidebar_root",
				importPath: "../sidebar",
				exportType: "default",
			}),
			makeFile("sidebar", {
				varName: "_sidebar_admin",
				importPath: "../features/admin/sidebar",
				exportType: "default",
			}),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('import _sidebar_root from "../sidebar"');
		expect(code).toContain(
			'import _sidebar_admin from "../features/admin/sidebar"',
		);
	});

	it("emits spread array in createApp", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
			makeFile("sidebar", { varName: "_sidebar_admin", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain(
			"sidebar: [...(_sidebar_root as any ?? []), ...(_sidebar_admin as any ?? [])],",
		);
	});

	it("emits a single-item spread array when only root file exists", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("sidebar: [...(_sidebar_root as any ?? [])],");
	});

	it("emits _Module<Key> type for module contributions", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain('type _ModuleSidebar = _MP<"sidebar">');
	});

	it("does not put spread keys into singles or plugin singles section", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		// Spread singles should not appear as plain singles (no "sidebar: _sidebar_root as any,")
		expect(code).not.toContain("sidebar: _sidebar_root as any,");
	});

	it("emits spread section label in imports", () => {
		const result = makeSpreadResult([
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("Sidebar (spread)");
	});

	it("supports multiple spread keys", () => {
		const result = minimalResult();
		result.spreads.set("sidebar", [
			makeFile("sidebar", { varName: "_sidebar_root", exportType: "default" }),
		]);
		result.spreads.set("dashboard", [
			makeFile("dashboard", {
				varName: "_dashboard_root",
				exportType: "default",
			}),
			makeFile("dashboard", {
				varName: "_dashboard_admin",
				exportType: "default",
			}),
		]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: result,
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("sidebar: [...(_sidebar_root as any ?? [])],");
		expect(code).toContain(
			"dashboard: [...(_dashboard_root as any ?? []), ...(_dashboard_admin as any ?? [])],",
		);
	});
});

// ─────────────────────────────────────────────────────────────────────────────
// Plugin factory re-exports
// ─────────────────────────────────────────────────────────────────────────────

describe("generateTemplate — factory re-exports", () => {
	it("includes collection and global in factory re-exports by default", () => {
		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: minimalResult(),
			categories: coreCategories(),
			singletonFactories: coreSingletonFactories(),
		});

		expect(code).toContain("collection");
		expect(code).toContain("global");
		expect(code).toContain('from "./factories.js"');
	});

	it("adds plugin singleton factories to re-exports", () => {
		const adminPlugin: CodegenPlugin = {
			name: "admin",
			targets: {
				server: {
					root: ".",
					outputFile: "index.ts",
					registries: {
						singletonFactories: {
							branding: {
								configType: "BrandingConfig",
								imports: [],
							},
						},
					},
				},
			},
		};
		const target = serverTarget([adminPlugin]);

		const code = generateTemplate({
			configImportPath: "../questpie.config",
			discovered: minimalResult(),
			categories: target.categories,
			singletonFactories: target.registries.singletonFactories,
		});

		expect(code).toContain("branding");
	});
});
