/**
 * Page Definition & Factory
 *
 * Defines custom admin pages outside of collections/globals.
 * The `page()` factory returns a plain frozen object.
 */

import type { I18nText } from "../../i18n/types";
import type { IconComponent, MaybeLazyComponent } from "../types/common";

/**
 * Page definition — a plain frozen object describing a custom admin page.
 */
export interface PageDefinition<TName extends string = string> {
	readonly name: TName;
	readonly component: MaybeLazyComponent;
	readonly path?: string;
	readonly showInNav?: boolean;
	/** Display label for navigation. Falls back to formatted page name. */
	readonly label?: I18nText;
	/** Icon for navigation sidebar. */
	readonly icon?: IconComponent;
	/** Navigation group this page belongs to. */
	readonly group?: string;
	/** Sort order within the navigation group (default: 0). */
	readonly order?: number;
}

/**
 * Options accepted by the `page()` factory (everything except `name`).
 */
type PageOptions = {
	component: MaybeLazyComponent;
	showInNav?: boolean;
	path?: string;
	label?: I18nText;
	icon?: IconComponent;
	group?: string;
	order?: number;
};

/**
 * Create a custom page as a plain frozen object.
 *
 * @example
 * ```ts
 * // Generated by `questpie generate`:
 * export default page("login", {
 *   component: async () => ({
 *     default: (await import("./login-page.js")).LoginPage,
 *   }),
 *   showInNav: false,
 *   path: "/login",
 * });
 * ```
 */
export function page<TName extends string>(
	name: TName,
	config: PageOptions,
): PageDefinition<TName> {
	return Object.freeze({
		name,
		component: config.component,
		path: config.path,
		showInNav: config.showInNav,
		label: config.label,
		icon: config.icon,
		group: config.group,
		order: config.order,
	});
}
