/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import { AccordionRenderer as _block_accordion } from "../blocks/accordion";
import { AnnouncementBannerRenderer as _block_announcementBanner } from "../blocks/announcement-banner";
import { ColumnsRenderer as _block_columns } from "../blocks/columns";
import { ContactsListRenderer as _block_contactsList } from "../blocks/contacts-list";
import { CTARenderer as _block_cta } from "../blocks/cta";
import { DividerRenderer as _block_divider } from "../blocks/divider";
import { DocumentsListRenderer as _block_documentsList } from "../blocks/documents-list";
import { GalleryRenderer as _block_gallery } from "../blocks/gallery";
import { HeadingRenderer as _block_heading } from "../blocks/heading";
import { HeroRenderer as _block_hero } from "../blocks/hero";
import { ImageRenderer as _block_image } from "../blocks/image";
import { ImageTextRenderer as _block_imageText } from "../blocks/image-text";
import { LatestNewsRenderer as _block_latestNews } from "../blocks/latest-news";
import { SpacerRenderer as _block_spacer } from "../blocks/spacer";
import { TextRenderer as _block_text } from "../blocks/text";
import { VideoRenderer as _block_video } from "../blocks/video";
import type { BlockRendererProps } from "@questpie/admin/client";
import type { InferBlockValues, InferBlockData } from "@questpie/admin/server";
import type { accordionBlock } from "../../server/blocks/accordion";
import type { announcementBannerBlock } from "../../server/blocks/announcement-banner";
import type { columnsBlock } from "../../server/blocks/columns";
import type { contactsListBlock } from "../../server/blocks/contacts-list";
import type { ctaBlock } from "../../server/blocks/cta";
import type { dividerBlock } from "../../server/blocks/divider";
import type { documentsListBlock } from "../../server/blocks/documents-list";
import type { galleryBlock } from "../../server/blocks/gallery";
import type { headingBlock } from "../../server/blocks/heading";
import type { heroBlock } from "../../server/blocks/hero";
import type { imageBlock } from "../../server/blocks/image";
import type { imageTextBlock } from "../../server/blocks/image-text";
import type { latestNewsBlock } from "../../server/blocks/latest-news";
import type { spacerBlock } from "../../server/blocks/spacer";
import type { textBlock } from "../../server/blocks/text";
import type { videoBlock } from "../../server/blocks/video";

const admin = {
	blocks: { "accordion": _block_accordion, "announcement-banner": _block_announcementBanner, "columns": _block_columns, "contacts-list": _block_contactsList, "cta": _block_cta, "divider": _block_divider, "documents-list": _block_documentsList, "gallery": _block_gallery, "heading": _block_heading, "hero": _block_hero, "image": _block_image, "image-text": _block_imageText, "latest-news": _block_latestNews, "spacer": _block_spacer, "text": _block_text, "video": _block_video },
};

type _ServerBlocks = { "accordion": typeof accordionBlock; "announcement-banner": typeof announcementBannerBlock; "columns": typeof columnsBlock; "contacts-list": typeof contactsListBlock; "cta": typeof ctaBlock; "divider": typeof dividerBlock; "documents-list": typeof documentsListBlock; "gallery": typeof galleryBlock; "heading": typeof headingBlock; "hero": typeof heroBlock; "image": typeof imageBlock; "image-text": typeof imageTextBlock; "latest-news": typeof latestNewsBlock; "spacer": typeof spacerBlock; "text": typeof textBlock; "video": typeof videoBlock };

export type BlockProps<T extends keyof _ServerBlocks> = BlockRendererProps<
	InferBlockValues<_ServerBlocks[T]["state"]>,
	InferBlockData<_ServerBlocks[T]>
>;

export default admin;
