/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module

// ── Collections ────────────────────────────────────────────
import { adminPreferencesCollection as _coll_adminPreferences_collection } from "../collections/admin-preferences.collection";
import { locksCollection as _coll_locks_collection } from "../collections/locks.collection";
import { savedViewsCollection as _coll_savedViews_collection } from "../collections/saved-views.collection";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface AdminPreferencesCollections {
	"adminPreferences.collection": typeof _coll_adminPreferences_collection;
	"locks.collection": typeof _coll_locks_collection;
	"savedViews.collection": typeof _coll_savedViews_collection;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-admin-preferences" as const,
	collections: {
		"adminPreferences.collection": _coll_adminPreferences_collection,
		"locks.collection": _coll_locks_collection,
		"savedViews.collection": _coll_savedViews_collection,
	} as AdminPreferencesCollections,
	globals: {},
	jobs: {},
	routes: {},
	messages: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	views: {},
	components: {},
	blocks: {},
	dashboard: [] as const,
};

export type AdminPreferencesModule = typeof _module;
export default _module;
