/* oxlint-disable */
// AUTO-GENERATED by questpie codegen — DO NOT EDIT
// Regenerate with: questpie generate --module
import "./registries.js";


// ── Collections ────────────────────────────────────────────
import _coll_account from "../collections/account";
import _coll_apikey from "../collections/apikey";
import _coll_assets from "../collections/assets";
import _coll_session from "../collections/session";
import _coll_user from "../collections/user";
import _coll_verification from "../collections/verification";

// ── Jobs ────────────────────────────────────────────
import _job_realtimeCleanup from "../jobs/realtime-cleanup";

// ── Messages ────────────────────────────────────────────
import _msg_en from "../messages/en";

// ── Singles ────────────────────────────────────────────────
import _appConfig from "../config/app";
import _fields from "../fields";

// ════════════════════════════════════════════════════════════
// TYPES — composed from typeof references (zero inference cost)
// ════════════════════════════════════════════════════════════

export interface StarterCollections {
	account: typeof _coll_account;
	apikey: typeof _coll_apikey;
	assets: typeof _coll_assets;
	session: typeof _coll_session;
	user: typeof _coll_user;
	verification: typeof _coll_verification;
}

export interface StarterJobs {
	realtimeCleanup: typeof _job_realtimeCleanup;
}

// ════════════════════════════════════════════════════════════
// MODULE DEFINITION — static plain object
// ════════════════════════════════════════════════════════════

const _module = {
	name: "questpie-starter" as const,
	collections: {
		account: _coll_account,
		apikey: _coll_apikey,
		assets: _coll_assets,
		session: _coll_session,
		user: _coll_user,
		verification: _coll_verification,
	} as StarterCollections,
	jobs: {
		realtimeCleanup: _job_realtimeCleanup,
	} as StarterJobs,
	messages: {
		en: _msg_en,
	},
	globals: {},
	routes: {},
	services: {},
	emails: {},
	migrations: [] as const,
	seeds: [] as const,
	config: {
		app: _appConfig,
	},
	fields: _fields,
};

export type StarterModule = typeof _module;
export default _module;
