/**
 * Scans source files for Iconify icon references (prefix:icon-name)
 * and generates a minimal JSON bundle with only the used icons.
 *
 * Supports ANY icon set from @iconify/json — not limited to Phosphor.
 * Automatically detects which prefixes are used (ph:, mdi:, lucide:, etc.)
 *
 * Usage: bun run packages/admin/scripts/generate-icon-bundle.ts
 *
 * Output: packages/admin/src/client/icons/icon-bundle.ts
 */
import { execSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type IconSet = {
	prefix: string;
	icons: Record<string, { body: string; width?: number; height?: number }>;
	aliases?: Record<string, { parent: string }>;
	width?: number;
	height?: number;
};

const ROOT = resolve(import.meta.dirname, "../../..");

// Scan for all prefix:icon-name references (matches ph:check, mdi:home, lucide:star, etc.)
const grepResult = execSync(
	'grep -roh "[a-z][a-z0-9]*:[a-z0-9-]*" --include="*.ts" --include="*.tsx" packages/ apps/ examples/ 2>/dev/null | sort -u',
	{ cwd: ROOT },
)
	.toString()
	.trim();

// Known iconify prefixes (skip false positives like import paths, css selectors)
const KNOWN_PREFIXES = new Set<string>();
const iconJsonDir = resolve(ROOT, "node_modules/@iconify/json/json");

// Group by prefix
const byPrefix = new Map<string, string[]>();

for (const ref of grepResult.split("\n").filter(Boolean)) {
	const colonIdx = ref.indexOf(":");
	if (colonIdx < 1) continue;
	const prefix = ref.slice(0, colonIdx);
	const name = ref.slice(colonIdx + 1);

	// Skip common false positives
	if (
		prefix.length < 2 ||
		prefix.includes("/") ||
		["http", "https", "data", "var", "oklch", "from", "node", "workspace"].includes(prefix)
	)
		continue;

	// Check if this prefix has a matching icon set JSON
	if (!KNOWN_PREFIXES.has(prefix)) {
		const jsonPath = resolve(iconJsonDir, `${prefix}.json`);
		if (!existsSync(jsonPath)) continue;
		KNOWN_PREFIXES.add(prefix);
	}

	if (!byPrefix.has(prefix)) byPrefix.set(prefix, []);
	byPrefix.get(prefix)!.push(name);
}

if (byPrefix.size === 0) {
	console.log("No icon references found.");
	process.exit(0);
}

// Build minimal bundles per prefix
const collections: Array<{ prefix: string; count: number; sizeKB: number; json: string }> = [];

for (const [prefix, names] of byPrefix) {
	const jsonPath = resolve(iconJsonDir, `${prefix}.json`);
	const iconSet = require(jsonPath) as IconSet;
	const uniqueNames = [...new Set(names)];

	const minimal: IconSet = {
		prefix: iconSet.prefix,
		icons: {},
		width: iconSet.width,
		height: iconSet.height,
	};

	for (const name of uniqueNames) {
		if (iconSet.icons[name]) {
			minimal.icons[name] = iconSet.icons[name];
		} else if (iconSet.aliases?.[name]) {
			const parent = iconSet.aliases[name].parent;
			if (iconSet.icons[parent]) {
				minimal.icons[name] = iconSet.icons[parent];
			}
		}
	}

	// Skip prefixes with no matched icons (false positives)
	if (Object.keys(minimal.icons).length === 0) continue;

	const json = JSON.stringify(minimal);
	collections.push({
		prefix,
		count: Object.keys(minimal.icons).length,
		sizeKB: json.length / 1024,
		json,
	});
}

// Generate output
const totalIcons = collections.reduce((s, c) => s + c.count, 0);
const totalKB = collections.reduce((s, c) => s + c.sizeKB, 0);

const output = `// Auto-generated by scripts/generate-icon-bundle.ts — DO NOT EDIT
// Contains ${totalIcons} icons from ${collections.length} set(s) (${totalKB.toFixed(1)}KB)
import { addCollection } from "@iconify/react";

${collections.map((c) => `// ${c.prefix}: ${c.count} icons (${c.sizeKB.toFixed(1)}KB)\naddCollection(${c.json});`).join("\n\n")}
`;

const outPath = resolve(ROOT, "packages/admin/src/client/icons/icon-bundle.ts");
writeFileSync(outPath, output);

console.log(`Generated ${outPath}`);
for (const c of collections) {
	console.log(`  ${c.prefix}: ${c.count} icons (${c.sizeKB.toFixed(1)}KB)`);
}
console.log(`  Total: ${totalIcons} icons, ${totalKB.toFixed(1)}KB`);
