/**
 * Admin Client Config
 *
 * Auto-generated by questpie codegen — do not edit.
 *
 * Pass this directly to <AdminLayoutProvider admin={admin} />
 */

import { default as _modules } from "../modules";
import { BookingCtaRenderer as _block_bookingCta } from "../blocks/booking-cta";
import _block_columns from "../blocks/columns";
import { ContactInfoRenderer as _block_contactInfo } from "../blocks/contact-info";
import { CTARenderer as _block_cta } from "../blocks/cta";
import _block_divider from "../blocks/divider";
import { GalleryRenderer as _block_gallery } from "../blocks/gallery";
import { HeadingRenderer as _block_heading } from "../blocks/heading";
import { HeroRenderer as _block_hero } from "../blocks/hero";
import { HoursRenderer as _block_hours } from "../blocks/hours";
import { ImageTextRenderer as _block_imageText } from "../blocks/image-text";
import { ReviewsRenderer as _block_reviews } from "../blocks/reviews";
import { ServicesRenderer as _block_services } from "../blocks/services";
import _block_spacer from "../blocks/spacer";
import { StatsRenderer as _block_stats } from "../blocks/stats";
import { TeamRenderer as _block_team } from "../blocks/team";
import { TextRenderer as _block_text } from "../blocks/text";
import type { BlockRendererProps } from "@questpie/admin/client";
import type { InferBlockValues, InferBlockData } from "@questpie/admin/server";
import type { bookingCtaBlock } from "../../server/blocks/booking-cta";
import type { columnsBlock } from "../../server/blocks/columns";
import type { contactInfoBlock } from "../../server/blocks/contact-info";
import type { ctaBlock } from "../../server/blocks/cta";
import type { dividerBlock } from "../../server/blocks/divider";
import type { galleryBlock } from "../../server/blocks/gallery";
import type { headingBlock } from "../../server/blocks/heading";
import type { heroBlock } from "../../server/blocks/hero";
import type { hoursBlock } from "../../server/blocks/hours";
import type { imageTextBlock } from "../../server/blocks/image-text";
import type { reviewsBlock } from "../../server/blocks/reviews";
import type { servicesBlock } from "../../server/blocks/services";
import type { spacerBlock } from "../../server/blocks/spacer";
import type { statsBlock } from "../../server/blocks/stats";
import type { teamBlock } from "../../server/blocks/team";
import type { textBlock } from "../../server/blocks/text";

const admin = {
	blocks: { ..._modules.blocks, "booking-cta": _block_bookingCta, "columns": _block_columns, "contact-info": _block_contactInfo, "cta": _block_cta, "divider": _block_divider, "gallery": _block_gallery, "heading": _block_heading, "hero": _block_hero, "hours": _block_hours, "image-text": _block_imageText, "reviews": _block_reviews, "services": _block_services, "spacer": _block_spacer, "stats": _block_stats, "team": _block_team, "text": _block_text },
	views: { ..._modules.views },
	components: { ..._modules.components },
	fields: { ..._modules.fields },
	pages: { ..._modules.pages },
	widgets: { ..._modules.widgets },
};

type _ServerBlocks = { "booking-cta": typeof bookingCtaBlock; "columns": typeof columnsBlock; "contact-info": typeof contactInfoBlock; "cta": typeof ctaBlock; "divider": typeof dividerBlock; "gallery": typeof galleryBlock; "heading": typeof headingBlock; "hero": typeof heroBlock; "hours": typeof hoursBlock; "image-text": typeof imageTextBlock; "reviews": typeof reviewsBlock; "services": typeof servicesBlock; "spacer": typeof spacerBlock; "stats": typeof statsBlock; "team": typeof teamBlock; "text": typeof textBlock };

export type BlockProps<T extends keyof _ServerBlocks> = BlockRendererProps<
	InferBlockValues<_ServerBlocks[T]["state"]>,
	InferBlockData<_ServerBlocks[T]>
>;

export default admin;
